- lib/generic/modules/appendicitis.json
- lib/generic/states.rb
- test/unit/generic/appendicitis_test.rb
Adds a generic module for Appendicitis. Basic flow is that patients are filtered by gender, and then are assigned to get or not get appendicitis. It picks an age that they will get it with a Delay, and then gives them the Appendicitis condition. There is a chance the appendix will rupture but it leads back into the same sequence of encounters and procedures for an appendectomy. 
Some things not modeled here that could be if we thought it was worthwhile: 
- Appendectomies where they didn't actually have appendicitis
- Complications of surgery
- Lab tests at the appendicitis encounter
This also adds a new State type: Simple. A simple state has no special logic like delay or guard, and doesn't add anything to the patient data, like encounter or procedures. I'm using it here so that we can …
> add appendicitis using generic module framework

- .travis.yml
- Gemfile
- Gemfile.lock
- config/synthea.yml
- lib/modules/encounters.rb
- lib/modules/lifecycle.rb
- lib/synthea.rb
- lib/tasks/tasks.rake
- lib/world/Location.rb
- lib/world/demographics.rb
- lib/world/sequential.rb
Adds the ability to generate 1 city at a time, using real city demographics, to the sequential generator. The generator can now run multithreaded or single-threaded. (Configurable by a synthea.yml property - for fastest performance use JRuby and enable multithreading. Don't enable multithreading on MRI)
Patients are generated in 1 thread per city, and then put into a thread pool to export them.
Adds a new optional parameter to the generate rake task, which accepts a json file of city demographics to use to generate patients. If no file is given it generates pure random patients, as it does today.
Example: 
`bundle exec rake synthea:sequential['./config/Barnstable_County.json']`
Some other changes were needed to accommodate targeting patients to demographics instead of just choosing them …
> sequential generator can generate 1 city per thread

- config/synthea.yml
- lib/generic/modules/appendicitis.json
- lib/modules/cardiovascular_disease.rb
- lib/modules/metabolic_syndrome.rb
- lib/records/exporter.rb
- lib/records/lookup.rb
- lib/tasks/tasks.rake
- lib/world/sequential.rb
- test/unit/exporter_test.rb
- test/unit/generic/appendicitis_test.rb
Exported files now contain only the past _ years (configurable) plus old data that is still relevant (active conditions, medications, careplans). Procedures are not kept if old but if they have permanent effects they should add a "History of xyz" condition, a few of which are introduced here. 
Also adds configurable options for exported file formats (fhir, ccda, html)
> Filter export to past _ years

- lib/modules/immunizations.rb
- lib/records/lookup.rb
- test/unit/immunizations_test.rb
It doesn't make sense to provide a patient with a vaccine before that vaccine was actually historically available. For example, the HPV vaccine should not be administered before 2006.
Adding logic for this makes the calculation for when to administer a vaccine more complex.
Additional tests help make sure that this more complex logic is providing reasonable results.
> Add support for historical availibility of vaccines

- lib/modules/lifecycle.rb
- lib/records/lookup.rb
Although height and weight are written out as FHIR observations, it is easier
for eCQM calculation if it the BMI is explicitly written out in the record.
> Explicitly record BMI

- config/synthea.yml
- lib/world/sequential.rb
Currently the multithreading uses 1 thread per city which loops over all the people to generate. This is a significant speedup over single-threading but loses its effectiveness over time when generating large cities.
Consider Suffolk County, where Boston has 600k people and the 2nd most populous city is Revere with 50k people. So once all the people in the smaller cities have been generated, the remaining 500k+ people in Boston will be generated on a single thread and the throughput drops significantly.
The new model uses 1 thread per city and then posts the work of generating people onto another thread pool, so that no matter how many cities are being processed at a time, it should always be generating multiple people at the same time.
> new multithreading model for sequential

- lib/generic/context.rb
- lib/generic/states.rb
- test/unit/generic_context_test.rb
- test/unit/generic_states_test.rb
When a generic module transitions from a state directly to itself, (ex, General Population in the Opioids model) that state is stored in the history during the patient's entire life, which adds up quickly.
This changes the GMF context & states so that if the new state to transition to is the same as the current one, it just stays in the current state and shifts the dates. Because the GMF will transition through states continuously until it hits a guard or delay, this change is likely to only apply to delays. 
A new date field is added to the State class, `start_time` which now represents the most recent time the state was called. `entered` now refers to the first time the state was called and is primarily for logging.
> condense history when a GMF state transitions to itself

- lib/generic/logic.rb
- lib/generic/modules/opioid_addiction.json
- lib/generic/states.rb
- test/fixtures/generic/condition_onset.json
- test/fixtures/generic/logic.json
- test/fixtures/generic/medication_end.json
- test/fixtures/generic/medication_order.json
- test/fixtures/generic/procedure.json
- test/fixtures/generic/set_attribute.json
- test/unit/generic_logic_test.rb
- test/unit/generic_states_test.rb
Adds a generic module for Injuries, and supporting framework changes.  The Injuries model allows patients to be prescribed opioids in certain cases, so in those cases we want the Opioids model to be aware of that. This is accomplished using "Attributes" which are just key/value pairs stored on the patient entity. An Attribute may be a Medication/Procedure/Condition, or an arbitrary string.
For the wiki:
* **assign_to_attribute**: The name of the attribute this [medication/condition/procedure/etc] should be referred to by. Attributes allow multiple to store, reference, and share medications, conditions, procedures, etc, as well as as arbitrary strings.
(remove "future considerations" from MedicationOrder")
The `SetAttribute` state type indicates a point in the module that sets a specified …
> Injuries Module, Attributes in GMF, Date logic, and MedicationEnd state

- lib/generic/logic.rb
- lib/generic/states.rb
- test/fixtures/generic/logic.json
- test/fixtures/generic/symptom.json
- test/unit/generic_logic_test.rb
- test/unit/generic_states_test.rb
Adds a new state type to add a Symptom to a patient, and logic based on Symptoms and prior states.
Symptoms use the existing Symptom API.  PriorState logic checks if a specific state is in the module's state history.
For the wiki:
(state)
The `Symptom` state type adds or updates a patient's symptom. Synthea tracks symptoms in order to drive a patient's encounters, on a scale of 1-100. A symptom may be tracked for multiple conditions, in these cases only the highest value is considered. See also the Symptom logic. (link here)
**Supported Properties**
* **type**: must be "Symptom" _(required)_
* **symptom**: the name of the symptom being tracked _(required)_
* **cause**: the underlying cause of the symptom. Defaults to the name of the module if not set. _(optional)_
* **exact**: an exact …
> adds Symptom state and symptom + priorState logic to GMF

- lib/records/fhir.rb
Minor change that makes sure that exported FHIR Conditions have a clinicalStatus
of active.
> Set FHIR Condition status to active

- lib/generic/modules/dementia.json
- lib/generic/states.rb
- test/fixtures/generic/observation.json
- test/unit/generic_states_test.rb
Adds a generic module for Alzheimer's, and a new Observation state for the GMF. (Eventually I would also like to add an Observation logical condition.) 
For the wiki:
The `Observation` state type indicates a point in the module where an observation is recorded. Observations include clinical findings, vital signs, lab tests, etc.
If the Observation state's `target_encounter` is set to the name of a future encounter, then the observation will be recorded when that future encounter occurs.  If the `target_encounter` is set to the name of a previous encounter, then the observation will only be recorded if the Observation start time is the same as the encounter's start time.  See the Encounter section above for more details.
**Supported Properties**
* **type**: must be "Observation" …
> alzheimer's module, plus observation state for GMF

- Gemfile.lock
- README.md
- config/synthea.yml
- lib/modules/module.rb
- lib/synthea.rb
- lib/tasks/graphviz.rb
- lib/tasks/tasks.rake
- synthea.gemspec
Migrates synthea_graphviz into synthea proper as a rake task. Graphviz is required to run the new `graphviz` rake task, but not for any other tasks, i.e. `generate` and `sequential` still work without graphviz installed
> adds graphviz graph generation as a rake task

- lib/entity/entity.rb
- lib/generic/logic.rb
- lib/generic/modules/lung_cancer.json
- lib/generic/states.rb
- lib/modules/cardiovascular_disease.rb
- lib/modules/encounters.rb
- lib/modules/generic.rb
- lib/modules/lifecycle.rb
- lib/modules/metabolic_syndrome.rb
- lib/records/ccda.rb
- lib/records/fhir.rb
- lib/world/population.rb
- lib/world/sequential.rb
- test/fixtures/generic/death_life_expectancy.json
- test/unit/exporter_test.rb
- test/unit/fhir_test.rb
- test/unit/generic/appendicitis_test.rb
- test/unit/generic_context_test.rb
- test/unit/generic_logic_test.rb
- test/unit/generic_states_test.rb
This pull request adds lung cancer to the list of disease's simulated.
I made a number of associated changes, including 
- Altering Procedures so they reference the associated Condition correctly for both generic modules and the original Ruby modules.
- Checking attributes in generic modules will check both strings (e.g. `'foo'`) and symbols (e.g. `:foo`)
- Replaced the `:is_alive` attribute with a more intelligent `alive?(time = nil)` method, so you can see if a patient is alive at a given time. Time `nil` is interpreted as "there has not been a death event in the past or in the future."
- Death state allows future deaths. For example, "you have X months to live given stage IV lung cancer." The patient may continue to receive chemotherapy and radiation treatments in the meantime... but …
> Lung cancer

- lib/generic/states.rb
- lib/tasks/graphviz.rb
- test/fixtures/generic/condition_end.json
- test/unit/generic_states_test.rb
- test/unit/graphviz_test.rb
Adds a ConditionEnd state to end conditions, basically identical to the MedicationEnd state in that it can end conditions based on codes, the name of a previous state, or as referenced by an attribute.
Also includes some graphviz changes so it's easier to unit test. The new graphviz test should fail if we add a new state type or condition type somewhere but forget to update graphviz. The test case should not depend on graphviz being installed.
For the Wiki:
The `ConditionEnd` state type indicates a point in the module where a currently active condition should be ended. (ex., if the patient has been cured of a disease) The `ConditionEnd` state supports three ways of specifying the condition to end:
1. By `codes[]`, specifying the code system, code, and display name of the condition to end, …
> Condition end

- lib/generic/logic.rb
- lib/tasks/graphviz.rb
- test/fixtures/generic/logic.json
- test/unit/generic_logic_test.rb
Adds logic based on Observations (compare the most recent observation of a certain type against a given value) and Conditions (check if a given condition is active)
for the wiki:
The `Observation` condition type tests the most recent observation of a given type against a given value. 
**Implementation Warnings**
* Synthea does not support conversion between arbitrary units, so all observations of a given type are expected to be made in the same units. 
* The given observation must have been recorded prior to performing this logical check, unless the `operator` is `is nil` or `is not nil`. Otherwise, the GMF will raise an exception that the observation value cannot be compared as there has been no observation made.
**Supported Properties**
* **condition_type**: must be "Observation" …
> Observation + condition logic

- config/synthea.yml
- lib/records/exporter.rb
- test/unit/exporter_test.rb
Changes the default output folder structure from /[type]/[city name]/[first 2 of guid]/ to /[type]/[first 2 of guid]/[first 3 of guid]/ in order to sync up better with syntheticmass bulk loader.  Folders per city is still available as a config setting.
> new default output folder structure

- lib/generic/modules/asthma.json
This module models a basic path for chronic asthma. Some things that are not included in this initial version:
* Increased likelihood of asthma from smoking or obesity
* Death from asthma (this is VERY unlikely, but possible)
* Allergy or exercise induced asthma (as-is, the cause of the occasional asthma attack is not documented, they just kind of happen)
* Additional asthma medications (beyond the standard maintenance and emergency inhalers there are also long-term steroids and nebulizers)
The granularity of the time step for asthma attacks is 6 months. Given this distribution patients could have between 0 and 2 asthma attacks per year. Most of the statistics for this module came from the CDC or the American Academy of Allergy Asthma and Immunology (AAAAI).
> Added Asthma Module

- lib/generic/modules/dementia.json
- lib/generic/modules/lung_cancer.json
- lib/generic/modules/opioid_addiction.json
- lib/generic/states.rb
- lib/modules/cardiovascular_disease.rb
- lib/modules/lifecycle.rb
- lib/modules/metabolic_syndrome.rb
- lib/records/ccda.rb
- lib/records/fhir.rb
- lib/records/lookup.rb
- lib/world/sequential.rb
- test/fixtures/generic/death_reason.json
- test/unit/generic_states_test.rb
Adds a "Death Certificate" with "Cause of Death" to patient records in FHIR when a cause of death is known. Cause of death may be specified in `Death` state in GMF.  Updates all modules to specify a reason for death.
One note: In the case of a Death state with a specified amount of time to live, the death certificate encounter + observation are added to the patient with future dates. It's theoretically possible that the patient could "die again" of something else before reaching those future dates. I'm thinking about how to fix that & open to suggestions.
> add cause of death to patient record

- lib/world/population.rb
**Warning** - This PR makes the assumption that the synthea code, in particular `Synthea::Rules.apply` is thread safe.
This PR allows the simulation to parallelize some of it's execution when running under JRuby. The modifications first check to see what platform the code is running on. If synthea is running in plain old ruby, this should in no way modify the behavior.
When JRuby is detected, the code will use java [Executors](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/Executor.html) to parallelize the logic. When synthea runs, it starts at a configured date, and then applies rules to all patients in the simulation (ignoring logic for births at the moment). It then advances the time and applies rules to all patients again. When running in plain old ruby, …
> Run simulation in parallel using JRuby

- lib/generic/states.rb
- test/unit/generic/appendicitis_test.rb
- test/unit/generic_states_test.rb
Modifies the underlying logic of time-based ranges so that they allow for intermediate values.
Ex. previously a range with units: years,  low: 1,  and high: 4 would always result in a delay of exactly 1, 2, 3, or 4 years. This change results in the ability for intermediate values.
This basically converts `rand(1..4).years` to `rand(1.years..4.years)`
> improve ranges to allow for intermediate values

- lib/records/exporter.rb
- test/unit/exporter_test.rb
Keeps the cause of death fields in exported patient records, regardless of the filter settings and how long ago the patient died.
> don't filter cause of death

- lib/records/fhir.rb
- test/unit/fhir_test.rb
This changes our WKT geospatial extension to use the existing extension defined in FHIR:
http://hl7.org/fhir/2016Sep/extension-geolocation.html
This change will effect downstream systems that rely on our geospatial coordinates, so should be merged in coordination with changes there.
> Fix geospatial extension to use existing extension on Address.

- lib/generic/context.rb
- test/unit/generic/appendicitis_test.rb
- test/unit/generic_states_test.rb
Upon review of some of our transition %s, I discovered that the raw %s were consistent with the defined probabilities, but the overall #s didn't make sense. 
For example, given a module with a 1 year Delay state, a patient should only be able to transition away from that state once per year at most. If a patient were 14 years old, the module should have transitioned from that Delay state 14 times. (Maybe 13-15 but still, in the range of 14.) I observed this patient had 23 transitions away from the state. What was happening is that it was exiting the Delay state, transitioning back to itself, rewinding history, and then the "new" state still had the same enter & exit time so was just immediately exiting and transitioning again. Counting the total # of transitions resulted in %s that …
> fix transition %s by reworking state-loop logic

- lib/entity/entity.rb
- lib/generic/context.rb
- lib/generic/logic.rb
- lib/generic/modules/bronchitis.json
- lib/generic/modules/sinusitis.json
- lib/generic/modules/sore_throat.json
- lib/tasks/graphviz.rb
- test/fixtures/generic/logic.json
- test/unit/generic_logic_test.rb
Adds new generic modules for some of the most common respiratory diseases, for which people are likely to visit their PCP.
Specifically, Bronchitis (Acute only), Sore Throat (Viral or Strep), and Sinusitis (Acute Viral, Acute Bacterial, and Chronic)
Adds 2 new logical conditions: "At Least" and "At Most". These are grouping conditions that return true based on the number of sub-conditions that return true.
Also includes another minor framework change - complex transitions now allow for a direct transition instead of always requiring a distribution.
**For the wiki** : 
The `At Least` condition type tests that a minimum number of conditions from set of sub-conditions are true.  If the _minimum_ number or more sub-conditions are true, it will return `true`, but if less than the minimum are …
> Respiratory diseases

- lib/records/ccda.rb
- lib/records/exporter.rb
- lib/records/fhir.rb
Updated FHIR exporter to handle the rare case when a patient's death date exists as an event but still occurs in the future (the patient hasn't actually died yet). This is typically seen for patients with lung cancer and is a rare occurence (1-3 in 10k records). Also added the deceasedBoolean field to the FHIR records that are exported to make it easier to query FHIR for living or deceased patients using the Patient?deceased=true/false query.
> Updated deceased datetime in FHIR exporter

- lib/generic/modules/opioid_addiction.json
The prevalence of opioid addicts is now realistic - about 1% of the population. The updated injuries module now drives about 75% of the opioid prescriptions. The remainder are still generated by the opioids module. In general I reduced the incidence of misuse and changed the time scale of the module to 1-week steps instead of 1-day. I adjusted the relevant probabilities accordingly.
The updated graphviz with new probabilities and time step:
> Fixed the Opioid Crisis

- lib/tasks/graphviz.rb
Added a list of Activities prescribed by the care plan to the CarePlanStart states generated by graphviz.
> Added Activities to CarePlanStart States in Graphviz

- lib/generic/logic.rb
- lib/generic/modules/injuries.json
- lib/generic/modules/self_harm.json
- lib/tasks/graphviz.rb
- test/fixtures/generic/logic.json
- test/unit/generic_logic_test.rb
1. Added a new module to model suicides and attempted suicides.
2. Added a new condition type:
```json
{
"condition_type": "Race",
"race": "Hispanic"
}
```
Returns `true` if the patient's race is "Hispanic", else `false`.
3. Removed the `fatal_injury` attribute from the injuries module (for gunshot injuries) that was originally intended to support suicides by firearm.
I ran a test of 1,000 patients that yielded reasonable and expected results. However, if we find that gunshot wounds are too frequent at a larger scale we may want to reduce the number of gunshot injuries in the injuries module to compensate for the additional firearm deaths from self harm.
The graphviz:
> Added Self Harm Module

- config/synthea.yml
- lib/world/sequential.rb
Adds some new features to help with identifying and debugging issues in sequential generation.
1. Adds timestamp to logs, ex `[2016-11-28 13:55:04] Boston 26/50: Roob872, Emilia103. White American. 8 y/o M 48 lbs. --`
2. Adds intermittent reports on the status of the queue, if enabled, ex `[2016-11-28 13:52:42] Generate Workers -- Queue Length: 9, Workers (Active/Max): 6/6, Total Completed: 35`
3. Adds exception handling to thread pool calls
> debug features

- lib/generic/modules/allergic_rhinitis.json
- lib/generic/modules/appendicitis.json
- lib/generic/modules/asthma.json
- lib/generic/modules/bronchitis.json
- lib/generic/modules/copd.json
- lib/generic/modules/dementia.json
- lib/generic/modules/ear_infections.json
- lib/generic/modules/lung_cancer.json
- lib/generic/modules/opioid_addiction.json
- lib/generic/modules/pregnancy.json
- lib/generic/modules/sinusitis.json
- lib/generic/modules/sore_throat.json
- lib/generic/modules/urinary_tract_infections.json
- lib/generic/states.rb
- lib/modules/encounters.rb
- lib/records/ccda.rb
- lib/records/fhir.rb
- lib/records/record.rb
- test/fixtures/generic/encounter.json
- test/unit/generic/appendicitis_test.rb
- test/unit/generic_context_test.rb
- test/unit/generic_states_test.rb
Adds a "reason" to the encounter state in GMF, and updates existing modules with that reason.
Reason may be either a previous ConditionOnset state name or an attribute set by a ConditionOnset.
> Encounter reason

- lib/generic/states.rb
- lib/tasks/graphviz.rb
- test/fixtures/generic/counter.json
- test/unit/generic_states_test.rb
New Counter state for GMF, allows for incrementing or decrementing an attribute. The attribute value is initialized to 0 if not previously set.
for the wiki:
The `Counter` state type indicates a point in the module that increments or decrements a specified value on the patient entity. In essence, this state counts the number of times it is processed. Note: The attribute is initialized with a default value of 0 if not previously set.
**Supported Properties**
* **type**: must be "Counter" _(required)_
* **action**: whether this counter will _increment_ or _decrement_ the attribute's value _(required)_
* **attribute**: the name of the Attribute for which the value will be incremented or decremented. _(required)_
**Example**
The following is an example of a Counter that decreases the value in …
> counter state

- lib/generic/modules/colorectal_cancer.json
- lib/world/sequential.rb
This module is segmented into two distinct sections:
1. Incidence, diagnosis, and routine colonoscopies
2. Treatment, remission, and death
I ran a test of 100 patients with logging enabled and saw good variety in the results. Various stages of the cancer were hit equally well. Some patients successfully reached remission, and some patients had recurrent cancer that eventually lead to death.
I also ran a batch of 500 patients to check prevalence and incidence. About 2.2% of patients were living with colorectal cancer. Of the 558 generated 5.1% (29) died of colorectal cancer, which also aligns with the expected stats. About the same number of patients die from colorectal cancer as lung cancer, but you also find a reasonable portion of patients that don't die from colorectal cancer and go on …
> Colorectal cancer

- lib/generic/modules/allergic_rhinitis.json
- lib/generic/modules/pregnancy.json
Added `Counter` states to `allergic_rhinitis` and `pregnancy` modules to improve and simplify these modules. Ran a test of 100 patients and checked the log to confirm that things still behaved as expected. Also added 1 extra pass through the pregnancy module to give a slightly higher incidence of pregnancy/birth.
> Use the New Counter State

- lib/generic/modules/injuries.json
- lib/generic/states.rb
Adds the missing `target_encounter` from the injuries model, and adds the metadata that should have caught the missing field in the first place.
> Adds missing target_encounter + metadata, fixes #103

- lib/generic/modules/colorectal_cancer.json
Fixes a potential exception that could be thrown in the Colorectal Cancer module, when trying to end a condition that wasn't active. In this case, the `Followup_Colonoscopy_Procedure` state checks whether the `Recurrent_Colorectal_Adenoma` state was previously hit, and if so ends the condition that was onset in `Recurrent_Colorectal_Adenoma`. There is a possible sequence where the `Recurrent_Colorectal_Adenoma` state was previously hit but its condition was later ended, so trying to end the condition again will fail.
This PR changes the condition from a PriorState to an Active Condition with the codes from the referenced state, which prevents this double-end of a condition and better represents the intent of the check anyway.
> Fix for exception in Colorectal Cancer module

- config/synthea.yml
- lib/generic/modules/homelessness.json
- lib/generic/states.rb
- lib/modules/lifecycle.rb
- lib/tasks/graphviz.rb
- lib/world/demographics.rb
Adds a module that represents people experiencing homelessness. Targets around 0.18% of the population being homeless at any one time. People cycle in and out of homelessness at roughly accurate rates. Currently the fact that a person is homeless is only recorded as an attribute, the person's residential address is unchanged. People that are homeless may visit shelters, at which point they are given a form and observations are taken regarding certain risk factors. These observations are intentionally simplified - eventually these risk factors should be modeled and represented directly within the patient record itself.
Also includes a couple minor tweaks: 1 - adds the ability to record an observation with the value of an attribute, and 2 - adds a config setting to disable generating …
> Homelessness Module

- lib/generic/modules/injuries.json
- lib/generic/states.rb
- test/unit/generic_states_test.rb
All injury care plans are now guaranteed to be concurrent with their `target_encounter`. Fixes [Issue #118](https://github.com/synthetichealth/synthea/issues/118).
> Fixed Injury Care Plans

- lib/generic/modules/gout.json
- lib/generic/modules/lupus.json
Fixes #123 & #124 .  A previous change added exceptions when a procedure, careplan, medication, etc was not concurrent with the target encounter. This fixes 2 instances where an exception could be thrown.
In Gout - just changed the order of the Encounter and CarePlanStart states. In Lupus - added a second MedicationOrder state instead of looping back to the original MedicationOrder state. The MedicationEnd now looks at an attribute instead of the MedicationOrder state name.
New Gout Module:
New Lupus Module:
> Target_encounter Sequence fixes

- lib/generic/modules/asthma.json
- lib/generic/modules/ear_infections.json
- lib/modules/cardiovascular_disease.rb
- lib/modules/metabolic_syndrome.rb
- lib/records/lookup.rb
Some fixes for realism based on physician feedback. Includes:
- Prescribe sublingual nitroglycerin instead of injected
- Certain medications are filtered by year first available (still a work in progress to do this across all modules though)
- Asthma emergency inhaler should be an actual inhaler, limited by date first available
- HB1AC recorded with only 1 decimal place
- High values of EGFR are recorded as >60
> Realism fixes

- lib/generic/components.rb
- lib/generic/states.rb
- lib/records/ccda.rb
- lib/records/fhir.rb
- lib/records/lookup.rb
- lib/records/record.rb
- test/fixtures/generic/medication_order.json
- test/unit/fhir_test.rb
- test/unit/generic_states_test.rb
I added additional, optional properties to the `MedicationOrder` state that capture dosage information. I updated the FHIR exporter but did not touch the CCDA export (yet). Where can I find documentation on the fields/values accepted by the HDS resources like `Medication`? I updated the tests for the `MedicationOrder` state and added an additional FHIR validation test in the event that prescription information is included.
For the wiki:
***
The `MedicationOrder` state type indicates a point in the module where a medication should be prescribed.  The MedicationOrder state must come after the `target_encounter` Encounter state in the module, but must have the same start time as that Encounter; otherwise it will not be recorded in the patient's record.  See the Encounter section above for …
> Medication order details

- .dockerignore
- config/mongoid.yml
- config/synthea.yml
- docker/mongoid.yml
- docker/ruby/Dockerfile
- docker/ruby/docker-compose.yml
- lib/records/exporter.rb
- lib/tasks/tasks.rake
Dockerized Synthea using Matz's standard C Ruby. jRuby to follow in a separate PR. See the "Docker" page of the Synthea Wiki for more information and instructions on how to run Synthea in Docker.
> Dockerized Synthea

- lib/entity/entity.rb
- lib/generic/logic.rb
- lib/generic/modules/wellness_encounters.json
- lib/generic/states.rb
- lib/modules/cardiovascular_disease.rb
- lib/modules/encounters.rb
- lib/modules/lifecycle.rb
- lib/modules/metabolic_syndrome.rb
- lib/tasks/graphviz.rb
- lib/world/sequential.rb
- test/fixtures/generic/logic.json
- test/fixtures/generic/vitalsign_observation.json
- test/unit/generic_logic_test.rb
- test/unit/generic_modules_test.rb
- test/unit/generic_states_test.rb
Adds Vital Signs to the Generic Module Framework. Vital Sign states can be used to store information which can then be captured by Observations or drive conditional logic. Vital Signs represent the physical state of the patient, in contrast to Observations which are the recording of that physical state. For instance, height and weight are physical properties of a person which can be observed. Note that not all observations are direct recording of physical properties, so Observations can still specify a range or exact value. For instance, MMSE (Mini–Mental State Examination, a diagnostic evaluation used for tracking dementia, ex Alzheimer's) is not a physical quantity but a score representing an evaluation. There may not be a clear distinction between the Vital Sign and Observation in all …
> GMF Vital Signs

- .gitignore
- lib/tasks/concepts.rb
- lib/tasks/tasks.rake
This adds a rake task to inventory all the terminology codes and concepts used within Synthea and output them to a comma-separated values (csv) file.
The task inventories all the built-in lookup tables as well as all the codes used within generic module states.
The concept file is used solely for reporting and analysis purposes and does not alter the simulation whatsoever.
> Add rake task for concept inventory.

- config/synthea.yml
- lib/records/csv.rb
- lib/records/exporter.rb
- lib/records/text.rb
- lib/tasks/tasks.rake
Exports Patients, Encounters, Observations, and so forth into separate CSV files. Each row in the files is linked to a patient and encounter when appropriate. The data for all patients is contained in one set of files. For example, all patients are contained in a single `output/csv/patients.csv` file -- one per row. The same pattern holds for the other resource types.
This pull request also fixes the allergies in the `text` exporter.
> Add CSV exporter to Synthea.

- .gitignore
- lib/generic/modules/allergic_rhinitis.json
- lib/generic/modules/allergies.json
- lib/generic/modules/bronchitis.json
- lib/generic/modules/dermatitis.json
- lib/generic/modules/ear_infections.json
- lib/generic/modules/injuries.json
- lib/generic/modules/medications/ear_infection_antibiotic.json
- lib/generic/modules/medications/moderate_opioid_pain_reliever.json
- lib/generic/modules/medications/otc_antihistamine.json
- lib/generic/modules/medications/otc_pain_reliever.json
- lib/generic/modules/medications/strong_opioid_pain_reliever.json
- lib/generic/modules/total_joint_replacement.json
- lib/tasks/graphviz.rb
These were the O.G. submodules that I finally got around to compiling and integrating with our existing modules. I created several different submodules that prescribe commonly used medications across several main modules:
* OTC Pain Relievers
* OTC Antihistamines
* Moderate Opioid Pain Relievers (post surgery, or for injuries)
* Strong Opioid Pain Reliever (for chronic pain, e.g. cancer)
* Ear Infection Antibiotic (also used for bacterial infections due to burns/open wounds)
The Strong Opioid Pain Reliever module isn't actually used yet - I expected the cancer modules to prescribe a strong opioid for chronic pain but neither one does. I will go back in and add a strong pain reliever for the late stages of cancer if my approach so far tickles your fancy.
I made updates to some of our …
> Medication Submodules

- lib/generic/components.rb
- lib/generic/modules/metabolic_syndrome_care.json
- lib/generic/states.rb
- lib/modules/cardiovascular_disease.rb
- lib/records/fhir.rb
- lib/records/record.rb
- lib/tasks/graphviz.rb
- test/unit/exporter_test.rb
- test/unit/fhir_test.rb
- test/unit/generic_logic_test.rb
- test/unit/generic_states_test.rb
- test/unit/record_test.rb
Introduces Goals within CarePlans. A goal can be defined by an observation with a target value (ex. "get HbA1c below 7.0"), a LOINC code, or free text (ex "Address patient knowledge deficit on diabetic self-care").   
Adds specific goals to Diabetes care plan, based on sample care plans at https://github.com/clinical-cloud/sample-careplans .
Note that in this implementation, goals are set at CarePlanStart and are active until the CarePlanEnd state (if any).  In the future I expect we will want to make these more dynamic - ie, allow different people to have different sets of targeted goals, do different logic based on what goals are active, etc.
> Add Care Goals to CarePlans

- lib/generic/states.rb
- lib/modules/cardiovascular_disease.rb
- test/fixtures/generic/death_reason.json
- test/unit/generic_states_test.rb
When a Death state contains a code, that code should be added to the condition LOOKUP so it's available later in the fhir exporter. Tweaks the ConditionOnset and AllergyOnset state so their codes are added to LOOKUP when the state is processed, not when the condition is diagnosed. 
Also fixed another small bug where the cardiovascular disease careplan reasons were "double-wrapped" in arrays.
>  Add cause of death code to condition lookup, fixes #141 

- test/unit/generic_context_test.rb
- test/unit/generic_states_test.rb
- test/unit/record_test.rb
fixes the warnings in the test suite about "Use assert_nil if expecting nil from [...] This will fail in MT6."
> fix minitest warnings, resolves #155

- lib/generic/modules/injuries.json
- lib/generic/modules/osteoporosis.json
Based on feedback that fractures should trigger an osteoporosis workup in the elderly:
- Adds a simple module that onsets Osteoporosis at realistic prevalences by age
- Adds a section in the Injuries module following broken bones that can result in a diagnosis of osteoporosis.
Injuries snippet:
Osteoporosis module:
> Add Osteoporosis module

- README.md
- lib/tasks/tasks.rake
Renames the `generate` task to `population` and renames the `sequential` task to `generate`. We really only use the sequential generation, so it makes more sense for that to be "generate". Sequential can still be called from the `sequential` task, just in case anyone had any scripts using that.
Updated the README with the new name. I didn't mention the `population` task since it's temporarily deprecated.
Closes #179
> Rename generation tasks, resolves #179

- config/synthea.yml
- lib/world/sequential.rb
- resources/prevalence_template.csv
Adds tracking of prevalence data for all combinations of age/race/gender/precondition. 
This implementation uses a multi-level nested hash to track the various combinations. While ideally we would use a database to keep patients in, and then run queries to get whatever stats we want, that would involve a major refactoring of the application.
This approach uses a template in the /resources/ directory: 
[prevalence_template.csv.txt](https://github.com/synthetichealth/synthea/files/916489/prevalence_template.csv.txt)
Which is then populated with statistics following a run:
[targeted_prevalences.csv.txt](https://github.com/synthetichealth/synthea/files/916492/targeted_prevalences.csv.txt)
Also exported is a csv with prevalence for all conditions and medications for living patients. …
> Detailed & configurable prevalence data for all conditions+medications

- config/synthea.yml
- lib/records/fhir.rb
Currently the patients do not have an MRN identifier. While this is valid, the issue is that there are many existing FHIR applications that (incorrectly) assume that all the patients do have MRN.
Since we are trying to make the transition to STU3 as smooth as possible, I have added an MRN to the patient identifiers which will use the  uuid as it's value. There is also an option to turn this off in the config file.
> Add MRN to patients

- lib/generic/modules/contraceptives.json
- Changed Route_To_Guard from a series of guards to an annual delay.
This resamples contraceptive use more frequently and causes different women
to become pregnant, distributing the babies more evenly across the
population.
- Changed Using_Sterilization to sample only at the 25 & 35 year marks
where the sampling used to occur with the previous Route_To_Guards. This
eliminates resampling for sterilization after pregnancy that was
decreasing the fertile female population unrealistically.
> Changes to contraception module to reduce sterilization after pregnancy

- lib/generic/modules/colorectal_cancer.json
Add delay to the beginning of the colorectal cancer module to account for delayed onset of smoking history.
> Colorectal Cancer Module Change

- .travis.yml
Travis is migrating from their default build system being Ubuntu 12.04 to 14.04. 14.04 doesn't have a precompiled version of ruby 2.1.0 so builds are failing right now. 
```
$ rvm use 2.1.0 --install --binary --fuzzy
ruby-2.1.0 is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.1.0 do rvm gemset create ' first, or append '--create'.
The command "rvm use 2.1.0 --install --binary --fuzzy" failed and exited with 2 during .
```
(see https://travis-ci.org/synthetichealth/synthea/jobs/257874893 )
The simplest fix is to bump the ruby version that travis builds with to 2.1.10 which is available as a precompiled ruby on …
> update version built on travis

- lib/tasks/graphviz.rb
Adds named transition probability support to the graphviz rake task. While named transitions are currently only supported in the java version of synthea, we'll need some way to visualize modules with these named transitions until the java version supports graphviz.
Sample: (see branch at top of image)
> graphviz handles named transition probabilities

- lib/generic/states.rb
Due to a bug somewhere, there's an issue where `rand()` called with a `Range` of `ActiveSupport::Duration`s occasionally returns a `Float` instead of an `ActiveSupport::Duration` as would be expected. This is a hack to check for that scenario and create a Duration from the Float so we can use it as expected.
> Workaround for issue #222

- .rubocop.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- test/unit/generic_logic_test.rb
- test/unit/metadata_test.rb
JRuby build on Travis is failing now due to unit test failures. I have no idea why because those unit tests and associated code haven't changed in a year and the vanilla Ruby builds work correctly.
I tried the latest version of JRuby on my local machine and all the unit tests pass without problem, so I'm updating the travis file to see if this will resolve the issue.
> Update version of jruby used by travis.

- build.gradle
Changes the version.txt generation task so that it always runs before compiling java code. Currently it is set to run before the "assemble" task, but the assemble task is not always run before running the code.  
In other words, someone cloning synthea today and calling the run_synthea script right away will see the error:
```
java.lang.IllegalArgumentException: resource version.txt not found.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:204)
at com.google.common.io.Resources.getResource(Resources.java:197)
at org.mitre.synthea.helpers.Utilities.readResource(Utilities.java:212)
at org.mitre.synthea.helpers.Utilities.getSyntheaVersion(Utilities.java:194)
at org.mitre.synthea.helpers.Utilities.<clinit>(Utilities.java:187)
at …
```
> Version.txt fix

- build.gradle
- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/modules/GrowthChartTest.java
Changes the growth from looking up bucket values to calculating the growth according to the CDC formulas. This will give more varied growth to the population.
> Fix growth calculations according to CDC growth chart formulas.

- build.gradle
Synthea doesn't work out of the box on Java 9, since Java 9 marked certain XML libraries as "deprecated" and they are no longer included by default. The recommended fix for maximum compatibility is to manually include these libraries as they are likely to be removed entirely in Java 10.
More info:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/48136912#48136912
Also adds a couple more libraries to get rid of the following error lines at startup, while I was modifying build.gradle anyway:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
More info: …
> Fix Java 9 compatibility

- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/modules/Immunizations.java
- src/main/java/org/mitre/synthea/world/concepts/Costs.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
This pull request fixes some oddities in Claims representations in FHIR and adds costs to CSV export.
The CSV costs are added directly into the encounters, immunizations, medications, and procedures csv tables. There is no separate claims table with aggregated costs.
The FHIR costs were also changed, as I noticed some weird things while looking at claims in general. Foremost is that now FHIR claims also include charges for immunizations. Second, is that DSTU2 claims were not linked to an Encounter... which doesn't make a whole lot of sense. The individual entries were also using example bindings, where it makes more sense to bind directly to the codes of the services provided (e.g. the procedure code).
> Claims Revisited

- src/main/java/org/mitre/synthea/helpers/Concepts.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/helpers/ConceptsTest.java
This reworks the `Concepts` class a little bit. Drops the use of `Table` to use `Map`:
```java
Map<Code,Set<String>> concepts;
```
This allows us to easily track which concepts appear in which modules. Most codes only appear in a single module, but some appear in many.
I also added `Comparable<Code>` to `Code` so that codes could be sorted alphabetically by system and then by code.
> Add modules to concepts list.

- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/ExportHelper.java
This is a possible fix for issue #283. As far as I can see there are no more types than text and decimal. I ran the tests without problems.
> issue #283 possible CSV export fix

- src/test/java/org/mitre/synthea/export/CSVExporterTest.java
This may be a Windows-only issue since I've never seen it on Travis, but I often (~50% of test runs) get the following exception in the test suite:
```
org.mitre.synthea.export.CSVExporterTest > testCSVExport FAILED
java.nio.charset.MalformedInputException: Input length = 1
at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
at java.io.InputStreamReader.read(InputStreamReader.java:184)
at java.io.BufferedReader.fill(BufferedReader.java:161)
at java.io.BufferedReader.readLine(BufferedReader.java:324)
at java.io.BufferedReader.readLine(BufferedReader.java:389)
at java.nio.file.Files.readAllLines(Files.java:3205)
at …
```
> Quick fix for exceptions on CSV Exporter Test

- src/main/java/org/mitre/synthea/helpers/RandomCollection.java
- src/test/java/org/mitre/synthea/helpers/RandomCollectionTest.java
This PR ignores the addition of entries in a RandomCollection that have zero weight.
A bug was causing zero weight entries to gain the probabilities of the last entered item.
> Fix random collection for zero-weight options and add unit tests.

- src/main/java/org/mitre/synthea/export/Exporter.java
- src/test/java/org/mitre/synthea/export/ExporterTest.java
Fixes a bug in the export filtering logic where encounters (and as such all associated conditions, medications, etc) were not being kept past the filter date. Issue was a flipped && and ||.
Also filters claim items if the corresponding item was removed from the record. I don't think this is the ideal approach, but it's quick and produces valid & internally consistent records. Open to suggestions on improvements.
> Fix encounter filtering bug

- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/export/HospitalDSTU2Exporter.java
- src/main/java/org/mitre/synthea/export/HospitalExporter.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRExporterTest.java
- src/test/java/org/mitre/synthea/export/HospitalDSTU2ExporterTest.java
- src/test/java/org/mitre/synthea/export/HospitalExporterTest.java
Allows users to create FHIR `transaction` Bundles instead of `collection` Bundles.
To enable, modify synthea.properties:
`exporter.fhir.transaction_bundle = false`
Change `false` to `true` and rerun with any FHIR exporter enabled.
> Fix #281 - Transaction Bundles.

- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/main/resources/templates/ccda/ccda.ftl
Fixes a bug that resulted in nearly every patient being assigned the same provider (in MA that's Shriners, because it's the last provider in the list for MA). Updates the minimum search distance every time it finds a provider within that distance, ensuring the closest provider is picked.
Also escapes "&" in a couple ccda fields - turns out some providers have these in their name or address.
> Fix provider distance check

- src/main/resources/gbd_disability_weights.json
- src/main/resources/modules/metabolic_syndrome_care.json
This PR adds additional metabolic syndrome codes.
I ran `./run_synthea -s 0 -p 10000` and got these results (filtering codes in the metabolic syndrome set and filtering out dead people):
DESCRIPTION | n | new
-- | -- | --
Body mass index 30+ - obesity (finding) | 3932 | :new:
Prediabetes | 2371
Body mass index 40+ - severely obese (finding) | 946 | :new:
Diabetes | 472
Hypertriglyceridemia (disorder) | 436 | :new:
Metabolic syndrome X (disorder) | 428 | :new:
Hyperglycemia (disorder) | 344 | :new:
Neuropathy due to type 2 diabetes mellitus (disorder) | 166
Diabetic renal disease (disorder) | 143
Diabetic retinopathy associated with type II diabetes mellitus (disorder) | 134
Nonproliferative diabetic retinopathy due to type 2 diabetes mellitus (disorder) | 85
Proliferative diabetic …
> Metabolic Codes

- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/world/geography/Demographics.java
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/engine/GeneratorTest.java
Currently the Generator will pick a target set of demographics when generating a person, but if the person dies before reaching the target age, it will re-pick demographics. This has the consequence of the population age being skewed low because people with a higher target age are more likely to die along the way.
This change picks demographics once and then re-uses those demographics for each attempt until it succeeds. This change means that those demographics are just stored in a HashMap, there's no Person object yet.
Also brings back a tweak from the Ruby version where if trying to generate a really old patient and failing multiple times, it will reduce the target age to between 85 & 90. Our top age bracket is 85+ so this shouldn't meaningfully affect the overall numbers, unless …
> Fix for bug in demographics selection

- src/main/java/org/mitre/synthea/export/CustomSqlReport.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/resources/custom_queries.sql
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/export/CustomSqlReportTest.java
Adds the ability to automatically run custom reports after a population is generated, using arbitrary SQL. Queries in the file src/main/resources/custom_queries.sql (configurable) will be run one at a time, and exported to CSV in output/reports. Lines starting with -- will be ignored, so this file includes a few sample queries to get started with.
This is not a "finished product" as it has some limitations but it is sufficiently usable that someone with an understanding of the DataStore data model could produce useful reports. After this is merged I plan to add a wiki page with an overview of the data model.
> Custom reports from arbitrary SQL

- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/test/java/org/mitre/synthea/world/agents/ProviderTest.java
This pull request fixes a bug when you try to customize providers. If you try to use alternative provider files, the system will break because it was looking for hardcoded filenames.
E.g. changing:
```properties
generate.providers.hospitals.default_file = providers/hospitals.csv
```
to:
```properties
generate.providers.hospitals.default_file = providers/uk_test.csv
```
Would cause no hospitals to offer services, because the code was looking for the string `"providers/hospitals.csv"`
Bonus commit: Changes filenames not to have whitespace, which causes issues with some other programs... for example, Unix command line utils.
> Provider bug fix

- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/export/HospitalDSTU2Exporter.java
- src/main/java/org/mitre/synthea/export/HospitalExporter.java
- src/main/resources/synthea.properties
This pull request makes country code an editable property for localization purposes.
Default:
```properties
generate.geography.country_code = US
```
Currently, this property is purely cosmetic for FHIR generated addresses. It has no other purposes, but in the future, we may use it for something more intelligent... for example, for switching between different country specific datasets.
> Make country code an editable property for localization.

- build.gradle
Updates the HAPI FHIR libraries in testCompile to 3.3.0.  The structures libraries are already at 3.3.0
> Update fhir resources libraries

- src/main/java/org/mitre/synthea/engine/Logic.java
- src/test/java/org/mitre/synthea/engine/LogicTest.java
Race comparisons are currently broken because the modules use capitalized strings (ex. "White") whereas the engine uses all lower-case (ex. "asian"). Rather than fix all the modules and the module builder, we can just use a case-insensitive match.
> Make race comparisons case-insensitive

- src/main/resources/modules/wellness_encounters.json
Removes the HbA1c test (`Lab_1_HA1C` and `Record_HA1C` states) from the wellness encounters module, because that's already taken care of in the metabolic syndrome care module. Also removes the numbers from the states (ie, the Lab_#_Xyz states to just Lab_Xyz) rather than renumbering.
Not sure why the diff shows so much added and changed, I guess the module builder moved things around when I renamed them.
Before & After - deleted section highlighted:
> Remove HbA1c test from wellness encounters, fixes #345

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
Makes 2 changes to Encounter.diagnosePastConditions:
1 - checks whether the current encounter state is the target encounter of an onset state before diagnosing it
2 - breaks out of the loop early if it finds a previous instance of the same state (which would have diagnosed anything prior to that)
> Update Encounter.diagnosePastConditions, fixes #351

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
Just introduced in a recent PR, the changes to Encounter.diagnosePastConditions broke diagnosing past conditions.
Note the comment at the beginning of the method:
`// reminder: history[0] is current state, history[size-1] is Initial`
So current state is an Encounter, which has the same name as itself, so it would always hit the `else` condition and break out before diagnosing anything.
Simplest fix is to just not break when you are not looking at the current state, ie when `!= this`. The unit test didn't catch it previously because it added the state to history after processing, which isn't how the modules actually work.
> Re-fix Encounter.diagnosePastConditions

- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/world/concepts/HealthRecordTest.java
Fixes DiagnosticReport to include the correct set of observations. Apparently this has been broken for a while... like 8 months. Blah.
> Fix diagnostic report including the correct number of observations.

- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/resources/modules/lung_cancer.json
- src/main/resources/modules/lung_cancer/lung_cancer_probabilities.json
Moves the logic that calculates probability of lung cancer from the java-based LifecycleModule to a new submodule. This is intended to be as close to a 1-1 translation of the java logic as possible, but only called once since the value is only read once.
New submodule:
(note the extra transition change in the lung_cancer module just fixes an unreachable state)
> Migrate lung cancer probability calculations to GMF

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/encounter_with_submodule.json
- src/test/resources/generic/submodules/admission.json
Fixes a bug where submodules did not have a current encounter, unless it was declared within the submodule. This now allows for submodules to add things to the current encounter, and even end the current encounter and start a new encounter (e.g. ADT).
Also, this PR now allows conditions to be diagnosed if the target_encounter is empty (previously allowed it correctly allowed `null` but not empty).
> Fix current encounter in submodules.

- src/main/java/org/mitre/synthea/export/TextExporter.java
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/export/TextExporterTest.java
For whatever reason Diagnostic Reports were missing from the text exporter. This PR adds them, using the same format as MultiObservations like blood pressure.
```
2013-12-21 : Lipid Panel
- Total Cholesterol                        178.0 mg/dL
- Triglycerides                            107.5 mg/dL
- Low Density Lipoprotein Cholesterol      96.9 mg/dL
- High Density Lipoprotein Cholesterol     59.7 mg/dL
```
Now all the clinical record entries are present in the exported text records. (I say clinical because Claims are not included.)
Samples:
Full -- [Son314_Leffler128_7765ccad-6f66-41b0-8ed7-b7cee4d1273b.txt](https://github.com/synthetichealth/synthea/files/2224072/Son314_Leffler128_7765ccad-6f66-41b0-8ed7-b7cee4d1273b.txt)
Per-encounter -- …
> Add diagnostic reports to text export

- src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java
- src/main/resources/costs/medications.csv
Previous ones were inactive.
Epinephrine changed to vial since that's what's used in hospitals, not
the Epipen form previously selected. Price adjusted accordingly.
Atlepase 100mg inj selected over 50mg based on the PI indicating the
most common doses; although smaller adults may still get the 50mg.
> Fix RxnCUIs for Atlepase and Epinephrine.

- src/main/resources/synthea.properties
Restore the default set of demographics, instead of the veteran demographics which have different age frequencies and are highly weighted towards males
> restore default demographics

- src/main/java/org/mitre/synthea/export/CSVExporter.java
The format of the costs in the encounter relation depends on the running system. Costs are formatted by a ',' in Germany (for example) instead of a '.' which leads to a "broken" CSV file. My suggestion is to set the locate to US.
> Fix for the CSVExporter 

- src/main/resources/modules/metabolic_syndrome_care.json
This fix changes the transition logic to take into account the hypertension attribute so children are not given low doses of hydroclorothiazide (sp).
> Fix #427 -- children with hypertension medication.

- src/main/java/org/mitre/synthea/export/FhirStu3.java
The issue this PR fixes is reference to a claim inside the same bundle given as claim id without resource type (i.e, "123" instead of "Claim/123"), which I think is an invalid reference.
The way I fixed it is by using Bundle.entry.fullUrl (similar to how other references are done).
> Fix Claim reference

- src/main/java/org/mitre/synthea/export/CDWExporter.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/ExportHelper.java
It was not possible to run
./gradlew build check test
without errors in Germany (for example), because numeric values were formatted with a ',' instead of a '.', which leads to wrong formatted csv files. I recently added an equal pull request which was merged, but i have overseen some formatting issues.
> CSVExporter and CDWExporter Format Issue Fix

- .travis.yml
- src/main/resources/modules/anemia/anemia_sub.json
- src/main/resources/modules/anemia___unknown_etiology.json
The following procedure came from Jay Walonoski's work:
Ran 10000 Patients with the addition of the Anemia modules.
1. Modify ./src/main/resources/synthea.properties:
```
generate.default_population = 10000
generate.database_type = file
```
2. Ran synthea 
`./run_synthea`
3. Open H2 database and connect to the database.mv.db file located at the root of the synthea directory.
4. SQL Query
```
select pop.race, pop.gender, pop.TOTAL, popa.ANEMIA, 
TRUNCATE((CAST(popa.ANEMIA as double) / CAST(pop.TOTAL as double)) * 100.0, 2) as PREVALENCE
from
(select race, gender, count(*) as TOTAL
from person
group by race, gender
order by gender, TOTAL desc) pop,
(select person.race, person.gender, count(*) as ANEMIA
from person, condition
where person.ID = condition.person_ID
and condition.code = …
```
> Add OSEHRA Anemia Module

- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/main/resources/geography/foreign_birthplace.json
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/world/geography/LocationTest.java
- src/test/resources/geography/foreign_birthplace.json
- src/test/resources/geography/foreign_birthplace_simple.json
- src/test/resources/geography/malformed_foreign_birthplace.json
This PR adds the enhancement when a patient is a non-native English speaker, that patient will have a foreign place of birth, #165 
How it works:
A reference file of ethnicities to cities should be created.  Format is:
{"ethnicity1": ["city1", "city2", ... "cityN"],
"ethnicity2": ["city1", "city2", ... "cityN"],
...
"ethnicityN": ["city1", "city2", ... "cityN"]}
File location can be declared in the synthea.properties file with the "generate.geography.foreign.birthplace.default_file" flag.
During the LifecycleModule, when a non-english first language is found instead of calling Location.randomCityName() we instead call Location.randomCityNameByEthnicity() which references the previously mentioned json file containing maps from ethnicities to cities.  Once the list of cities is accessed …
> Non native speakers 165

- build.gradle
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- Update the HAPI libraries to 3.7.0-SNAPSHOT to include the first normative release of FHIR R4.
- Update the FHIR R4 exporter to align with the normative version.
> FHIR Update

- build.gradle
Just wraps the `versionTxt` build task in a try-catch block and writes the exception message to the console if anything goes wrong, for example, if someone downloaded the repo using the download zip option instead of cloning it because they don't have git installed.  Git isn't required or used for any other aspect of synthea so it doesn't make sense to me to have it be a hard requirement. Fixes #462.
Sample error message (I changed the call from "git" to "badgit" here to intentionally trigger it):
```
λ .\run_synthea.bat
> Task :versionTxt
Warning: unable to create version.txt. Generated records will not indicate which version of Synthea was used to create them.
Cannot run program "badgit": CreateProcess error=2, The system cannot find the file specified
> Task :run
Loading …
```
> Log warning instead of crashing if git is not present, addresses #462

- src/main/java/org/mitre/synthea/export/Exporter.java
This was being caused by multiple threads written to the ndjson files simultaneously. Synchronization of the output method solved the problem.
> Fix #457 Truncated lines in ndjson files.

- src/main/java/org/mitre/synthea/export/CSVExporter.java
Fixes #443 by renaming `ID` headers in all exported CSV files to `Id`
> Fix for #443: renamed ID headers to Id in CSV export

- src/main/java/org/mitre/synthea/export/CSVExporter.java
An extra comma delimiter at the end of each record was being exported to the provider csv file.
> removed extra comma delimiter in provider csv exporter

- src/main/java/org/mitre/synthea/world/agents/Provider.java
Initial workaround for #483 until all providers coordinates are updated and verified. Updates the logic that selects a "closest" provider by keeping a list of providers at the current closest distance, and then at the end it chooses one randomly.
> Randomly choose a provider if there is more than one at a given location

- build.gradle
This upgrades the HAPI libraries from `3.7.0-SNAPSHOT` to `3.7.0`
> Update to HAPI 3.7.0.

- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
This pull request adds the ability to specify "SNOMED-CT" within the "system" field of a code within a MedicationOrder state definition.
With this change, the FHIR DSTU2, STU3 and R4 generators will now correctly output the SNOMED CT URI ("http://snomed.info/sct"), rather than ignoring the value in the module and defaulting to the RxNorm URI.
> Respect SNOMED-CT coded medication orders within FHIR exports

- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterR4.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterStu3.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/HospitalExporterR4.java
- src/main/java/org/mitre/synthea/export/HospitalExporterStu3.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- src/test/java/org/mitre/synthea/export/HospitalExporterTestR4.java
- src/test/java/org/mitre/synthea/export/HospitalExporterTestStu3.java
This PR introduces some fixes for the FHIR R4 exporter so that resources can be US Core compliant.
First, it introduces a new configuration property in `synthea.properties` which defaults to `false`
```properties
exporter.fhir.use_us_core_ig = false
```
Or, from the command line:
```
./run_synthea --exporter.fhir.use_us_core_ig true
```
Thanks to @Healthedata1
Custom extensions should be ignored by validator am checking in with GG
> Fixes for FHIR R4 so resources are US Core compliant.

- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/modules/HealthInsuranceModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/IProviderFinder.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderNearest.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderQuality.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderRandom.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/export/CSVExporterTest.java
- src/test/java/org/mitre/synthea/world/agents/ProviderTest.java
- src/test/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderTest.java
This pull request adds the ability to change patient behavior in how they find or select a provider.
Prior to this pull request, the implicit behavior was equivalent to `nearest` and is the default behavior.
- `nearest` - choose the nearest provider that offers the service needed. If there are several with the same distance, one is selected randomly. This is the default behavior.
- `quality` - choose the best quality provider (within range) that offers the service needed. If there are several, it chooses the nearest.
- `random` - choose a random provider that offers the service needed.
- `network` - choose a provider that offers the service needed that is within the patient's insurance network. Currently, this is equivalent to `random` every time the patient switches insurance. When …
> Provider Finder Behaviors

- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
When exporting Encounter FHIR resources, Synthea is currently outputting
a lowercased version of the EncounterType enum for the Encounter.class
element. However, this value should be from the ActEncounterCode VS:
http://www.hl7.org/implement/standards/fhir/v3/ActEncounterCode/vs.html
This change adds the appropriate value into the EncounterType enum and
updates the STU3 and R4 exporters to use it.
> Fix FHIR Encounter class codes

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/modules/EncounterModule.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRSTU3ExporterTest.java
- src/test/java/org/mitre/synthea/helpers/AttributesTest.java
- src/test/java/org/mitre/synthea/helpers/TransitionMetricsTest.java
This PR has two changes
- Makes wellness encounters actually use wellness providers -- previously it was using ambulatory providers.
- Fixes occasionally incorrect FHIR validation errors on `Period` datatypes, when the `start` appears to be after the `end` but the validation is not correctly accounting for timezone offset changes (i.e. daylight savings time).
> Make wellness encounters use wellness providers.

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/resources/modules/lung_cancer.json
- src/main/resources/modules/surgery/general_anesthesia.json
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/medication_order.json
Companion PR to https://github.com/synthetichealth/module-builder/pull/245. Adds support in the State engine, HealthRecord, and FHIR Exporters for an `administration` attribute on `MedicationOrder` states.
> Support the creation of MedicationAdministration resources for MedicationOrder states

- src/main/java/org/mitre/synthea/helpers/Concepts.java
The `concepts` task is supposed to list out all of the concept codes used within the modules, but I noticed it's missing component observations. For example, the Wellness Encounters module records Blood Pressure, a `MultiObservation` with systolic and diastolic blood pressure, and a Metabolic Panel, a `DiagnosticReport` with a number of component observations, but the codes for all of those observations are missing from the concepts list. This PR adds those in.
Resulting concept list (899 concepts) is attached: 
[concepts.csv.txt](https://github.com/synthetichealth/synthea/files/3402437/concepts.csv.txt)
> Add missing component observations to concepts list

- src/main/resources/modules/opioid_addiction.json
This pull request removes an unfortunate transition back to the `Initial` state that seems to have been added in error. Even if it was intentional, it should have had no effect on the module performance, since it was the last in a list of distributed transitions.
> Removed transition to Initial state from opioid module.

- src/main/java/org/mitre/synthea/engine/Module.java
- src/test/java/org/mitre/synthea/TestHelper.java
Updates the module loading process to support running Synthea from a JAR file (for instance, eclipse IDE supports exporting a project and re-packaging all dependencies into a single JAR). All other resources seem to load fine, only modules needed to be handled differently.  Without these changes, if you try to package synthea into a JAR and run it, you get various exceptions trying to load the files.
This is especially useful for running Synthea in a cluster environment; gradle lockfiles prevent multiple instances from running against the same copy at once, and running the classes directly requires a lot of separate libraries and classpath setup.
> Support running from a JAR file

- src/main/resources/costs/medications.csv
- src/main/resources/modules/asthma.json
- src/main/resources/modules/breast_cancer.json
- src/main/resources/modules/breast_cancer/hormonetherapy_breast.json
- src/main/resources/modules/congestive_heart_failure.json
- src/main/resources/modules/contraceptives/injectable_contraceptive.json
- src/main/resources/modules/cystic_fibrosis.json
- src/main/resources/modules/dementia.json
- src/main/resources/modules/dermatitis.json
- src/main/resources/modules/epilepsy.json
- src/main/resources/modules/fibromyalgia.json
- src/main/resources/modules/gallstones.json
- src/main/resources/modules/gout.json
- src/main/resources/modules/hypertension.json
- src/main/resources/modules/lupus.json
- src/main/resources/modules/medications/otc_pain_reliever.json
- src/main/resources/modules/opioid_addiction.json
- src/main/resources/modules/rheumatoid_arthritis.json
- src/main/resources/modules/surgery/general_anesthesia.json
- src/main/resources/modules/veteran_hyperlipidemia.json
- src/main/resources/modules/veteran_mdd.json
- src/main/resources/modules/veteran_ptsd.json
Reasoning for all changes is in the commit messages. Addresses #469.
> Fix incorrect RxNorm codes in Synthea

- src/main/java/org/mitre/synthea/world/geography/Location.java
Previous settings always added a value to the lat/lon. This will shift
the generated population to the north and east of the desired point.
This change will now allow the generation of negative values for the
random offset. This will generate a population in a circle around the
desired point.
> Fixing lat/lon randomization

- build.gradle
- src/main/java/org/mitre/synthea/engine/Components.java
- src/main/java/org/mitre/synthea/export/CDWExporter.java
- src/main/java/org/mitre/synthea/modules/BloodPressureValueGenerator.java
- src/main/java/org/mitre/synthea/world/concepts/BirthStatistics.java
- src/main/java/org/mitre/synthea/world/concepts/ClinicianSpecialty.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
Add support for pushing synthea.jar to Maven repositories.
Running the new Gradle tasks to publish the jar requires additional local set-up, in particular a Sonatype Jira account and a GnuPGP key pair. Regular builds are unaffected.
> Maven Repo Publishing

- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/world/geography/LocationTest.java
Randomizing zip code selection, fixing placement
Previously, when a person was generated in a city with multiple zip
codes, Synthea would select the first zip code for the city.
This change causes it to randomly choose a zip code.
This also fixes the assignment of the lat / lon to the person. Previously, it would randomly chose a place in a city if multiples existed. Now, if a person has a zip code in a city with multiple zip codes, it will start with the lat / lon of the proper zip code.
> Fix zipcode selection

- build.gradle
- src/main/java/org/mitre/synthea/export/CDWExporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/world/agents/Clinician.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderNearest.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/main/java/org/mitre/synthea/world/geography/Place.java
- src/main/java/org/mitre/synthea/world/geography/quadtree/QuadTree.java
- src/main/java/org/mitre/synthea/world/geography/quadtree/QuadTreeElement.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/helpers/ConfigTest.java
- src/test/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderTest.java
- src/test/java/org/mitre/synthea/world/geography/quadtree/QuadTreeTest.java
- src/test/java/org/mitre/synthea/world/geography/quadtree/TestElement.java
This pull request removes the `org.apache.sis` library dependency and replaces it with a very simple and fast QuadTree class.
While reviewing Pull Request #589 I have been conducting a lot of profiling using `jvisualvm`.
The single largest consumption of CPU time has been calls to `java.lang.Math.acos()` required to compute the Haversine distance while querying the QuadTree from the Apache SIS library. These are queries such as the "find nearest provider" query. According to the profiler, this was taking 28 - 30% of the computation time for each entire run of Synthea.
As an experiment, I replaced the Apache SIS QuadTree which uses Haversine distance calculations (which take into account the curvature of the Earth) with a very simple QuadTree that merely considers Euclidean distance on a …
> Accelerate geographic searches.

- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/concepts/GrowthChart.java
- src/main/java/org/mitre/synthea/world/concepts/GrowthChartEntry.java
- src/test/java/org/mitre/synthea/modules/GrowthChartTest.java
- src/test/java/org/mitre/synthea/modules/LifecycleModuleTest.java
Extract growth chart related items from `LifecycleModule`. This makes the `LifecycleModule` a little smaller with fewer unrelated functions.
This change also parses age in months as well as the LMS values from
strings into ints or doubles on startup as opposed to every time a value
is needed. Rough performance test appears to show a 2x performance
improvement when looking up values in growth charts. On my machine, running `LifecycleModule.lookupGrowthChart` on my laptop 1,000,000 times took ~580ms originally. After the changes, it's down to ~265ms.
> Extracting GrowthChart from LifecycleModule

- build.gradle
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/helpers/ExpressionProcessor.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/helpers/ExpressionProcessorTest.java
- src/test/resources/generic/observation.json
- src/test/resources/generic/set_attribute.json
For discussion:
Implements a simple "expressions" concept (#189) using a CQL engine. SetAttribute, Observations, and VitalSigns now include an "expression" field which gets translated and passed to a CQL engine for evaluation.  The details of the implementation are all abstracted away in a new ExpressionProcessor class. The translation layer allows for selected attributes, identified with a ruby-esque "#{attr}", on the patient to be referenced and added to the evaluation context.
For example, the expression "#{age} / 2 + 7" for a patient with the attribute "age" defined as 26 will result in the following CQL being evaluated:
```
library Synthea version '1'
context Patient
define age: 26
define result: age / 2 + 7
```
My goal here was to enable the kind of basic calculations that are used …
> WIP: Expressions using CQL Engine

- src/main/java/org/mitre/synthea/world/agents/Clinician.java
Fixes #608 providers with duplicate UUIDs.
Through a twist of fate, the `providers.csv` file actually contains `Clinicians`. `Providers` are written into the `organizations.csv` file.
Therefore, the fix to #608 is to increase the variation in the code that assigns UUIDs to `Clinicians`.
> Fix #608 providers with duplicate UUIDs.

- build.gradle
- src/main/java/Graphviz.java
- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/helpers/Attributes.java
- src/main/java/org/mitre/synthea/helpers/Concepts.java
- src/main/java/org/mitre/synthea/helpers/ModuleOverrides.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/engine/ModuleTest.java
- src/test/java/org/mitre/synthea/helpers/ModuleOverridesTest.java
Starting point for "module overrides". The idea here is that we can provide a module override file at runtime that defines parameters that override parts of the generic modules. There are a number of possible use cases for this, for example pre-defining alternative populations (think "internationalization", such as "run with this override file to produce a population matching all condition prevalence rates in Germany"). Also includes a task that can generate a base set of override files with some configurability.
The format of the overrides file is a java properties file, with format:
```
(module file path)::(jsonpath to value) = (new value)
```
example:
```
congestive_heart_failure.json\:\:$['states']['Age_70-79-Chance\ of\ CHF']['distributed_transition'][0]['distribution'] = 0.024 …
```
> Module overrides

- gradle/wrapper/gradle-wrapper.properties
- src/main/java/org/mitre/synthea/helpers/InnerClassTypeAdapterFactory.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
Use newer Gradle distribution and modify Javadoc to get the build running on Java 13.
"gradlew build check test" is running successfully after these changes.
Disclaimer: I'm neither a Java, Gradle or Javadoc expert. This was a simple, naive try to get the build working.
> Fix build on Java 13

- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/engine/GeneratorTest.java
Allows users to specify that only alive patients are generated.
This new property conflicts with only_dead_patients, and I couldn't really find a place to do a check for the conflict, so I thought it better to default them both to false if the user sets them both to true.
Solves #624
> There is now an option to generate only alive patients (Solves #624)

- src/main/java/org/mitre/synthea/modules/WeightLossModule.java
Addresses #660 
Since adjustBMIVectorForSuccessfulManagement gets called multiple times, it kept adding values to the end of the growth trajectory. This code makes sure that even when called multiple times, it will only append a single point.
Also, make sure that we properly limit running over 20 years when
maintaining BMI
> Fix adjustBMIVectorForSuccessfulManagement to only append once

- src/main/java/org/mitre/synthea/export/FhirR4.java
Reverse a bug where only us core patients have a gender in FHIR R4.
Thanks @cmoesel for the bug report!
> Fix FHIR R4 gender.

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/counter.json
Adds an `amount` field to the Counter state, so that counters can count 2 by 2, or 17 by 17, or whatever number you like. Defaults to 1 if the field is not present, so all current usage of the Counter state will work without explicitly adding the field.
> Add amount field to Counter state

- src/main/java/org/mitre/synthea/engine/Logic.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/main/resources/modules/veteran_ptsd.json
- src/test/java/org/mitre/synthea/engine/LogicTest.java
- src/test/resources/generic/logic.json
Fixes attribute logic and a bug in the `veteran_ptsd` module that was silently effected by it.
See #529.
> Fix attribute logic. See #529.

- src/main/java/org/mitre/synthea/engine/Module.java
This was created to deal with #673. I think this will fix the issue, but I find that it is sometimes hard to reproduce.
`Module` keeps a map of `States`. When running, most of these get cloned before they are run. The exception to this is the initial state. `Module` has a function that will return a single instance of the initial state.
Some problems with this, I think we avoid via luck. Others come back to get us via multi-threading.
After the first person has gone through a module, in `Module.process` when adding the initial state to the person's history, `State.exited` will be set to whenever the last time it was used. This can be a value before someone was born in the simulation. It probably doesn't matter, because it gets reset when `State.run` gets called.
What I believe to be the …
> Clone the initial state

- .travis.yml
As a follow up on #654 this PR runs the travis-ci jobs on OpenJDK 13 as well, so future code changes are checked for Java 13 compatibility.
I ran the CI tests with the new changes. The first job failed, but the next job (https://travis-ci.org/bugspencor/synthea/builds/656615725) succeeded without any changes in synthea code. So hopefully the errors in the first build were only random, temporary errors (https://travis-ci.org/bugspencor/synthea/builds/656161105). Building locally (build check test) on my setup with Java 13 worked as well.
> Add openjdk13 to Travis Build Matrix

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/artificial_heart_device.json
Adds new state types Device and SupplyList, which get added to the HealthRecord data model but are not (yet) written out to any exported records.
A Device represents a permanent or semi-permanent device such as a prosthetic or a pacemaker. SupplyList represents the generic supplies needed to perform the encounter, like gloves, mask, other PPE, etc
IMPORTANT: I discovered that the new serialization feature doesn't work when the patient's record contains `JsonObject`s. Here I was using one for supplies since we aren't doing anything but exporting yet, but we're also using one already for CarePlan goals, so we should address both of those. I can do that here but wanted to get this PR up asap.
> Add Device & SupplyList to GMF

- build.gradle
Hello people,
This pull request excludes a dependency from the project's `build.gradle` in order to have a single binding for SLF4J on classpath.
Thanks,
Jafer
> Make available only one binding for SLF4J on classpath (fixes #659)

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/CSVExporterTest.java
- src/test/resources/generic/artificial_heart_device.json
In support of the new Device and SupplyList fields recently added to the GMF, this adds Device and SupplyDelivery resources to FHIR exporters (R4, STU3, and DSTU2) and creates new devices.csv and supplies.csv in the CSV exporter.
Travis is failing right now because of issues with the oss.sonatype.org repo, but if you already have all the libraries loaded it works.
Samples containing the new output:
FHIR R4: [Shannon293_Schumm995_r4.json.txt](https://github.com/synthetichealth/synthea/files/4402447/Shannon293_Schumm995_r4.json.txt)
STU3: [Shannon293_Schumm995_stu3.json.txt](https://github.com/synthetichealth/synthea/files/4402451/Shannon293_Schumm995_stu3.json.txt)
DSTU2:  [Shannon293_Schumm995_dstu2.json.txt](https://github.com/synthetichealth/synthea/files/4402453/Shannon293_Schumm995_dst …
> Export Device and SupplyDelivery resources in FHIR and CSV

- src/main/java/org/mitre/synthea/engine/Transition.java
- src/test/java/org/mitre/synthea/engine/LookupTableTransitionTest.java
- src/test/resources/generic/lookup_tables/lookuptable_timerangetest.csv
- src/test/resources/generic/lookuptable_timerangetest.json
This change allows time to be used a a property in
LookupTableTransitions. It only supports time ranges, as exact times are
unlikely to be useful. Time refers to the time in the simulation. Time
ranges can be combined with any other attributes that would be valid for
a LookupTableTransition.
This was extracted from the `covid19lookuptable` branch. This will allow us to get the capability into Synthea without needing to worry about getting the COVID-19 probabilities correct.
> Allow time as a property in LookupTableTransitions

- build.gradle
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/engine/Transition.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/resources/modules/covid19/admission.json
- src/main/resources/modules/covid19/supplies_hospitalization.json
- src/main/resources/modules/covid19/supplies_icu.json
- src/main/resources/modules/covid19/supplies_intubation.json
- src/test/java/org/mitre/synthea/engine/LookupTableTransitionTest.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/CSVExporterTest.java
- src/test/resources/generic/artificial_heart_device.json
- src/test/resources/generic/lookup_tables/lookuptable_timerangetest.csv
- src/test/resources/generic/lookuptable_timerangetest.json
Adds 3 supplies submodules to the COVID19 track - one for daily supplies in general inpatient care, one for daily supplies in intensive care, one for the supplies needed for the intubation process. These 3 submodules are called at appropriate times in the admissions submodule - 2 Simple state placeholders were replaced with CallSubmodules, and 1 was added right before the Intubation Procedure state.
Note that the covid19 branch doesn't currently have the Device and SupplyList states that were recently merged into master, so I merged all the latest from master into this branch. If that makes things too messy I can look into cherry-picking instead.
> Covid19 Supplies

- src/main/java/Graphviz.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/artificial_heart_device.json
Adds a DeviceEnd state to support removal of devices associated to patients. The Device to remove can be referenced by an attribute, the name of the state where the Device was added, or by SNOMED code. Assigning Devices to an attribute was not previously supported so that has been added as well.
I also realized I forgot to update Graphviz for the Device and SupplyList states previously so that's now been added as well.
> Add DeviceEnd state

- src/main/java/org/mitre/synthea/export/CSVExporter.java
Adds time information to the `DATE` or `START` and `STOP` fields in the following CSV output files: (basically any care-driven information which would be precisely captured in an EHR and where the time/sequence component is potentially relevant within the scope of a single day)
- Observations
- Procedures
- Medications
- ImagingStudies
- Devices
- Immunization (now that I write this I realize it may not have that same single-day relevance, but it shouldn't hurt to include it)
Notably this doesn't include things like Conditions and Allergies which are less likely to have a well-defined start and end, or have their start and end times be meaningful within the context of a single day. If there's a push for it we could also consider just making every date in the CSVs a date+time.
> Add times to dates on select CSV exports

- build.gradle
This pull request only updates a dependency.
The expression processing code uses the CQL engine.
The version in Synthea is `1.3.10-SNAPSHOT` which seems to no longer be available.
This PR updates the dependency to `1.3.12`.
> Update CQL engine off of snapshot.

- build.gradle
- src/main/java/org/mitre/synthea/engine/Components.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/helpers/ChartRenderer.java
- src/main/java/org/mitre/synthea/helpers/physiology/IoMapper.java
- src/main/java/org/mitre/synthea/helpers/physiology/PreGenerator.java
- src/main/resources/modules/gallstones.json
- src/main/resources/physiology/models/circulation/McSharry2003_Synthetic_ECG.xml
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRSTU3ExporterTest.java
- src/test/java/org/mitre/synthea/helpers/TimeSeriesDataTest.java
- src/test/resources/generic/observation.json
- src/test/resources/generic/smith_physiology.json
Added ability to disable Physiology State simulations in the `synthea.properties` file (and they are now disabled by default). This also involved adding an `alt_direct_transition` field to Physiology state definitions to indicate where the Module should flow in the event Physiology States are disabled.
Note that this also includes updates from the (yet unmerged) `observation_media` branch.
> Physiology State Enable/Disable

- build.gradle
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/modules/EncounterModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/test/java/AppTest.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/modules/EncounterModuleTest.java
1. Ensure all encounters started by the encounter module are ended.
2. Prevent the encounter module from starting a new encounter in the middle of another encounter from a different module.
> Fixes to the encounter module.

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/resources/modules/allergic_rhinitis.json
- src/main/resources/modules/asthma.json
- src/main/resources/modules/bronchitis.json
- src/main/resources/modules/copd.json
- src/main/resources/modules/covid19/admission.json
- src/main/resources/modules/dementia.json
- src/main/resources/modules/dermatitis.json
- src/main/resources/modules/ear_infections.json
- src/main/resources/modules/hypertension.json
- src/main/resources/modules/med_rec.json
- src/main/resources/modules/metabolic_syndrome_care.json
- src/main/resources/modules/osteoporosis.json
- src/main/resources/modules/urinary_tract_infections.json
- src/main/resources/modules/wellness_encounters.json
This pull request:
1. Adds encounter end states for encounters that were left open in modules
2. Moves symptom delays out of encounters to ensure they run for a more realistic length of time
3. Ensures sub-module encounters are removed from the list of current module encounters
The net result is that wellness encounters that were being blocked by open encounters will now proceed.
> Module Encounter Fixes

- src/main/resources/modules/appendicitis.json
The appendicitis module was written that encounters were auto closing.
Since the ED encounter is never closed, in some cases it can remain open
for an incredibly long time (decades). This fixes it for the
appendicitis module, but there is still at least one case of a hanging
open encounter in the injury module.
> Closing ED Encounter for appendicitis

- src/main/java/org/mitre/synthea/datastore/DataStore.java
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/export/CCDAExporter.java
- src/main/java/org/mitre/synthea/export/CPCDSExporter.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirGroupExporterR4.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterR4.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/export/HospitalExporterR4.java
- src/main/java/org/mitre/synthea/helpers/RandomNumberGenerator.java
- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/engine/LogicTest.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRSTU3ExporterTest.java
- src/test/java/org/mitre/synthea/export/HospitalExporterTestR4.java
- src/test/java/org/mitre/synthea/modules/DeathModuleTest.java
- src/test/java/org/mitre/synthea/world/agents/PersonTest.java
This pull request builds on recent work to improve the reproducibility of generated records when using the same patient seed, provider seed and reference date. This pull request introduces reproducible resource and element ids so diffing two sets of generated patients will not yield differences resulting from random ids.
To test:
```
./run_synthea -p 10 -s 5 -cs 10 -r 20200701
mv output/fhir output/fhir2
./run_synthea -p 10 -s 5 -cs 10 -r 20200701
```
Diff the corresponding files in `output/fhir` and `output/fhir2`.
> Reproducible IDs for FHIR resources and CCDA elements.

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/engine/LogicTest.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/procedure_duration_and_death.json
This change addresses issue #735.
**Edit**
The PR has now been changed.  
Procedure now acts like a Delay state. This PR introduces an abstract Delayable state that is now implemented by Delay and Procedure.
**Old PR**
Procedures with duration add time to the end of an encounter. That pushes the end of the encounter beyond the current time step. If an encounter is ended and followed by a death state, the time of death is set to the current time step. This means that the death will happen before the encounter is closed.
This PR changes the Death state to look at the end time of the last encounter. If that happens, it will push the time back to the end of the encounter.
> Fix for encounters that end after death

- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/test/java/org/mitre/synthea/helpers/UtilitiesTest.java
Discovered via CI that the DICOM UIDs include the current timestamp, which if before 1970 are negative and the minus sign breaks the expected format. These aren't expected to be 100% guaranteed unique in the way UUIDs are so just use the absolute value of the time.
> Fix DICOM UIDs

- build.gradle
When generating large sets of data, I noticed that the generation was gradually slowing down time went on. I figured this was due to memory starvation.
I couldn't figure out a way to set the Xmx of the application process through the command line without changing the build.gradle file. So I added in a way to specify it using an environment variable.
Let me know if there is a better way of doing this!
> Make max heap size of application process configurable

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
This PR tweaks the `Delayable` interface that `Procedure` and `Delay` states and adds a new `processOnce` method, which should only be executed a single time, regardless of how many times the `process` method gets called. The `Procedure` state now overrides this "hook" method instead of having a `process` method which calls back to `super.process`.
(I can envision in the future we might want a "processEveryTimestep" hook method as well, but since we don't need one today and it's trivial to add later, I didn't add it now)
This addresses a bug where Procedures were being added to the record twice because the corresponding state was processing twice.
> Fix procedures with delays to ensure the record entry is only added once

- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
> Use “Non Hispanic or Latino” instead of “Not Hispanic or Latino”

- .gitignore
One line added to gitignore file to ignore generated files in project's `out/` directory. The directory is populated when tests are run.
> Ignore test generated output

- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
Fixes FHIR Identifiers with a system of `urn:ietf:rfc:3986` which require a value that is a URI with a proper prefix (e.g. `urn:uuid:`).
See http://hl7.org/fhir/R4/datatypes.html#Identifier and https://github.com/onc-healthit/inferno-program/issues/179
> Fix FHIR identifiers that require prefix.

- build.gradle
- src/main/java/org/mitre/synthea/helpers/Concepts.java
- src/main/java/org/mitre/synthea/world/concepts/Costs.java
- src/main/resources/costs/encounters.csv
- src/main/resources/costs/medications.csv
- src/main/resources/costs/procedures.csv
- src/main/resources/modules/covid19/symptoms.json
- src/test/java/org/mitre/synthea/helpers/ConceptsTest.java
- src/test/java/org/mitre/synthea/world/concepts/CostsTest.java
This Pull Request adds costs (min/mode/max) for concepts in Synthea that were missing specified costs. It adds:
- 78 Medication costs
- 145 Procedure costs
This PR also adds a new gradle command which generates a csv list of concepts that are missing specified costs:
- `./gradlew conceptswithoutcosts`
- When using this command, it will also output concepts like conditions that should not have a cost.
Notes:
- This PR provides costs for all of the medications currently in Synthea except 3 (Pancreatin 600 MG Oral Tablet, Leronlimab 700 MG Injection, Lenzilumab 200 MG IV)
- Although many of the SNOMED code costs were added, there are still ~60 that lack cost information.
Sources:
- Each of the added costs includes a link to the source used in their csv entry.
- Medications: most medication …
> Costs August 2020 Update (V3)

- src/main/java/org/mitre/synthea/export/ExportHelper.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterDstu2.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterStu3.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/export/HospitalExporterDstu2.java
- src/main/java/org/mitre/synthea/export/HospitalExporterStu3.java
Also:
- Adds display text to practitioner references in encounter resources.
- Makes practitioner IDs consistent across R4, DSTU2 and STU3.
> Apply resource deduplification fix from FHIR R4 exporter to DSTU2 and STU3 exporters

- src/main/resources/modules/opioid_addiction.json
- src/main/resources/modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json
Add a new module prescribing opioids for chronic pain and treatment of Opioids Use Disorder. As the prescribing opioids for chronic pain module applies to year 2014 and after modified the Opioid Addiction module from guard >=1990 to guard >=1990 and < 2014. The following is the description of the new module:
"This module models the prescribing of opioids for chronic pain and treatment of opioid use disorder (OUD) for patients age >= 18. It is based on the Centers for Disease Control (CDC) Guideline for Prescribing Opioids for Chronic Pain. This CDC guideline provides recommendations for the prescribing of opioid pain medication by primary care clinicians for chronic pain (i.e., pain conditions that typically last >3 months or past the time of normal tissue healing) in outpatient settings …
> new module prescribing opioids for chronic pain and treatment of OUD.

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
Synthea ImagingStudy states can have procedure codes, but nothing really
happens with them in the simulation or export.
This takes the procedure code and adds it to the entry for ImagingStudy
in the HealthRecord. It then updates the export for FHIR STU3, R4 and
CSV so that the procedure code is exported. FHIR DSTU2 doesn't appear to
have a place in the ImagingStudy resource for procedure code.
> Adding procedure codes to Imaging Studies

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/test/java/org/mitre/synthea/engine/FixedRecordTest.java
- src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRSTU3ExporterTest.java
This PR intends to fix a few issues, mostly in unit tests, relating to memory usage and weird exceptions. This gets pretty involved so please don't hesitate to ask if the fixes aren't clear.
Note: when looking at the diff I highly recommend using "ignore whitespace changes" as the 3 FHIR exporter test diffs are mostly indentation changes
1. Occasionally I've seen `NotSerializableException`s in `GeneratorTest.testUpdateAfterCreationAndSerialization` because of FixedRecordGroup not being Serializable. At a glance this doesn't make sense because this test doesn't use fixed records. But deeper analysis revealed that our approach with `clone()` methods left some dangling references. 
- First issue is that we aren't even using the `clone()` method correctly. The top-level `Object.clone()` …
> Even more assorted bugfixes

- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/export/CSVExporterTest.java
Adds configuration options for included and excluded files in the CSV exporter. Since many use cases don't require every single CSV file, we can save some space and computing time by not exporting them in the first place. (I'm looking at you, observations.csv...)
If you specify a list of files in `exporter.csv.included_files`, then only those files will be exported. (and if you don't include `patients.csv` in the list, it will yell at you but still process as expected)
If you specify a list of files in `exporter.csv.included_files`, then all other files will be exported and the named files will not be.
If you specify both config options, it will ignore both and do the default, export every file.
The basic approach here is to use a "no-op" implementation of an OutputStream, so that we only …
> Include/Exclude for CSV exporter files

- src/test/java/org/mitre/synthea/helpers/UtilitiesTest.java
testYears fails towards the end of the calendar year. This is due to the
fact that the convertTime method does not account for leap years.
Unfortunately, code in other parts of Synthea depends on this behavior.
This fixes the test from failing by using a fixed date for the test as
opposed to the current time, ensuring that the code doesn't encounter
a problematic date.
This PR eliminates the need for #842.
> Fix test that fails towards end of calendar year

- src/main/java/Graphviz.java
- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/helpers/Attributes.java
- src/main/java/org/mitre/synthea/helpers/Concepts.java
- src/main/java/org/mitre/synthea/helpers/ModuleOverrides.java
- src/test/java/org/mitre/synthea/engine/LogicTest.java
- src/test/java/org/mitre/synthea/engine/ModuleTest.java
- src/test/java/org/mitre/synthea/helpers/ConceptsTest.java
Cleans up use of deprecated methods in both the main source code and test suite. This eliminates warnings for deprecation when the project builds.
> Remove deprecated code

- src/main/resources/modules/medications/hypertension_medication.json
* Fixed transition bug in a couple of conditional transitions: changed `Condition Active` to `Medication Active` on amlodipine.
* Eliminated redundant logic for proteinuria and microalbuminuria (which should put the patient on lisinopril 10 MG Oral Tablet regardless of whether they're on other meds) for state `Step 2 High`.
> Hypertension medication module: fix medication tagged as condition and remove redundant logic

- src/main/java/org/mitre/synthea/engine/Distribution.java
- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/helpers/RandomValueGenerator.java
- src/test/java/org/mitre/synthea/engine/DistributionTest.java
- src/test/java/org/mitre/synthea/engine/ModuleTest.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/busted_distribution/module_with_bad_distribution.json
- src/test/resources/generic/gmf_two_point_oh.json
This change supports a new `distribution` property in `Delay`, `Observation`, `Procedure`, `SetAttribute`, `Symptom` and `VitalSign` states. 
For example, an `Observation` of LDL Cholesterol with a Gaussian distribution of results would be:
```json
"Observation" : {
"type" : "Observation",
"category" : "procedure",
"codes" : [
{
"system" : "LOINC",
"code" : "2089-1",
"display" : "Cholesterol in LDL"
}
],
"distribution": {
"kind": "GAUSSIAN",
"parameters": {
"mean": 140,
"standardDeviation": 15
}
},
"unit": "mg/dL",
}
```
All states still support the "legacy" format for defining ranges or whatever they call themselves. Current distribution types in this PR are:
* Exact
* Uniform
* Gaussian
The Distribution class should make it easy to add any other distribution types desired.
> Support different distribution types for random variables in a new GMF format

- src/main/java/org/mitre/synthea/export/CSVExporter.java
Updates the procedures.csv exporter to export the procedure end time, so we can track procedure duration. This was already in the HealthRecord data model, we just weren't exporting it in CSV. For consistency with other tables, I renamed the DATE column to START, so we now have START and STOP.
I think this might be the first time we are renaming a CSV column, and since we can't regenerate every old dataset that someone may have, I suggest we mention this in the wiki:
| | Column Name | Data Type | Required? | Description |
|-|-------------|-----------|-----------|-------------|
| | Start <br/> ("Date", prior to v3.0.0 ) | iso8601 UTC Date (`yyyy-MM-dd'T'HH:mm'Z'`) | `true` | The date and time the procedure was performed. |
| | Stop | iso8601 UTC Date (`yyyy-MM-dd'T'HH:mm'Z'`) | `false` | …
> Change procedures.csv DATE column to START and STOP

- run_synthea.bat
The Windows batch script `run_synthea.bat` has a minor bug where as it copies arguments to pass into gradle, it also evaluates them. Most of the time this will have no impact, but if one of the command line args contains a wildcard (`*`) then this evaluates it again unexpectedly, and it essentially deletes that arg.
Note that I said "again" - the windows shell already does expansion once for anything that matches a wildcard, so for instance in the main synthea folder `g*` becomes `gradle gradlew gradlew.bat` but `go*` would stay `go*` since there are no maches. But in short I don't think there's any scenario where evaluating it a second time would be correct. This is tough to explain so some examples are below.
Really this only affects the `-m` flag, or possibly some config settings, but …
> Update run_synthea.bat to not evaluate args

- src/main/java/App.java
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/engine/GeneratorTest.java
- src/test/resources/keep_patients_module/keep.json
This PR introduces the ability to specify a special GMF module that determines criteria for a patient to be exported.
Because the GMF doesn't have the concept of "returning a value" explicitly, this takes the approach of using a named state to determine whether a patient record should be kept or not. (I don't love magic names, but we already require the "Initial" state name.) If a patient finishes in a Terminal state named "Keep" then the record is kept, otherwise the record is discarded, the seed rotated, and another record is generated and tested.
(Another possible approach, if people don't like requiring a specific name, would be to set a specific attribute to true/false)
Use the feature with `./run_synthea -k (path_to_module_file)`
Note that this uses a reduced version of …
> Add ability to select patients to keep/export using a GMF module

- src/main/java/Graphviz.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/engine/Transition.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/main/java/org/mitre/synthea/world/concepts/Names.java
- src/main/resources/modules/hypothyroidism.json
- src/main/resources/modules/sepsis.json
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/switching_provider.json
This PR includes a mishmash of various fixes and tweaks pulled from multiple active working branches, in order to reduce the changes left on those branches to what's really important, and ensure these fixes are available throughout.
Where possible, these commits were cherry-picked from other branches to help git figure out how to merge and rebase later.
Details of changes:
- `src/main/java/Graphviz.java`: fix a bug in rendering graphviz for modules that use the "Vital Sign" type logic 
- `src/main/java/org/mitre/synthea/engine/State.java`: 
1.  allow calling Java modules via the "CallSubmodule" state, and ensure that module history isn't duplicated (this caused an issue when a Java module was called repeatedly and the module history grows exponentially)
2. fix a bug with Delays occuring …
> Odds and Ends

- build.gradle
Fix `:uberJar` gradle task after Gradle 7 upgrade.
> Fix uberJar task.

- .github/workflows/deploy.yml
There's currently a bug in the deploy workflow, where the master-branch-latest is left in a "draft" / unpublished state. (People probably haven't noticed since we don't do that many merges to master and I try to manually publish it right away)
While investigating I noticed the actions/create-release action is marked as unmaintained, so I figured it would be good to switch to another action.
This change does 2 things:
1 - switches to using a new release action that is maintained
2 - adds another "publish" step to the workflow, after the uberJar is uploaded, to make sure the release isn't marked as draft
> Update Deploy Workflow

- .github/workflows/ci-build-test.yml
Now that we upgraded to gradle 7.0, we should be able to use jdk16 (the most recent version of java as of march)
> Bump ci to run on jdk16

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/gaussian_distro_delay.json
Now, when a Delayable generates the length of delay, if it would be
negative, it's just set to zero. Essentially the Delay state will
complete at the current time.
Added tests to validate. Also added a test to ensure that Gaussian
delays actually generating values with a distribution mean close
to the specified mean.
Addresses #885
> Fix for Delays that could possibly have a negative time

- build.gradle
- src/main/java/org/mitre/synthea/helpers/SerializableTypeAdapter.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
This PR fixes #897 and makes Synthea work in Java 16 by introducing a new TypeAdapter for GSON, to allow serializing and deserializing classes that are in core Java packages. (ie, `java.*.*`). In practice it seems like the only core class that we try to serialize is java.util.Random, but I made this generic so that if we need to add more in the future this should make it easy. The basic approach is to leverage the existing java Serializable functionality to write the object to a string, then base64 it. (It turns out for the `java.util.Random` class all the relevant fields are private, so there aren't many other options to serialize it)
Note that I think the only time this will actually get called is when someone does population snapshotting. But we need the TypeAdapter present for loading …
> Support for de/serializing Random class in GSON

- src/main/resources/language_lookup.json
Per #909, FHIR requires the use of the system `urn:ietf:bcp:47` in the [Patient.communication.language](https://www.hl7.org/fhir/patient-definitions.html#Patient.communication.language) element. A handful of languages (5) in language_lookup.json currently use `http://id.loc.gov/vocabulary/iso639-1` as the system URI, which raises a validation error in some FHIR server implementations. 
[BCP: 47, Section 2.2.1](https://tools.ietf.org/search/bcp47#section-2.2.1) designates ISO 639 language subtags as conforming with BCP: 47. As such, the only change made is to update the systems of the 5 language entries to `urn:ietf:bcp:47`.
> Update language lookup to always use BCP: 47

- .github/workflows/ci-build-test.yml
Quick change to the CI script to only run the slack notification step for PRs/commits, etc, if the webhook URL is configured. Our notifications should still occur for commits and PRs on synthetichealth/synthea, but should no longer fail CI for PRs coming from forks (such as this one) because the webhook URL secret is not passed to forks
> Only run Slack notification step on CI if the webhook URL is defined

- src/main/java/App.java
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/export/MetadataExporter.java
- src/main/resources/synthea.properties
Currently in the FHIR exporter we include patient seed, population seed, and Synthea version, but these are not available in any other data formats. Rather than add them individually to the other formats, this metadata exporter outputs info about the most recent run as a JSON file.
Notes:
- I set the new config setting to default to true, because it's a lot better to have it and not need it, than to create a large CSV population and forget the seed you used when you want to recreate it. If people disagree I'm fine disabling it by default though
- Each run gets a separate metadata file, just to minimize the chance of weirdness in case people have multiple instances running at the same time.
- The filename is `{timestamp} _ {population size} _ {state} _ { city? } _ {run ID}` to make it more …
> Metadata exporter

- src/main/java/org/mitre/synthea/modules/covid/C19ImmunizationModule.java
- src/test/java/org/mitre/synthea/modules/covid/C19ImmunizationModuleTest.java
The Immunizations module sets an attribute on Person that keeps a map
of vaccines to a list of timestamps when the vaccine was given. The
original implementation of COVID-19 vaccination did not update this map.
The changes here now add to this map the match the Immunizations module.
> Updating COVID-19 Immunizations existing Immunizations module

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
This PR addresses cases where `HealthRecord.Entry`s can have multiple instances of the same `Code` in their `codes` property. In cases where a `Person` in the simulation passes through the same `ConditionOnset` state multiple times, Synthea will just keep appending the same condition codes to the `Entry`. This change now checks to see if the `Code` already exists in the `Entry`.
> Prevent duplicate codes in HealthRecord Entries

- build.gradle
When running `./gradlew dependencies` I see  transitive dependencies that use log4j versions vulnerable to log4shell. This PR ensures dependencies use log4j 2.17.0, which contains the patch
> ensure transitive dependencies do not use vulnerable log4j

- README.md
- src/main/java/App.java
And cleanup extraneous paren in usage info.
In my particular case, I was looking for an option to generate more patients with the same set of clinicians/providers, which I now assume is the `-cs` option (which wasn't documented here previously).
> Add more usage info to the README

- .gitignore
- NOTICE
- README.md
- build.gradle
- src/main/resources/log4j2.xml
The PR is a follow up to #969.
That PR ended up generating a new log file: `jsbml.log`.
This PR reverts to the previous behavior where log output is silenced or to the console only.
> Restore log silencing by default.

- build.gradle
- src/test/java/org/mitre/synthea/ParallelTestingService.java
- src/test/java/org/mitre/synthea/PersonTester.java
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/engine/GeneratorTest.java
- src/test/java/org/mitre/synthea/export/CCDAExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
- src/test/java/org/mitre/synthea/export/FHIRSTU3ExporterTest.java
This PR attempts to reduce the amount of time it takes to run the Synthea test suite. On my machine, it reduces the time by about 2 - 3 minutes. It includes the following changes:
* For exporter tests, 10 people are generated and then serialized out to byte arrays. Each time an exporter test is run, a Person object is rehydrated from the byte array, so the test will get an unmodified copy. This removes several places where the Generator would be spun up and used to create 10 patients
* Some exporter tests are now multithreaded. Export and validation takes place on a separate thread.
* Serialization and deserialization testing in Generator was reduced from 100 people to 10 people
Some things that I tried, but didn't work or hinder greater performance gains:
* Gradle allows for parallel …
> Decrease the time it takes to run the test suite

- .github/workflows/ci-build-test.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Java 17 (LTS) was released in September, so we need to support it. Gradle added JDK17 support in 7.3, so this bumps that version and the CI test. From some quick testing it doesn't seem like anything else breaks on java 17 or gradle 7.3, but we should verify more thoroughly before merging
> Support java 17

- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
This PR alters the BBRIFExporter, adjusting the DRG mapping in `inpatient` export down a dozen lines of code or so, makes it so that more codes can be successfully mapped.
The mapping check was immediately after looking at the `encounter.reason` code, which isn't always there.
Moving this block of code further down, means it is much more likely a principal diagnosis is in place to map.
> Adjust DRG mapping until later catches more codes.

- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
Fixes an issue where a death date in the future would be used in the RIF exporter.
> Ignore death dates beyond the end of the simulation in the RIF exporter

- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/export/Exporter.java
Don't export claims for encounters that finished before the export date range defined by effective time and years of export history.
> BFD: Exclude claims for encounters outside of the export date range

- src/test/java/org/mitre/synthea/world/geography/DemographicsTest.java
Seeding the Random in this test to prevent intermittent test failures
Should address one of the issues raised in #983
> Fix intermittent failures for DemographicsTest

- src/test/resources/generic/switching_provider.json
See https://github.com/synthetichealth/module-builder/pull/303 for an explanation of why this was there in the first place and what it generates.
> Remove unnecessary assign_to_attribute in switching_provider module

- src/main/java/org/mitre/synthea/engine/Transition.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/test/java/org/mitre/synthea/helpers/UtilitiesTest.java
Look up table transitions previously allowed for decisions to be made on the time in the simulation. The way that this works is that time ranges can be defined using milliseconds since the epoch. This works, but is not great for human readability.
This PR preserves that capability, but also allows for date ranges to be defined as ISO Dates. This means what was previously:
`1599264000000-1627948800000`
can now be represented as:
`2020-09-05-2021-08-03`
For those who prefer the old format (there is probably someone), it still works.
> Allow ISO formatted dates in look up table transitions

- src/main/java/org/mitre/synthea/engine/State.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/resources/generic/condition_onset.json
The way that the Module Builder worked, ConditionOnset states would
have a blank assign_to_attribute by default. This would cause a
blank attribute to show up in everyones' records. That has been
addressed in the Module Builder, but this change ensures that the
blank attribute won't be created if older GMF is used.
This is sort of an add on to #989
> Better handle blank assign_to_attribute

- src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java
The `CardiovascularDiseaseModule` module will add the same code to an `Entry` multiple times. This is mostly harmless, but will end up with CCDA exports that have multiple translations in code blocks, all with the same code.
This change ensures that codes are added only once.
This PR addresses issue #992
> Stop CardiovascularDiseaseModule from adding multiple codes to the same Entry

- src/main/java/org/mitre/synthea/world/geography/Demographics.java
- src/main/resources/geography/zipcodes.csv
- Fixes a rare exception related to demographic distributions that are all zeroes (e.g., if every income bracket for a location has a zero probability -- then a person cannot exist within any of the income brackets, and a runtime exception is thrown).
- Rather than patch the demographics file, part of this fix is to detect all zero distributions and use a default uniform distribution (which was already being applied in the case where the distributions were null instead of zero). Don't like that? Override the demographics file.
- I also made partial fixes to the demographics file (fixed one county in New Mexico that was especially egregious in this regard).
- One other fix related to Unicode accented n's
> Demographics fix

- src/main/java/Graphviz.java
This PR adds the ability to render table based transitions to the `./gradlew graphviz` task.
The labeling follows the same standard as the Module Builder.
Example rendering:
This PR does not address the preexisting overflow/word-wrap issue displayed in the example above.
> Add table based transitions to Java Graphviz rendering.

- .github/ISSUE_TEMPLATE/bug-template.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-template.yml
Implement issue templates for Synthea
* Turns off just opening a blank issue
* Makes users select bug or feature request
* Bug template discourages users from asking open questions and points them to discussions
* Feature request points users to discussions first and also the contributions to avoid section of the wiki
> Issue template

- src/main/java/org/mitre/synthea/modules/WeightLossModule.java
- src/test/java/org/mitre/synthea/modules/WeightLossModuleTest.java
This fix addresses an issue where weight could be calculated as not a number
due to a divide by zero error.
This happened when a person had successful weight management, starting at age
13 and then regressing back to their original weight trajectory. The issue
would happen when attempting to determine what percentage of the "adult"
(after age 20) part of regression had elapsed. Since the adult regression
period was less than one year, it was setting the denominator of the
equation to zero.
The fix now sets this denominator to 1, making the calculation of percentage
elapsed the fraction over age 20 that the person is at the time of the weight
measurement.
Addresses issue #1038 
There are checkstyle issues currently in the master branch that this PR does not address. Those issues are fixed …
> Fixes rare issue with weight management regression

- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/world/geography/LocationTest.java
Meant to address #1046 
Not sure about this "fix" though because it may just mask the fact that a place exists without a corresponding entry in the zip code file.
Which shouldn't happen.
> Add null check to assignPoint methods.

- README.md
- src/main/java/App.java
Adjust readme and help to remove -m.
Add `=` to `--config=value` settings, even though the `=` is optional and not required.
Also, removing mentions of the `-m` feature, even though it still exists. It does more harm than good, so I don't want to advertise it.
> Adjust readme and help to remove -m.

- src/main/resources/modules/encounter/vitals.json
BP code was incorrect in 1 out of 9 instances in the modules where BP was recorded.
See
- Stackoverflow  thread https://stackoverflow.com/questions/71246204/fhir-to-omop-mapping-question-blood-pressure-systolic-and-diastolic-with-unmapp/71246501#71246501
- FHIR Spec http://hl7.org/fhir/STU3/observation-vitalsigns.html
> Fix BP code to be the required code.

- src/main/java/org/mitre/synthea/modules/BloodPressureValueGenerator.java
- src/main/resources/htn_drugs.csv
One more PR bringing features over from `cabg_cardio_gmf_htn_trial`. This PR reworks the Blood Pressure model to account for hypertension medications having impact. Ultimately I think this kind of thing could be reworked to medications having impact on arbitrary vital signs, but this is a first step.
Medications are defined in file `src/main/resources/htn_drugs.csv` with, as of this writing, more columns and codes than are required, so I may pare that down from what we had previously. Most important are the "code" and "impact minimum" and "impact maximum" columns, which are the RxNorm code and the expected range in mmHg of impact on blood pressure the medication is expected to have. As of now all drugs have impact range -11.5 to -16.29.
The basic approach of the model is:
- determine …
> Blood pressure model with medication impacts

- src/test/java/org/mitre/synthea/engine/FixedRecordTest.java
Fix unit test failure on FixedRecords when it generates someone who dies.
```
org.mitre.synthea.engine.FixedRecordTest > fixedDemographicsImportTest FAILED
java.lang.AssertionError: expected:<4> but was:<5>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at org.mitre.synthea.engine.FixedRecordTest.fixedDemographicsImportTest(FixedRecordTest.java:58)
```
> Fix occasional unit test failure.

- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
There was a bug that multiple medication administrations were not being output on a patient record unless that medication was also ended for each administration.
However, ending the medication after every administration is not a good idea, because that patient could also have an open prescription for that medication.
This fix ensures that MedicationAdministrations and open ongoing prescriptions of the same medications do not conflict, and both are recorded in the output files.
You can replicate the error on `master` and the fix on this branch using the below modules (looking for an annual inpatient encounters called "Dummy Encounter" and Medication/MedicationAdministration named "Administered Injection", "Chronic Injection", and "Administered Chronic Injection"). …
> Fix #1079 multiple administrations.

- src/main/java/org/mitre/synthea/export/CCDAExporter.java
- src/main/resources/templates/ccda/social_history_no_current.ftl
This PR contains two fixes.
The first fix moves a single line in the CCDA template, and addresses the following stack trace when a patient has no documented history of smoking.
```
org.mitre.synthea.export.CCDAExporterTest > testCCDAExport FAILED
java.lang.AssertionError: Validation of exported CCDA failed: index=41, size=41|Consol Continuity of Care Document (CCD) (V3) SHALL contain  [1..1] component such that it  (CONF:1198-30687, CONF:1198-30688) Conforms to Social History Section (V3) (templateId: 2.16.840.1.113883.10.20.22.2.17:2015-08-01) expected:<0> but was:<2>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.mitre.synthea.export.CCDAExporterTest.testCCDAExport(CCDAExporterTest.java: …
```
> Two more CCDA fixes

- src/main/java/org/mitre/synthea/export/FhirR4.java
Avoid a rare NPE on FHIR export.
```
org.mitre.synthea.export.FHIRR4ExporterTest > testFHIRR4Export FAILED
java.lang.NullPointerException
at org.mitre.synthea.export.FhirR4.findLocationUrl(FhirR4.java:883)
at org.mitre.synthea.export.FhirR4.encounter(FhirR4.java:773)
at org.mitre.synthea.export.FhirR4.convertToFHIR(FhirR4.java:268)
at org.mitre.synthea.export.FhirR4.convertToFHIRJson(FhirR4.java:355)
at org.mitre.synthea.export.FHIRR4ExporterTest.lambda$testFHIRR4Export$0(FHIRR4ExporterTest.java:114)
```
> Avoid NPE on looking up provider location references.

- src/main/java/org/mitre/synthea/identity/Entity.java
- src/test/java/org/mitre/synthea/identity/EntityTest.java
When converting timestamps into LocalDates, the code was using the
local system timezone, when it should be using UTC. This was an issue
for some fixed records with a birthdate that happens in the year
before the start of Daylight Saving Time. This fix switches to using
UTC.
> Fixes an issue with fixed records, birthdates and timezones

- src/main/java/org/mitre/synthea/export/CDWExporter.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/SymptomCSVExporter.java
Fixes #1131 and #1130.
Adds default value for `exporter.encoding` in the code.
This is important for when a `synthea.properties` file does not specify a value, which causes the effected exporters to fail. This can happen with synthea-international configurations, for example.
> Add default value for exporter.encoding in code.

- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirR4PatientHome.java
This PR fixes #1146 by adding an `Identifier` to the patient's home `Location` so it can be referenced by identifier.
> Add Identifier to Patient Home Location

- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
Seconds were omitted from the timestamp when their value was zero. Fixes #1160.
> Fix issue with BFD manifest timestamp

- .github/workflows/ci-build-test.yml
- .github/workflows/deploy.yml
- build.gradle
- src/main/java/org/mitre/synthea/helpers/RandomCodeGenerator.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/CodeResolveAndExportTest.java
- src/test/java/org/mitre/synthea/export/ValueSetCodeResolverTest.java
- src/test/java/org/mitre/synthea/helpers/RandomCodeGeneratorTest.java
- src/test/resources/generic/imaging_study_with_valueset.json
- src/test/resources/wiremock/ValueSetCodeResolverTest/mappings/fhir_valueset_expand-9c08a2a2-d391-4571-a1b2-2fe88c6079d4.json
This PR bumps dependencies to eliminate some transitive dependencies on libraries with known vulnerabilities. It also eliminates the dependency on the Spring Framework (!) which was being used solely for its HTTP client. That has now been replaced by OkHttp, which was already a transitive dependency.
An update to the library that is used for URL validation started flagging URLs being constructed for value set expansions. This was fixed by URI encoding some of the characters in the URL, but this should be checked more closely.
This PR bumps the minimum version of Java required to run Synthea to Java 11. This is required to use hapi 6.x.
There are still known issues that will require deeper code changes to fix:
* Physiology - `cql-engine` and `cql-to-elm` both have vulnerabilities, but the …
> Dependency bumps

- .github/workflows/ci-build-test.yml
- .github/workflows/deploy.yml
- build.gradle
- src/main/java/org/mitre/synthea/helpers/ExpressionProcessor.java
- src/main/java/org/mitre/synthea/helpers/RandomCodeGenerator.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/CodeResolveAndExportTest.java
- src/test/java/org/mitre/synthea/export/ValueSetCodeResolverTest.java
- src/test/java/org/mitre/synthea/helpers/RandomCodeGeneratorTest.java
- src/test/resources/generic/imaging_study_with_valueset.json
- src/test/resources/wiremock/ValueSetCodeResolverTest/mappings/fhir_valueset_expand-9c08a2a2-d391-4571-a1b2-2fe88c6079d4.json
This PR updates dependencies to the latest CQL libraries. The CQL that gets generated has been updated to reflect a change in the way that contexts work in CQL. Finally, there was a minor code change to handle an API difference in reading CQL.
This should be merged after #1144.
> Bump CQL dependencies

- .gitignore
- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/helpers/ConsolidatedServicePeriods.java
- src/main/java/org/mitre/synthea/world/concepts/Claim.java
- src/main/resources/export/bfd_field_values.tsv
- src/main/resources/modules/snf/skilled_nursing_facility.json
- src/test/java/org/mitre/synthea/export/BB2RIFExporterTest.java
- src/test/java/org/mitre/synthea/helpers/ConsolidatedServicePeriodsTest.java
- src/test/java/org/mitre/synthea/helpers/ConsolodatedServicePeriodsTest.java
Note that there are three new mapping files (available on the file share) utilized by this PR.
1. Fix a bug where all procedures would happen in one day
2. Reduce probability of various procedures during SNF stay
3. RIF revenue center codes are now mapped from procedure codes
4. Update BFD RIF SNF exporter so that claim lines without HCPCS codes are not skipped (matches real data)
5. Add mappings to SNF PPS and PDPM codes to better match real data
6. Centralize logic that determines which events map to which BFD RIF claim files
> Various updates to BFD RIF SNF and HHA exports

- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/export/CPCDSExporter.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/geography/CMSStateCodeMapper.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/world/geography/LocationTest.java
- Update CSV exporter to include patient FIPS county code and more frequently populate the zip code.
- Addresses #1124 
- Fixes SSA County code default value (the default was `22090`)  to try county name matching or picking a county within the correct state.
- Before this fix, approximately 200+ county codes would be the default in 10,000.
- With just county name looked up, usage of the default code drops from ~200+ to ~30 in 10,000.
- The last ~30 or so now default to a random county in the correct state.
> FIPS County (CSV Exporter) and SSA County (RIF Exporter)

- .lift.toml
- src/test/java/org/mitre/synthea/export/BB2RIFExporterTest.java
- src/test/resources/module/hearing.json
Modify RIF tests so there are always DME claims.
- Adds a hearing aid module for only the unit tests.
- Adds a mock DME mapper class to ensure the hearing aid claim is exported regardless of the presence of mapping files.
- Ignore sonatype-lift complaints about "God Classes" -- we hear you, now go away.
> Modify RIF tests so there are always DME claims.

- src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/resources/modules/copd.json
- src/main/resources/modules/dme/wheelchair.json
- src/main/resources/modules/dme/wheelchair_end.json
- src/main/resources/modules/encounter/fall_risk_screening.json
- src/main/resources/modules/hospice_treatment.json
- src/main/resources/modules/injuries.json
- src/main/resources/modules/metabolic_syndrome/dme_supplies.json
- src/main/resources/modules/metabolic_syndrome_care.json
- src/main/resources/modules/osteoarthritis.json
- src/main/resources/modules/sleep_apnea.json
- src/main/resources/modules/snf/skilled_nursing_facility.json
- src/main/resources/modules/total_joint_replacement.json
Adjustments to DME Data Ratios; see #1150.
The following adjustments are approximations based on observed claims data:
- Adds DME states back into metabolic syndrome care module.
- Blood glucose monitors, calibration solution, testing strips, lancets.
- Adds Oxygen concentrators and portable concentrators into COPD with "DeviceEnd" states.
- Adds additional DME supplies to Sleep Apnea, regular supplies at Wellness visits, and device replacement every 5 years.
- masks, respiratory humidifiers, air filters, tubing
- Skilled nursing facility
- wheelchairs
- Added crutches and wheelchairs for broken ankles and hips.
- Added osteoporosis as a fall risk.
- Assign wheelchair or walker for osteoarthritis
- Total joint replacement resolves DME for 99%
- Assigns wheelchairs for some COPD patients …
> DME Data Ratio Changes

- build.gradle
Switch current uberJar method to use shadowJar plug-in instead of manual assembly
Fixes #1180.
Retains the `uberJar` task (just calls shadowJar) but that could be dropped if we edit the GitHub actions file to use the `shadowJar` task instead.
> Fix log4j Error in uberJar

- build.gradle
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
Addresses #1104
Adds new config settings to support filtering the resource types that are exported in the FHIR exporter, by either an include list or exclude list. (Similar to the existing feature for CSVs)
This approach checks each resource type before instantiating the relevant HAPI resource class.
A few notes on current status:
- this leaves the Patient and Encounter resources as always included, even if specifically excluded, primarily because of the number of changes it would require.  
- this doesn't currently attempt to be "friendly" and include related resources, for example a DiagnosticReport will reference Observations, but if you include DiagnosticReport without including Observation, you will get a DiagnosticReport with no outgoing references. 
- this is only FHIR R4, but I'd …
> FHIR export resource type filter

- .github/workflows/ci-build-test.yml
I noticed a while ago that our internal slack notification hasn't reported build failures in a long time. This was because of my previous PR #920 where I had changed the logic to not run if there was no slack webhook url configured (so that it wouldn't fail 100% of the time on forks). But removing the `always()` meant that if a previous step failed, it wouldn't run the slack notification step.
The correct logic should be to combine both the `always()` check and the slack webhook url check
> Restore slack notifications on failed builds

- .gitignore
- build.gradle
- src/main/java/org/mitre/synthea/export/rif/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/export/rif/ConsolidatedClaimLines.java
- src/main/java/org/mitre/synthea/export/rif/HospiceExporter.java
- src/main/java/org/mitre/synthea/export/rif/SNFExporter.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- Break up RIF `HospiceExporter.export` function to make the flow clearer
- Break up RIF `SNFExporter.export` function to make the flow clearer
- Add claim line consolidation to Hospice export to reduce the number of claim lines per claim
- Fix deprecation warning re `new Double(0.0)`
- Fix gradle deprecation warning re dependency version fixing
Note: requires new hospice_rev_cntr_code_map.json file available from the usual places.
> RIF Hospice Consolidation

- src/main/java/org/mitre/synthea/engine/Distribution.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/resources/modules/anemia/anemia_sub.json
- src/main/resources/modules/breast_cancer.json
- src/main/resources/modules/cystic_fibrosis.json
- src/main/resources/modules/home_hospice_snf.json
- src/main/resources/modules/hospice_treatment.json
- src/main/resources/modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json
- src/main/resources/modules/snf/skilled_nursing_facility.json
- src/test/java/org/mitre/synthea/engine/DistributionTest.java
This pull request adds the [exponential distribution](https://en.wikipedia.org/wiki/Exponential_distribution) [Wikipedia] to the list of available distributions.
This distribution can be used for determining "length of stay", for instance.
Addresses #1168 for the purposes of #1169, #1170, #1171
> Add exponential distribution for Length of Stay

- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/rif/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/export/rif/CarrierExporter.java
- src/main/java/org/mitre/synthea/export/rif/CodeMapper.java
- src/main/java/org/mitre/synthea/export/rif/DMEExporter.java
- src/main/java/org/mitre/synthea/export/rif/HHAExporter.java
- src/main/java/org/mitre/synthea/export/rif/HospiceExporter.java
- src/main/java/org/mitre/synthea/export/rif/InpatientExporter.java
- src/main/java/org/mitre/synthea/export/rif/OutpatientExporter.java
- src/main/java/org/mitre/synthea/export/rif/PDEExporter.java
- src/main/java/org/mitre/synthea/export/rif/RIFExporter.java
- src/main/java/org/mitre/synthea/export/rif/SNFExporter.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/export/rif/BB2RIFExporterTest.java
- src/test/java/org/mitre/synthea/export/rif/CodeMapperTest.java
Track Synthea codes that can't be mapped to a suitable BFD code and export a CSV report with: map file, code, code description, and number of times the code was requested.
> BFD missing code map report

- src/main/java/Graphviz.java
- src/main/java/org/mitre/synthea/engine/Transition.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/main/java/org/mitre/synthea/modules/covid/C19VaccineAgeDistributions.java
- src/main/java/org/mitre/synthea/world/agents/PayerManager.java
- src/main/java/org/mitre/synthea/world/agents/Provider.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/IncomeSpenddownEligibility.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/PlanEligibilityFinder.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/PovertyMultiplierFileEligibility.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/QualifyingAttributesEligibility.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/QualifyingConditionCodesEligibility.java
- src/main/java/org/mitre/synthea/world/concepts/BirthStatistics.java
- src/main/java/org/mitre/synthea/world/concepts/Costs.java
- src/main/java/org/mitre/synthea/world/geography/Demographics.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/world/geography/LocationTest.java
Addresses #1224 
As of today we have a number of config settings which implicitly point to locations under `src/main/resources`, but there's no technical reason they necessarily have to. But as shown in the linked issue, if you try to point to an absolute file path somewhere else, it doesn't work.
This PR refactors the `Utilities.readResource` family of methods into 4:
`Utilities.readResource(String, boolean, boolean)`:
Method containing all the logic and configurability. Allow for optionally reading from different locations and optionally stripping BOM.
`Utilities.readResource(String)`:
Default method to match the previous implementation, calls the above with the options set to false.
`Utilities.readResourceOrPath(String)`:
Method to allow for reading from either src/main/resources, or …
> Allow config settings that are usually in resources to reference any file location

- build.gradle
- src/main/java/org/mitre/synthea/export/rif/tools/BB2RIFBeneSplitter.java
Add new gradle task to split original 3 file BFD bene export into one bene file per year.
Usage: `./gradlew rifBeneSplit -Pargs="inputDir"`
Split files will be written to the same directory. The splitter will work either before or after conversion from BFD RIF to CCW RIF.
> RIF Bene File Splitter

- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/ExportHelper.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterR4.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/HospitalExporterR4.java
- src/main/java/org/mitre/synthea/modules/covid/C19Vaccine.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planfinder/PlanFinderPriority.java
- src/main/java/org/mitre/synthea/world/concepts/Claim.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/java/org/mitre/synthea/world/concepts/healthinsurance/InsurancePlan.java
- src/test/java/org/mitre/synthea/export/FHIRR4ExporterTest.java
Addresses #1236 and fixes some instances where running the same population multiple times produces different results
Issues identified and fixed so far:
1. The ordering of allergy reactions
2. DocumentReference content and Insurance plan selection
(Essentially both of these are the result of using Sets where order is not guaranteed. The current fix is not ideal, it does some extra sorting at the end, so there may be a more "root" fix further upstream. Note that I was not able to reproduce this second issue when running with only a single thread, which also suggests to me further analysis is required)
3. Resource UUIDs are occasionally different
This is because the UUIDs are generated using the same random number generator as used during generation. When the simulation is re-run with a …
> Reproducibility fixes

- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/engine/State.java
- src/main/java/org/mitre/synthea/export/rif/BB2RIFExporter.java
- src/main/java/org/mitre/synthea/modules/DeathModule.java
- src/main/java/org/mitre/synthea/modules/EncounterModule.java
- src/main/java/org/mitre/synthea/modules/covid/C19ImmunizationModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/DefaultPlanEligibility.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/PlanEligibilityFinder.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/resources/modules/cerebral_palsy.json
- src/main/resources/modules/heart/cabg_sequence.json
- src/main/resources/modules/sepsis.json
- src/main/resources/modules/vhd_aortic.json
- src/test/java/org/mitre/synthea/TestHelper.java
- src/test/java/org/mitre/synthea/engine/LogicTest.java
- src/test/java/org/mitre/synthea/engine/LookupTableTransitionTest.java
- src/test/java/org/mitre/synthea/engine/StateTest.java
- src/test/java/org/mitre/synthea/export/JSONExporterTest.java
- src/test/java/org/mitre/synthea/export/rif/BB2RIFExporterTest.java
- src/test/java/org/mitre/synthea/helpers/TransitionMetricsTest.java
- src/test/java/org/mitre/synthea/modules/QualityOfLifeTest.java
- src/test/java/org/mitre/synthea/modules/covid/C19ImmunizationModuleTest.java
- src/test/java/org/mitre/synthea/world/agents/PayerTest.java
- src/test/java/org/mitre/synthea/world/concepts/CostsTest.java
- src/test/java/org/mitre/synthea/world/concepts/HealthRecordTest.java
- src/test/resources/generic/example_module.json
This pull request fixes Encounter Leaks as described in #1221.
With these changes, modules must now "reserve" the "current encounter" and "release" it when finished.
Modules that do not have the current encounter are blocked from starting new encounters. Wellness encounters are still an exception.
This fix also adjusts how submodules are called and tracked. A submodule may impersonate or disguise itself as a parent top-level module in order to interact with the current encounter. It does this by saying it is the parent top-level module when it is asked for its name.
> Fix Encounter Leaks

- src/main/java/org/mitre/synthea/export/CPCDSExporter.java
- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4PatientHome.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/resources/templates/ccda/allergies.ftl
- src/main/resources/templates/ccda/conditions.ftl
- src/main/resources/templates/ccda/encounters.ftl
- src/main/resources/templates/ccda/functional_status.ftl
- src/main/resources/templates/ccda/immunizations.ftl
- src/main/resources/templates/ccda/medical_equipment.ftl
- src/main/resources/templates/ccda/medications.ftl
- src/main/resources/templates/ccda/procedures.ftl
- src/main/resources/templates/ccda/results.ftl
- src/main/resources/templates/ccda/social_history.ftl
- src/main/resources/templates/ccda/vital_signs.ftl
This PR completes the "reproducibility fixes" from #1237 - that PR updated the FHIR R4 exporter, this PR updates all other exporters that use UUIDs. Now instead of using Person.randUUID, the exporters use the uuid from the relevant entry where possible. In only a few instances this doesn't work out super cleanly, and there are spots where the UUIDs may differ in some cases.
Here are the (intentional) exceptions:
- CSV Exporter, claim_transactions.csv
- The CSV exporter uses a monotonically increasing value for "ChargeID" which is shared across all patients. If Synthea is run with only a single thread and all the same settings, 2 runs will be exactly identical. If the run uses multithreading, then the order of exports will be different, and different entries in this file will receive …
> UUID recreation on other exporters

- .github/workflows/ci-build-test.yml
- .github/workflows/deploy.yml
Update the versions of the actions used in our CI to address some of the deprecation warnings. 
For example see https://github.com/synthetichealth/synthea/actions/runs/4117160673  
If you dig into the log https://github.com/synthetichealth/synthea/actions/runs/4117160673/jobs/7108119437  you can see that the deprecation warnings come from the steps "Set up JDK" and "Gradle cache".
The only difference beyond just version numbers is we now need to specify a java distribution to use:
https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md  
`'zulu'` was the implicit default previously so I stuck with that here.
> Update CI action versions

- .github/workflows/deploy.yml
Bumps the delete-tag-and-release action up to 0.2.1. Apparently the repo owner deleted all previous releases (intentionally) when pushing v0.2.1.
> Bump github action version on Deploy

- src/main/resources/templates/notes/note.ftl
Fixes hispanic ethnicity display in clinical notes.
Previously, the template improperly printed "non-hispanic" in cases even when the patient was hispanic, because the lookup was based on the weird US Core terminology code systems.
Now, the raw attribute value of "hispanic" or "nonhispanic" is printed.
Results were validated by comparing with `patients.csv` output.
> Fix ethnicity display in clinical notes.

- src/main/java/App.java
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/test/java/org/mitre/synthea/engine/LogicTest.java
- src/test/java/org/mitre/synthea/modules/covid/C19ImmunizationModuleTest.java
- src/test/java/org/mitre/synthea/world/agents/PersonTest.java
Fixes two additional instances where running with the same settings may produce different results, and adds a new feature to assist in debugging.
1. Fixes the issue seen here: https://github.com/synthetichealth/synthea/issues/1236#issuecomment-1442152946 where the records were identical up to a point, then diverged. The issue appears to be with age calculation, specifically if you're unlucky a person's age in months can be different for a given timestep based on the time zone. The change here makes it so that all age calculations are done in UTC. (This does introduce the possibility of age-based events happening up to 12 hours before they would be expected to, or one full timestep later, but in context I don't think that's a big deal)
While there I also cached the birthdate as a LocalDate …
> Additional reproducibility fixes, plus a "single person seed" feature

- src/main/java/org/mitre/synthea/modules/LifecycleModule.java
- src/main/java/org/mitre/synthea/world/agents/Person.java
- src/main/java/org/mitre/synthea/world/concepts/Employment.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/main/resources/modules/encounter/sdoh_hrsn.json
- src/test/java/org/mitre/synthea/world/concepts/EmploymentTest.java
This PR contains fixes for the SDoH HRSN submodule as well as a new model of unemployment.
Previously, people in Synthea would be selected to be unemployed for their whole life in the simulation.
With this change, people will have a chance to become unemployed based on the unemployment rate for their county. Unemployment status is checked every 6 months.
This addresses #1272
> Unemployment enhancements

- src/main/java/org/mitre/synthea/export/rif/DMEExporter.java
- src/main/java/org/mitre/synthea/export/rif/HospiceExporter.java
- src/main/java/org/mitre/synthea/export/rif/InpatientExporter.java
- src/main/java/org/mitre/synthea/export/rif/OutpatientExporter.java
- src/main/java/org/mitre/synthea/export/rif/RIFExporter.java
- src/main/java/org/mitre/synthea/export/rif/SNFExporter.java
- src/test/java/org/mitre/synthea/export/rif/BB2RIFExporterTest.java
1. Update BFD inpatient exporter to ensure line item totals match claim totals
2. Update BFD outpatient exporter to ensure line item totals match claim totals
3. Pull common code for inpatient and outpatient exporter up in RIFExporter base class
4. Add tests for BFD HHA exporter to ensure line item totals match claim totals
5. Update BFD SNF exporter to ensure line item totals match claim totals
6. Update BFD Hospice exporter to ensure line item totals match claim totals
>  BFD Exporter Updates

- src/main/java/org/mitre/synthea/export/CSVExporter.java
Hi,
claims, exported as CSV, contains both, according to the wiki, a Primary Patient Insurance ID and a Secondary Patient Insurance ID of type UUID. However, the code produces 0, if no Payer exists. 0 is not a valid UUID and hence we are unable to import the exported CSV files into a PostgreSQL database.
In case of no Payer exists, I suggest to generate nothing (NULL in SQL speak) instead of 0.
> Claims CSV contains invalid uuids

- src/main/java/org/mitre/synthea/export/rif/PDEExporter.java
First pass at improving the prescription drug event patient residence codes.
The decision of which residence code is selected is based on the encounter class, and sometimes patient homelessness status.
Prior to this change, something like 99.99% of the codes were `01 - home` and an exceptionally small number were `14 - homeless`.
The following table shows the results after the change, and was based on 10K synthetic patients using `--generate.providers.selection_behavior=medicare` and `-a 65-80` 
PTNT_RSDNC_CD | Display | SYNTHETIC % | REAL % | DELTA
-- | -- | -- | -- | --
01 | home | 0.873368 | 0.802164 | +0.071204
00 | not specified | 0.085420 | 0.073489 | +0.011931
04 | assisted living | 0.040491 | 0.039337 | +0.001154
13 | inpatient rehab | 0.000577 | 0.000001 | +0.000576
11 | hospice …
> Adjust patient residence codes.

- src/main/java/org/mitre/synthea/export/CCDAExporter.java
- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirGroupExporterR4.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterDstu2.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterR4.java
- src/main/java/org/mitre/synthea/export/FhirPractitionerExporterStu3.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/export/HospitalExporterDstu2.java
- src/main/java/org/mitre/synthea/export/HospitalExporterR4.java
- src/main/java/org/mitre/synthea/export/HospitalExporterStu3.java
- src/main/java/org/mitre/synthea/export/JSONExporter.java
- src/main/resources/synthea.properties
The following exporters will now use the `exporter.pretty_print` configuration setting:
- FHIR (all versions)
- Pretty printing settings are ignored when using `exporter.fhir.bulk_data` 
- CCDA
- JSON
The savings in C-CDA file size is low, only around 2% smaller.
The savings in FHIR file size can be quite large, approximately 33% smaller in most cases.
> Configuration option to disable pretty printing for XML and JSON

- src/main/resources/modules/encounter/sdoh_hrsn.json
Fixes the PRAPARE SDOH module so that the "Address" observation has a category of `survey` instead of `laboratory`.
> Fix SDOH address category.

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Bump the gradle wrapper version to 8.2.1 (latest as of July 10, 2023 - https://gradle.org/releases/)
This will enable support up through JDK 20 yet. (Note JDK 21 LTS is also right around the corner.) (An earlier version of this said JDK 20 was not yet supported, that was a mistake I'm not sure why I thought that)
Gradle/JDK compatibility is described here: https://docs.gradle.org/current/userguide/compatibility.html
Also see the JDK support matrix at https://endoflife.date/java
The changes to build.gradle are required to get past some errors, I guess they changed the gradle DSL:
```
* What went wrong:
A problem occurred evaluating root project 'synthea'.
> Could not find method classifier() for arguments [sources] on task ':sourceJar' of type org.gradle.api.tasks.bundling.Jar.
```
I …
> Bump gradle wrapper version to 8.2.1

- build.gradle
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/export/PatientExporter.java
- src/main/java/org/mitre/synthea/export/PostCompletionExporter.java
- src/main/resources/synthea.properties
This is a proof of concept for supporting drop-in custom exporters.
This approach takes advantage of the [Java ServiceLoader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) to load in JARs containing classes that implement a certain interface. I've defined two interfaces here, PatientExporter and PostCompletionExporter. (The existing exporters weren't modified here but they could easily extend these interfaces as well)
A template for building a custom exporter is here: https://github.com/dehall/custom-exporter-template
And an example Postgres loader which loads Patient basic info and Conditions into simple tables: https://github.com/dehall/example-exporter-postgres
(Documentation is limited on those new repos, apologies)
Note this has not yet been tested with the …
> Custom Exporters

- src/main/java/org/mitre/synthea/export/ExportHelper.java
ExportHelper originally used SimpleDateFormat, which is not thread-safe. Hence access to the static DATE_FORMAT and ISO_DATE_FORMAT had to be protected using `synchronized`, as noted in the original code.
This synchronized access is especially visible on higher end machines. For example on a VM with 48 vCPUs, a `jstack -l` output analysis showed almost 50% of the pool threads were waiting on the static `ISO_DATE_FORMAT` instance within ExportHelper. On such machines, CPU usage would be low and Synthea's throughput was not scaling well with higher number of vCPUs.
This change safely replaces those usage of SimpleDateFormat with FastDateFormat, which is thread-safe, thereby removing the need to synchronize access to those static instances across threads. The result of this is better …
> Replace SimpleDateFormat with FastDateFormat in ExportHelper

- src/main/java/org/mitre/synthea/world/geography/Location.java
- src/test/java/org/mitre/synthea/world/geography/LocationTest.java
The simulation expects every person to have an employment model set in their attributes. If a person was generated an a county where the `sdoh.csv` file did not have a row, the employment model would not get set. This change uses the state average information when the desired county can not be found.
This PR addresses Pattern 2 as described in #1380.
> Fix issues with NPEs related to the employment module

- src/main/java/org/mitre/synthea/world/concepts/GrowthChartEntry.java
- src/test/java/org/mitre/synthea/modules/GrowthChartTest.java
- src/test/java/org/mitre/synthea/world/concepts/GrowthChartTest.java
Synthea's simulation of height and weight under the age of 20 depends on growth charts published by CDC. The growth charts are [provided with a method](https://www.cdc.gov/growthcharts/percentile_data_files.htm) for transforming values into percentiles and vice-versa. It appears that for higher percentiles, this method can break down. 
The case that was used for testing this issue is transforming the ~99.74th percentile BMI for females at 240 months into an actual BMI value. 
This code change addresses the issue by converting any request above the 99.5th percentile to just the 99.5th percentile.
This addresses #1372.
> Fix issue where vital signs were sometimes being set to `NaN`

- src/main/java/org/mitre/synthea/export/Exporter.java
- src/test/java/org/mitre/synthea/export/ExporterTest.java
Fixes #1383 
This PR addresses an issue where the export filter isn't filtering out old entries when there is a separate active entry of the same "type", ie, code. This is especially likely to happen with "Medication Review Due" from the Med Rec module, but it could also happen for any potentially-recurring entry such as Viral Sinusitis or chronic medications.
The issue is that the logic is using `record.conditionActive` which only checks whether the given code is in the "active" set, it doesn't look at the specific entry at all. The change here is to only look at dates, and the date logic can be pretty simple: "if the entry is open (stop = 0) or the stop is after the cutoff, keep the entry"
> Fix export filter keeping old entries when there is an active entry of the same type

- .github/workflows/deploy.yml
The deploy workflow with "autogenerate sample data" failed because the job runner ran out of disk space. This change deletes the uncompressed records (1k each of FHIR R4, STU3, DSTU2, CCDA, and CSV, so it's a lot) to save space.
Note, I made the change in the workflow instead of the generate_samples script because I don't want someone to run that script and accidentally delete data they want, and I put that step first so we could `rm ./output` without having to specify all the different subfolders and without affecting the javadoc folder.
> Delete uncompressed sample data in deploy workflow

- src/main/resources/modules/heart/avrr/avrr_referral.json
- src/main/resources/modules/heart/avrr/sequence.json
- src/main/resources/modules/heart/cabg/cabg_referral.json
- src/main/resources/modules/heart/cabg_sequence.json
This PR addresses Pattern 1 as reported in #1380. It makes sure that this issue should not happen, but there is still a likely underlying issue in Synthea. Whether it is worth addressing is up for debate.
The NPE in the bug report happens when the person in the simulation is going through the AVRr Referral submodule in the Myocardial Infarction module. When looking at the debugger for the case in question, `Module` is on the state `Priority_4_Next_Encounter_2` and trying to transition to the state `Valve Surgery`. However, `Module` is in the context of the **CABG** Referral submodule. When it tries to find the `Valve Surgery` state, it isn't there.
This is likely due to both the CABG and AVRr submodules being called `referral`. This PR renames them so that they both have unique names. …
> Fix for NPE seen when sometimes trying to clone the next state

- src/main/resources/modules/appendicitis.json
- src/main/resources/modules/covid19/end_outcomes.json
- src/main/resources/modules/home_health_treatment.json
- src/main/resources/modules/home_hospice_snf.json
- src/main/resources/modules/metabolic_syndrome_care.json
- src/main/resources/modules/opioid_addiction.json
- src/main/resources/modules/pregnancy.json
- src/main/resources/modules/snf/skilled_nursing_facility.json
- src/main/resources/modules/total_joint_replacement.json
This PR cleans up a few items that pop up pretty often in generated records and look odd:
1. There are several ConditionOnsets that do not have a corresponding ConditionEnd and are left open forever, even though they are acute conditions which are addressed in the module:
- Appendicitis & rupture of appendix
- Opioid addiction: Drug overdose (note there are a few other conditions in this module which don't get ended, like "Impacted molars", "Chronic pain", and migraine, which are not really treated so I'm ok leaving them open)
- Miscarriage (added a "history of miscarriage" condition)
- Covid19 outcomes: Hypoxemia (seems like this was just missed in the long list of conditions, I don't see anything in the old notes for why this one specifically should stay open)
2. Prediabetes can be …
> Module cleanup

- src/main/java/App.java
- src/main/java/org/mitre/synthea/export/flexporter/Actions.java
- src/main/resources/modules/heart/acs_discharge_meds.json
- src/test/resources/flexporter/qicore_withnotdone.yaml
This PR adds a few enhancements identified when trying to create "Not Done" type resources for QICore. (Ex, Medication Not Requested https://build.fhir.org/ig/HL7/fhir-qi-core/StructureDefinition-qicore-medicationnotrequested.html )
- Disables the annoying warning the flexporter introduced. For a single patient it wasn't that big a deal but for larger populations it made it impossible to follow the output.
- Adds a "fullUrl" field to the Bundle entry on any created resources
- When creating resources based on a given state, adds the ability to reference the Encounter that was active at that time
- Adds a specific "No Aspirin" state to the ACS Discharge Meds submodule for the flexporter to key off of for this example. We may want to make it a "best practice" to have an actual empty …
> Flexporter enhancements

- src/main/javascript/update_code_display.js
- src/main/resources/modules/cerebral_palsy.json
- src/main/resources/modules/congestive_heart_failure.json
- src/main/resources/modules/heart/avrr/preoperative.json
- src/main/resources/modules/heart/avrr/savrr_postop.json
- src/main/resources/modules/heart/tavr/alt_access.json
- src/main/resources/modules/heart/tavr/postop.json
- src/main/resources/modules/hiv/hiv_screening.json
- src/main/resources/modules/spina_bifida.json
- src/main/resources/modules/uti/gu_pregnancy_check.json
This PR introduces a new script to automatically update code displays when they do not match the preferred value for the code system. Originally I intended this process to be part of the Concepts java class, but writing changes back to the JSON file would have involved too much refactoring so instead I created a new JavaScript ... script.
To try to minimize the number of display changes, and standardize code displays across modules, this script takes a 2-pass approach:
1. Iterate over all the modules and keep an inventory of the codes/displays
2. Fetch the preferred display for each code. Keep a dictionary of code -> display
i. If a module already uses the preferred display somewhere, store that
ii. If the current display is allowed but not necessarily the preferred, store that (to reduce …
> New script to update code displays

- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
- src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
- src/main/javascript/update_code_display.js
- src/main/resources/modules/encounter/depression_screening.json
- src/main/resources/modules/encounter/sdoh_hrsn.json
- src/main/resources/modules/heart/avrr/outcomes.json
- src/main/resources/modules/heart/avrr/sequence.json
- src/main/resources/modules/heart/cabg/outcomes.json
- src/main/resources/modules/heart/tavr/outcomes.json
- src/main/resources/modules/injuries.json
- src/main/resources/modules/self_harm.json
- src/main/resources/modules/snf/skilled_nursing_facility.json
- src/main/resources/modules/veteran_self_harm.json
Addresses #1430
For the most part, the SNOMED codes we use come from the International edition, but there are a few that are US-specific. This causes errors when validating generated resources that use these code, because if the resource doesn't specify the version, the validator/tx server will assume the international edition.
This PR adds a `version` field to our HealthRecord.code model which allows the version to be specified, and updates the codes that currently cause errors. The new version field is optional since it's only really relevant to half a dozen codes. See corresponding PR on the module builder: https://github.com/synthetichealth/module-builder/pull/330
Codes that were changed:
5251000175109 -- the one from the linked issue, added US version flag
784051000000106 -- …
> Add support for code system versions

- src/main/java/org/mitre/synthea/export/flexporter/Actions.java
- src/main/java/org/mitre/synthea/export/flexporter/CustomFHIRPathResourceGeneratorR4.java
- src/test/java/org/mitre/synthea/export/flexporter/ActionsTest.java
- src/test/java/org/mitre/synthea/export/flexporter/CustomFHIRPathResourceGeneratorR4Test.java
- src/test/resources/flexporter/test_mapping.yaml
This PR adds better handling of lists in the flexporter. Currently as seen in #1421, adding multiple items to a list requires awkward "where" syntax which won't be apparent to users. This PR enables a couple options that should be more intuitive.
These 3 actions should now produce equivalent results (though the ordering of the items in the first instance is not guaranteed)
```yaml
- name: testSetValues_where
set_values:
- applicability: Encounter 
fields: 
- location: Encounter.serviceType.coding.where(code='229')
value: 
system: http://terminology.hl7.org/CodeSystem/service-type
- location: Encounter.serviceType.coding.where(code='355')
value: 
system: http://terminology.hl7.org/CodeSystem/service-type
- name: testSetValues_indexed
set_values:
- applicability: Encounter 
fields: 
- …
```
> Better handling of lists in Flexporter

- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/engine/Module.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/helpers/TransitionMetrics.java
- src/test/java/AppTest.java
- src/test/java/org/mitre/synthea/engine/GeneratorTest.java
- src/test/java/org/mitre/synthea/helpers/TransitionMetricsTest.java
This branch revamps the module, state, and transition metrics.
Previously, use of the `generate.track_detailed_transition_metrics` property outputted metrics to system out. Using this feature roughly quadrupled the runtime.
This change outputs the metrics as JSON (`./output/metrics/**`), one file per module. Using this feature will roughly double the runtime.
Sample output looks something like this for each state, where the name of the state (e.g., `Chance_of_Stroke` matches a state name in the corresponding GMF module):
```json
"Chance_of_Stroke": {
"entered": 58987,
"duration": 152635104000000,
"population": 101,
"current": 100,
"destinations": {
"Stroke": 1,
"Chance_of_Stroke": 58886
}
}
```
Field | Description
-----|-----
`entered` | Count, how many times this state was entered. …
> Module Metrics

- src/main/java/org/mitre/synthea/export/CSVExporter.java
added feature which completes issue #1326, middle name is now included in patients.csv
testing: ran all test cases provided
> Middle Name added to patients.csv

- src/test/resources/module/test_hha.json
This PR cherry-picks a commit from the dental branch to fix an intermittent unit test failure, where a test may or may not have a home health visit. This test module fixes that issue.
- `Add testing module to ensure HHA visits for RIF unit tests.`
> Unit Test Fix

- src/main/resources/modules/sepsis.json
Fix for the US Core Pulse Ox error:
> Validation of exported FHIR bundle failed: Observation.code.coding:PulseOx: minimum required = 1, but only found 0 (from http://hl7.org/fhir/us/core/StructureDefinition/us-core-pulse-oximetry)
That profile requires both these two codes
Tested out locally with the below change to ensure all patients went through the sepsis module:
```diff
--- a/src/main/resources/modules/sepsis.json
+++ b/src/main/resources/modules/sepsis.json
@@ -16,7 +16,7 @@
"states": {
"Initial": {
"type": "Initial",
-      "direct_transition": "Age_Guard"
+      "direct_transition": "Sepsis"
},
```
> Quick Fix for US Core Pulse Ox error

- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/resources/synthea.properties
@jawalonoski something along these lines correct? (in relation to https://chat.fhir.org/#narrow/stream/179166-implementers/topic/From.20Synthea.20Bulk.20Export.20to.20Bulk.20Import)
> Added feature for generating the parameters file

- src/main/java/App.java
- src/main/java/org/mitre/synthea/export/Exporter.java
This addresses an issue where certain config settings, ie `exporter.years_of_history` don't work when set via the command line args.
I think we've seen a few times and have put fixes on various branches: https://github.com/synthetichealth/synthea/pull/1357/commits/d10d07e8f4c2dff820da8b2c5f4ef7f0f564b725 , https://github.com/synthetichealth/synthea/commit/d0e43719ea54573a6ad4a5050ace749f8490d336#diff-a6b8b70e408cd3e34b8db02476445bfd607cad475dd9e80a5b62bc82c583b3b2
This is still a bandage though and we'll probably run into this again, but it should work as a quick fix. The longer andmore permanent fix would be to keep separate variables for the things the cli args can set, and only instantiate the 2 Options objects after all args have been parsed.
Fixes #1476
> Fix issue with setting config via CLI

- src/main/java/org/mitre/synthea/export/flexporter/Actions.java
Fixes an issue with the flexporter where mappings that use `execute_script` export files without ids on the resources.
Resets ids by searching for and removing `urn:uuid:`. Now flexporter run appropriately exports resources with ids when executing a script during mapping.
Copies code from [line 151 of RunFlexporter.java](https://github.com/synthetichealth/synthea/blob/055d977ec40f52cd5d386395297930241ad4e34c/src/main/java/RunFlexporter.java#L151) which is used to fix an issue with HAPI ids. (Thanks for the fix @dehall!)
Run the synthea flexporter with something like `./run_synthea -fm {mapping_file.yaml}` where the mapping file contains some `execute_script` mapping as described in the [flexporter wiki](https://github.com/synthetichealth/synthea/wiki/Flexporter#execute-script). Look at …
> Fix ids for flexporter executeScript

- src/main/java/org/mitre/synthea/export/flexporter/Actions.java
- src/test/java/org/mitre/synthea/export/flexporter/ActionsTest.java
- src/test/resources/flexporter/test_mapping.yaml
A few new features for the flexporter:
1. A new `if` field that can be used in `create_resource` to conditionally set a field. The use case that inspired this is shown in the unit test - creating ServiceRequest based on Procedure, setting ServiceRequest.authoredOn = Procedure.performed, but Procedure.performed is either a dateTime (ie, primitive) or a Period (ie, an object) so the types need different handling. Previously the only way to do this was with two separate actions with different applicability.
2. Allow deleting resources by FHIRPath instead of just by resource type. The use case that inspired this is deleting some of the SDOH conditions to clean up a record for a demo
3. Allow functions to be nested within definitions. Previously a function call such as `getAttribute` could …
> Flexporter updates - October 2024

- src/main/java/App.java
- src/main/java/org/mitre/synthea/engine/Generator.java
- src/main/java/org/mitre/synthea/export/Exporter.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/rif/CodeMapper.java
- src/main/java/org/mitre/synthea/helpers/RandomCollection.java
- src/main/resources/synthea.properties
- src/test/java/org/mitre/synthea/export/rif/CodeMapperTest.java
1. Add support for mapping condition codes to ICD-10-CM in the FHIR R4 exporter.
2. Fix some checkstyle warnings.
> ICD-10-CM Code Mapping

- src/main/resources/modules/hypertension.json
- src/main/resources/modules/metabolic_syndrome_disease.json
This set of module changes is designed to adjust the onset age of hypertension to be more in line with the following studies:
1. Ostchega Y, Fryar CD, Nwankwo T, Nguyen DT. Hypertension prevalence among adults aged 18 and over: United States, 2017–2018. NCHS Data Brief, no 364. Hyattsville, MD: National Center for Health Statistics. 2020.
2. Huang X, Lee K, Wang MC, Shah NS, Khan SS. Age at Diagnosis of Hypertension by Race and Ethnicity in the US From 2011 to 2020. JAMA Cardiol. 2022;7(9):986–987. doi:10.1001/jamacardio.2022.2345
- Age of Hypertension Onset
| Average (years) | Standard Deviation (years) |
|----:|----:|
| 46 | 15 |
- From source [2] above.
The data below was generated using the command `./run_synthea -p 10000` for the Before and After cohorts.
- Age of Hypertension Onset …
> Changes to hypertension onset to better align with statistics.

- src/main/java/App.java
- src/main/java/RunFlexporter.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/flexporter/Actions.java
- src/main/java/org/mitre/synthea/export/flexporter/Mapping.java
- src/main/java/org/mitre/synthea/helpers/RandomCodeGenerator.java
- src/main/java/org/mitre/synthea/helpers/Utilities.java
- src/test/java/org/mitre/synthea/export/flexporter/ActionsTest.java
- src/test/resources/flexporter/test_mapping.yaml
Updates to address flexporter issues identified by @elsaperelli :
1. I realized the `randomCode` function was improperly named since technically it produces a Coding not a code. Rather than rename it and break backwards compatibility, this gives it an optional second parameter for "return type". This can be "code" to return a string, "Coding" to return a Coding (ie `{system, code, display}`), or "CodeableConcept" to return a CodeableConcept. Default if unspecified is Coding, for backwards compatibility.
2. Adds support for defining custom ValueSets in a flexporter mapping file, so that you can select a randomCode from your handpicked set of codes rather than having to use a terminology server and pre-existing VS. The syntax is a YAML version of the ValueSet resource, to minimize inventing …
> Flexporter - Update randomCode fn to take output type as an optional second param

- src/main/java/org/mitre/synthea/world/agents/PayerManager.java
- src/main/java/org/mitre/synthea/world/agents/behaviors/providerfinder/ProviderFinderNearest.java
- src/main/java/org/mitre/synthea/world/concepts/healthinsurance/InsurancePlan.java
- src/main/java/org/mitre/synthea/world/geography/Location.java
This PR adds a few small updates to add defaults for missing data or configuration settings, mostly applicable to synthea-international configurations.
This PR pairs with https://github.com/synthetichealth/synthea-international/pull/20
> Defaults for some missing configuration settings

- src/main/java/org/mitre/synthea/export/FhirDstu2.java
- src/main/java/org/mitre/synthea/export/FhirR4.java
- src/main/java/org/mitre/synthea/export/FhirStu3.java
This PR fixes a discrepancy in how MedicationRequests are created by the synthea R4 export. The previous code was setting the MedicationRequest to STOPPED if the medication has a valid stop value. But looking at the [MedicationRequest status valueset](https://hl7.org/fhir/R4/valueset-medicationrequest-status.html), stopped means:
> Actions implied by the prescription are to be permanently halted, before all of the administrations occurred. This should not be used if the original order was entered in error
Essentially this seems to mean that the request was stopped rather than that the medication itself was stopped. For most synthea modules, the intent is for medication.stop to get set to something other than 0L when the medication is _completed_. As such, we want to set the …
> Set MedicationRequest status to COMPLETE instead of STOPPED

- src/main/java/org/mitre/synthea/export/CSVExporter.java
- src/test/java/org/mitre/synthea/export/CSVExporterTest.java
The `CSVExporter` has been updated to support the simultaneous setting of `included_files` and `excluded_files`. The implementation now includes a check for any overlap between these two lists, raising an error if and only if common elements are found.
Fixes:  https://github.com/synthetichealth/synthea/issues/1560
> Allow included and excluded files in CSV exporter if there is no overlap

- src/main/java/org/mitre/synthea/helpers/DefaultRandomNumberGenerator.java
- src/test/java/org/mitre/synthea/helpers/TransitionMetricsTest.java
Addresses the duplicate UUID issue from #1545 
Our UUID generation uses the seeded random number generator to ensure reproduceability, and picks 2 randLong()s to pass into the UUID constructor. For small populations this works ok but in larger populations we wind up with UUID collisions within the same resource type.
I believe what's happening when we get duplicate UUIDs is we're seeing two separate patients (two separate RNGs with separate seeds) where their RNGs have lined up in terms of state and where they are in that sequence, and so they produce the same 2 long values in a row, resulting in the same UUID. In small populations the range of numbers is so large that collisions are unlikely, but when we get up to say 1,000,000 patients, we start to see a small handful of collisions. By …
> Reduce chances of duplicate uuids in large populations
