synthetichealth/synthea

lib/modules/cardiovascular_disease.rb
Added atrial fibrillation feature into cardiovascular module
=> Cardiovascular

lib/modules/cardiovascular_disease.rb, lib/modules/metabolic_syndrome.rb, lib/modules/module.rb, lib/records/ccda.rb, lib/records/fhir.rb, lib/records/lookup.rb, lib/records/record.rb, test/unit/fhir_test.rb, test/unit/module_test.rb, test/unit/record_test.rb
Refactored some metabolic treatment code to use new medications functions that allow for multiple reasons. Added treatment and medications for cardiovascular diseases.
=> Cardiovascular treatment

synthea.gemspec
this should have been included with the original pr that added multithreading
=> add concurrent-ruby to gemspec

lib/generic/modules/birth.json, lib/generic/modules/pregnancy.json
Initial birth and pregnancy generic models
=> Birth & Pregnancy

config/synthea.yml, lib/modules/cardiovascular_disease.rb, lib/modules/lifecycle.rb, lib/modules/metabolic_syndrome.rb, lib/records/exporter.rb, lib/tasks/tasks.rake, lib/world/sequential.rb, test/unit/exporter_test.rb
Includes a number of minor tweaks, including:
- Makes the medication changes `@@med_changes` field in a couple rules threadsafe by moving it to the entity
- Randomizes birthdates so they occur throughout the year, not all on the same date
- Fixes adult weight gain %s, they were off by a factor of 10
- Moves all export and upload logic to the Exporter class
=> Small fixes

config/synthea.yml, lib/modules/lifecycle.rb, lib/modules/metabolic_syndrome.rb, lib/world/sequential.rb
Adjusted weight gain and loss to be more realistic. Folks gain weight until 49 and start losing weight at age 60. The gain/loss ranges are more dramatic than the citations because we don't account for socioeconomic status or diet yet.
The glucose estimate now gives higher numbers, so diabetes is up around 14% +- 5% per run, which is where it should roughly be for Massachusetts.
=> Adjust weight gain and loss and glucose estimates

lib/generic/modules/injuries.json
The actual injuries model which should have been included in #40
=> injuries model

config/synthea.yml, lib/modules/lifecycle.rb
Just a pull request to make the hash that is added to person names configurable (default is to leave it enabled, but I don't need that for my testing)
=> Make hash on person names configurable

lib/generic/modules/ear_infections.json
Added a module to model ear infections. These primarily occur in children. For now I model treatment with either a standard antibiotic (Amoxicillin) or an over-the-counter (OTC) painkiller.
Some things that could be considered in the future:
* Other antibiotics used for treatment (e.g. Azithromycin, Augmentin)
* Recurring ear infections that eventually lead to ear damage and surgery (or hearing loss)
* Seasonal incidence (they're far more likely in the winter)
=> Added Ear Infection Module

lib/generic/modules/med_rec.json
This module will generate a documentation of current medications procedure at 45% of wellness encounters. Through the Meaningful Use program, ONC is striving for medication reconciliation at 50% of encounters. This assumes that we are not
at the goal level yet.
Source: https://www.healthit.gov/providers-professionals/achieve-meaningful-use/core-measures-2/medication-reconciliation
=> Adding a module for medication reconciliation

lib/generic/logic.rb, lib/generic/states.rb, lib/records/lookup.rb, lib/tasks/graphviz.rb, test/fixtures/generic/careplan_end.json, test/fixtures/generic/careplan_start.json, test/fixtures/generic/logic.json, test/unit/fhir_test.rb, test/unit/generic_logic_test.rb, test/unit/generic_states_test.rb
I added the CarePlanStart and CarePlanEnd states to the GMF, as well as an “Active CarePlan” condition. I added unit tests for these new states and updated the graphviz tests with the new states/condition. I will update the Wiki to reflect these additions as well.
=> CarePlan GMF States

test/unit/fhir_validation_test.rb
Executes 10 random patients and runs FHIR validation on the output of each record. This should capture some edge case errors in execution and validation not covered by specific targeted tests.
=> Execute and validate -- no more invalid resources.

README.md
update the readme with a little more detail on how to get setup
=> update readme install instructions

.gitignore, lib/generic/modules/allergic_rhinitis.json
Also known as “allergic rhinitis”. This is the first GMF module to
implement the new CarePlan states as well.
I added .palate to the gitignore - I keep a small file in my Atom IDE
called .palate with code snippets, for example the JSON for a code
(system, code, display) used in many of the GMF states.
=> Added GMF module for seasonal allergies

lib/generic/context.rb, lib/generic/states.rb
Adds attributes to the GMF states, and logic to the base State constructor such that all properties in the state in the JSON are automatically assigned to the corresponding attribute in the State object. As such we don't have to manually specify `@codes = context.state_config(@name)['codes']` and the like in all the states, and most of the `initialize` methods are redundant.
=> add attributes to states, and logic to automatically assign them

lib/modules/metabolic_syndrome.rb, lib/modules/module.rb, lib/world/sequential.rb
Diabetes drugs now alter the disease progression, especially during the later stages of the disease as the potency of the medications ramp up. I'm getting around 11-14% of the living population as diabetics now, which is about right. I've also modified the sequential task to run until it generates the correct number of living people -- dead people are no longer counted.
=> Diabetes medications now effect the progression of disease.

lib/generic/modules/injuries.json
Missed a couple of minor, un-pushed commits that have the correct incidences and remarks explaining any changes.
=> Injuries fix cleanup

config/synthea.yml, lib/generic/modules/copd.json, lib/modules/cardiovascular_disease.rb
Adds a module for COPD (Chronic Obstructive Pulmonary Disease, #.4 on the GBD YLL Top 10)
Changes smoking % from a fixed 16% to variable by year.
=> COPD module

lib/generic/modules/urinary_tract_infections.json
Created a module to model urinary tract infections. 50% of women will get at least one UTI in their lifetime, with some getting 2 or 3. In rare cases women can also get recurring UTIs that happen every 2-4 months for life. UTIs are rare for males but about 1 in 20 will get 1.
=> Added UTI Module

lib/generic/modules/asthma.json, lib/generic/modules/bronchitis.json, lib/generic/modules/dementia.json, lib/generic/modules/lung_cancer.json, lib/generic/modules/opioid_addiction.json, lib/generic/modules/self_harm.json
Added care plans to the remaining GMF modules where a care plan makes sense. I did not add care plans to modules with short-term infections (like UTIs or ear infections). Instead I focused on long-term issues and chronic conditions. In the case of respiratory illnesses (Bronchitis, Asthma) there are different variants of the care plan for smokers and non-smokers.
=> Added Care Plans to Relevant GMF Modules

lib/generic/modules/attention_deficit_disorder.json
Added childhood ADHD, treated by either behavioral therapy or medication.
=> Added ADHD

lib/generic/modules/allergic_rhinitis.json, lib/generic/modules/appendicitis.json, lib/generic/modules/asthma.json, lib/generic/modules/attention_deficit_disorder.json, lib/generic/modules/bronchitis.json, lib/generic/modules/copd.json, lib/generic/modules/dementia.json, lib/generic/modules/ear_infections.json, lib/generic/modules/fibromyalgia.json, lib/generic/modules/gout.json, lib/generic/modules/injuries.json, lib/generic/modules/lung_cancer.json, lib/generic/modules/lupus.json, lib/generic/modules/med_rec.json, lib/generic/modules/opioid_addiction.json, lib/generic/modules/osteoarthritis.json, lib/generic/modules/pregnancy.json, lib/generic/modules/rheumatoid_arthritis.json, lib/generic/modules/self_harm.json, lib/generic/modules/sinusitis.json, lib/generic/modules/sore_throat.json, lib/generic/modules/total_joint_replacement.json, lib/generic/modules/urinary_tract_infections.json
Swapped the code-display properties that were incorrect in the injuries module. Removed the reason attribute in the Procedure states in the allergic rhinitis module since we can't conclusively point that reason to a single ConditionOnset state. It would probably be a meaningful enhancement to allow reasons to be attributes as well.
=> Fixed reasons

config/synthea.yml, lib/records/exporter.rb, lib/records/fhir.rb, test/unit/fhir_test.rb
Fix synthetichealth/syntheticmass#28 and add configuration option for readable filenames (not UUIDs).
=> Minor changes

config/synthea.yml, lib/records/exporter.rb, lib/records/text.rb, lib/tasks/tasks.rake
I added a text exporter back in December to output a basic text file so you could browse files using the command line or other editors/IDEs without having to wade through XML, HTML, or FHIR JSON.
=> Adds an exporter for a basic text file.

lib/generic/modules/gout.json
Fixes https://github.com/synthetichealth/synthea/issues/136
=> Fixed Gout CarePlan Bug

config/synthea.yml, lib/generic/modules/asthma.json, lib/generic/modules/metabolic_syndrome_care.json, lib/generic/modules/metabolic_syndrome_disease.json, lib/modules/lifecycle.rb, lib/world/sequential.rb
This pull request focuses on model validation.
=> Diabetes Validation

lib/world/sequential.rb
Fixes https://github.com/synthetichealth/synthea/issues/151
=> Fixed undefined 'dead' error

lib/generic/modules/ear_infections.json, lib/generic/states.rb, lib/modules/generic.rb, lib/records/fhir.rb, test/unit/fhir_test.rb
Fixes #157.
Also fixes Rubocop complaint on master.
Running more patients to see if there are other generic module errors lurking in their lurkems.
=> Generic errors

lib/generic/modules/allergies/allergy_panel.json, lib/generic/modules/colorectal_cancer.json, lib/generic/modules/copd.json, lib/generic/modules/dementia.json, lib/generic/modules/dermatitis/early_moderate_eczema_obs.json, lib/generic/modules/dermatitis/early_severe_eczema_obs.json, lib/generic/modules/dermatitis/mid_moderate_eczema_obs.json, lib/generic/modules/dermatitis/mid_severe_eczema_obs.json, lib/generic/modules/dermatitis/moderate_cd_obs.json, lib/generic/modules/dermatitis/severe_cd_obs.json, lib/generic/modules/homelessness.json, lib/generic/modules/metabolic_syndrome_care.json, lib/generic/modules/sore_throat.json, lib/generic/modules/wellness_encounters.json, lib/generic/states.rb, lib/modules/lifecycle.rb, lib/records/fhir.rb, lib/records/record.rb, lib/tasks/graphviz.rb, test/fixtures/generic/vitalsign_observation.json, test/unit/fhir_test.rb, test/unit/generic_states_test.rb
Adds a mandatory `category` field to Observations, in anticipation of SHR FHIR profiles which require Observation.category.
Category is required for all Observations, and must come from the following value set: http://hl7.org/fhir/2017Jan/valueset-observation-category.html
For the wiki:
The `Observation` state type indicates a point in the module where an observation is recorded. Observations include clinical findings, vital signs, lab tests, etc. The Observation state must come after an Encounter state in the module, but must have the same start time as that Encounter; otherwise it will not be recorded in the patient's record.  See the Encounter section above for more details.
Common observation categories include:
- `"vital-signs"` :  Clinical observations measure the body's basic …
=> Observation Categories

lib/modules/cardiovascular_disease.rb
Fixes a bug where the coronary heart disease (CHD) risk was not being calculated, and also fixes the calculation so it uses the correct risk factors  - ie, cholesterol, HDL, blood pressure; previously it was using age for every category.
The resulting %s of CHD are slightly high (seems to hover around 10%, compared to a real-world value of ~6%), but that should be expected since this module does not include any treatment for high blood pressure. 
In a few runs of ~100 patients, this produces ~8 patients with a medication order for simvastatin and ~2 with atorvastatin, so this resolves issue #170
=> Fix coronary heart disease risk calculations, resolves #170

lib/tasks/graphviz.rb
All submodules rendered by graphviz are now placed in a separate 'submodules' directory in the same export path. For example:
```
output/
|_ graphviz/
|_ submodules/
|   |_ <submodule_files>
|_ <main_module_files>
```
One other design change I'd suggest, but haven't implemented yet: I think we should only add the main module files to the index file for the GitHub pages site carousel. That way users aren't viewing submodules, which are often meaningless without context. Thoughts?
=> Submodules directory for Graphviz

lib/modules/lifecycle.rb
Fixed an issue on LastName generation where in one case the name was still getting the hash added if if the config flag was turned off.
=> Fixed an issue on LastName generation where hash added innappropriately

config/healthcare_facilities.json, lib/records/hospital_exporter.rb
=> fix hospital bed count error #217

config/synthea.yml, lib/generic/modules/wellness_encounters.json, lib/modules/lifecycle.rb, lib/records/lookup.rb
Fixes the spelling of creatinine throughout the code.
=> Fix spelling of creatinine.

lib/records/fhir_dstu2.rb, test/unit/fhir_dstu2_test.rb
Fixes #223 and #224 -- two bugs related to the FHIR DSTU2 Exporter.
=> DSTU2 fixes

Gemfile.lock
Gemfile.lock issues with Java after pushing CCDA R2.1 fix.
=> Fix java build.

lib/records/fhir.rb, lib/records/fhir_dstu2.rb, test/unit/fhir_test.rb, test/unit/fhir_validation_test.rb
Fix validation errors in FHIR STU3 and DSTU2. 
Kudos to HAPI FHIR validation!
Fixes #239
=> Fix validation errors in FHIR STU3 and DSTU2. 

lib/records/fhir.rb, lib/records/fhir_dstu2.rb, test/unit/fhir_dstu2_test.rb, test/unit/fhir_test.rb
2 small fixes for FHIR issues, resolves issues #248 and #251
=> FHIR bugfixes

src/main/java/App.java, src/main/java/Graphviz.java, src/main/java/org/mitre/synthea/export/ExportHelper.java, src/main/java/org/mitre/synthea/helpers/TransitionMetrics.java, src/main/java/org/mitre/synthea/modules/Immunizations.java, src/test/java/AppTest.java, src/test/java/GraphvizTest.java, src/test/java/org/mitre/synthea/helpers/UtilitiesTest.java
Adds a unit test on `App.java`, adds a disabled unit test on `Graphviz.java`, and a handful of logic tests.
=> Add some more unit tests.

src/main/resources/templates/ccda/ccda.ftl, src/test/java/org/mitre/synthea/export/CCDAExporterTest.java
Fixes CCDA template to account for changes in `Provider` model.
Also, tracks exceptions in CCDA parsing in our unit test that would have discovered this error earlier.
=> Fix #270 Broken CCDA

build.gradle, src/main/java/org/mitre/synthea/export/FhirDstu2.java, src/main/java/org/mitre/synthea/export/FhirStu3.java, src/main/java/org/mitre/synthea/export/TextExporter.java, src/main/resources/synthea.properties, src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java, src/test/java/org/mitre/synthea/export/FHIRExporterTest.java
Includes 
- candidate fix for #267 includes specific tests to check for DSTU2 `DiagnosticReport.performer`
- mirrored change in STU3
- replaced deprecated method calls TextExporter
=> Export Fixes

src/main/resources/modules/epilepsy.json, src/main/resources/modules/sinusitis.json
- Fix #233 Epilepsy encounter reason.
- Fix #234 Sinusitis follow-up encounter reason.
=> Module fixes using Module Builder

src/main/resources/modules/dermatitis.json
Use RxNorm codes only for Medications. Fixes dermatitis module prescription.
=> Use RxNorm codes only for Medications.

src/main/resources/modules/epilepsy.json, src/main/resources/modules/sinusitis.json
Remove UTF-8 byte-order marks from 2 modules. These don't seem to cause any issues on Mac OS or on Travis but on Windows they cause a lovely error, as seen below. The BOM was added by the module builder so I'll be submitting a change to that as well shortly.
```
Loading C:\Users\dehall\synthea\build\resources\main\modules\sinusitis.json
java.lang.IllegalStateException: Not a JSON Object: "∩╗┐"
at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
at org.mitre.synthea.engine.Module.loadFile(Module.java:89)
at org.mitre.synthea.engine.Module.lambda$loadModules$2(Module.java:57)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at …
```
=> remove byte order marks

src/main/java/org/mitre/synthea/engine/Generator.java, src/test/java/AppTest.java
Fixes #317 - leaves the state in GeneratorOptions as null, and only falls back to the default state later in Generator.init()
=> Fix default state issue

src/main/resources/modules/dementia.json
=> Fixes invalid code in #320.

src/main/java/org/mitre/synthea/world/agents/Person.java, src/main/java/org/mitre/synthea/world/agents/Provider.java, src/main/resources/modules/primary_atrophic_hypothyroidism.json, src/main/resources/synthea.properties
This pull request adds hypothyroidism separately from the veteran modules.
It also fixes a few checkstyle issues and removes an unused deprecated property.
After this PR is merged, the last remaining change for the CHW analysis is the price adjustments.
=> Hypothyroidism

src/main/java/Graphviz.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/TextExporter.java, src/main/java/org/mitre/synthea/modules/EncounterModule.java, src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java
Fix all checkstyle issues except javadocs.
No functional changes.
=> Fix all checkstyle issues except javadocs.

src/main/resources/modules/cystic_fibrosis.json
The finished cystic fibrosis module.
=> Cystic fibrosis

src/main/resources/costs/medications.csv, src/main/resources/modules/medications/otc_antihistamine.json
239981 -> 477045
389128 -> 1363309
=> Change Chlorphenerime to RxnCUIs SCDs on the market.

src/main/resources/modules/allergic_rhinitis.json
=> Fixed duplicate state "Allergic_Rhinitis_Symptom4_Ends"

src/main/java/org/mitre/synthea/modules/CardiovascularDiseaseModule.java, src/main/resources/costs/medications.csv, src/main/resources/modules/attention_deficit_disorder.json, src/main/resources/modules/bronchitis.json, src/main/resources/modules/colorectal_cancer.json, src/main/resources/modules/copd.json, src/main/resources/modules/dementia.json, src/main/resources/modules/fibromyalgia.json, src/main/resources/modules/gout.json, src/main/resources/modules/lupus.json, src/main/resources/modules/opioid_addiction.json, src/main/resources/modules/osteoarthritis.json, src/main/resources/modules/osteoporosis.json, src/main/resources/modules/rheumatoid_arthritis.json, src/main/resources/modules/sinusitis.json, src/main/resources/modules/urinary_tract_infections.json, src/test/java/org/mitre/synthea/world/concepts/CostsTest.java
RxNorm Code fixes: SBDC to SCD, mostly.
=> Sbdc to scd

src/test/java/org/mitre/synthea/world/geography/LocationTest.java
Ensures that all cities in the Demographics file have a corresponding line in the Zipcodes file. This includes changes to both demographics.csv and zipcodes.csv, as there appear to be discrepancies between both. Most notably this fixes Hawaii in that previously the demographics file only contained counties, now it contains cities instead.
Fixes all NullPointerExceptions in #326 , though it is still incomplete in the sense that certain records will not have zip codes, or will have 00000 as the zip code. Many of the lines missing zipcodes are Townships and unincorporated territories in counties, for which a corresponding zipcode isn't easy to find and is painfully manual. We should continue to review, but this current set of changes is important to get in to prevent exceptions.
=> Fix all demographics/zipcode mismatches

src/main/java/org/mitre/synthea/world/concepts/BirthStatistics.java
Fixes a rare birth weight exception that gets thrown when the random "roll of the dice" is less than a tiny minimum value.
=> Fix rare birth weight exception.

src/main/java/org/mitre/synthea/export/CSVExporter.java
Fixes #405 by adding an encounter type header and populating it with `encounter.type`
=> Added encounter class to CSV exporter

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/CDWExporter.java
Do not export CDW folder unless it is enabled.
=> Do not export CDW folder unless it is enabled.

src/main/java/org/mitre/synthea/export/FhirStu3.java
Fixes references in FHIR STU3 `ExplanationOfBenefit` resources... but rather than actually make them full url references, we need to use identifiers to conform to the BlueButton 2.0 IG: 
https://bluebutton.cms.gov/assets/ig/StructureDefinition-bluebutton-outpatient-claim.html
Not the ideal way to make a reference, but anything else and the resources don't validate.
=> Fix #440 but also adheres to BB2.0 IG.

src/main/resources/modules/allergies/severe_allergic_reaction.json, src/main/resources/modules/cystic_fibrosis.json, src/main/resources/modules/injuries.json, src/main/resources/modules/self_harm.json, src/main/resources/modules/veteran_self_harm.json, src/test/resources/generic/imaging_study.json
Addresses the changes requested in #323 
- updates the entry 'Emergency room admission' or 'Emergency Room Admission' to 'Emergency room admission (procedure)' throughout.
=> Emergency Room Admission casing normalization

src/main/java/App.java, src/main/java/org/mitre/synthea/engine/Generator.java, src/test/java/AppTest.java
Adds the flag mentioned in #439, disabling the regeneration of persons if they are generated dead.
=> Dead population overspill

src/main/java/org/mitre/synthea/engine/Event.java, src/main/java/org/mitre/synthea/engine/EventList.java, src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/engine/Module.java, src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/world/agents/Person.java, src/main/java/org/mitre/synthea/world/concepts/ClinicianSpecialty.java, src/main/java/org/mitre/synthea/world/geography/Location.java, src/test/java/org/mitre/synthea/world/geography/LocationTest.java
Fixes all current checkstyle warnings except "Missing a Javadoc comment."
=> Checkstyle Warning Housekeeping

src/main/java/Graphviz.java, src/main/java/org/mitre/synthea/engine/State.java, src/test/java/org/mitre/synthea/engine/StateTest.java, src/test/resources/generic/symptom50.json
Added probability attribute to Symptom (0.0-1.0) which controls whether a patient will have the symptom (whether setSymptom is even called on the patient). Default value is 1.0 (100%)
=> Add probability attribute to Symptom

src/main/resources/modules/veteran.json
Fix #496 Female veteran transitions.
=> Fix #496 Female veteran transitions.

src/main/resources/modules/wellness_encounters.json, src/test/java/org/mitre/synthea/engine/StateTest.java, src/test/resources/generic/observation.json, src/test/resources/generic/observation_groups.json
Fix #495 millimeter mercury UCUM.
=> Fix #495 millimeter mercury UCUM.

src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/FhirDstu2.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/export/FhirStu3.java
=> Fix #513 ndjson references.

.travis.yml
Changed and encrypted Travis token.
Thanks to the reporter of this issue, you know who you are.
=> Travis Security Fix.

src/main/java/org/mitre/synthea/world/concepts/HealthRecord.java, src/main/java/org/mitre/synthea/world/geography/Demographics.java, src/main/java/org/mitre/synthea/world/geography/Location.java, src/test/java/org/mitre/synthea/modules/WeightLossModuleTest.java
Fixes distributions of people across cities, when there is more than one entry for a city in the `demographics.csv` census file.
For example, Houston, Texas has three census entries:
```csv
30338,157.0,Houston,Texas,42127.0,Fort Bend County,716087.0,0.4917125991674196,0.5082874008325804,0.5680482958076323,0.2411327115280685,0.2094982872192904,0.1948268855599948,0.005837279548434758,0.001,0.06708123454273014,0.07878511968517792,0.08258773026182573,0.07365585466570403,0.05972877597275191,0.05622361528696932,0.06847073051179535,0.07417394813758664,0.07879629151206488,0.07253029310684317,0.06885755501775623,0.06649471363116492,0.053591253576730204,0.04033588097535635,0.024668790244760763,0.015214631741673847,0.009331268407330394,0.009472312721778219,0.07,0.05,0.11,0.1,0.14,0.16,0.1,0.11,0.04,0 …
```
=> City distributions

src/main/resources/modules/veteran_ptsd.json
- two new telehealth careplans; separate virtual and regular appts; add sources
=> update ptsd module 

index.html
Save me from having to look at this all the time please.
=> Fix spacing on contact circles.

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/world/agents/Clinician.java, src/main/java/org/mitre/synthea/world/agents/Provider.java, src/test/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderTest.java
Update CSV files to include latitude and longitude of patients, organizations, and providers.
=> CSV Export Lat/Lon Data

.travis.yml
Switch Travis build from `oraclejdk8` to `openjdk8`.
=> Switch Travis build to openjdk8.

src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/export/FhirStu3.java, src/main/java/org/mitre/synthea/world/concepts/Claim.java
This pull request fixes the Payer NullPointerException in #558.
=> Fix Payer NPE #558.

src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/export/FhirStu3.java
Addresses the isssues identified in #572 with the fixes proposed by
@jawalonoski. This fixes the problem in the FHIR R4 and FHIR STU3
exports.
=> Fix coding of w/us-core-race, us-core-ethnicity

src/main/java/org/mitre/synthea/export/FhirStu3.java
This branch adds a geolocation extension to providers in FHIR STU3 output.
=> Added geolocation extension to providers in FHIR STU3 output

build.gradle, src/main/java/App.java, src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/engine/Module.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/test/java/AppTest.java, src/test/java/org/mitre/synthea/engine/GeneratorTest.java, src/test/java/org/mitre/synthea/engine/ModuleTest.java, src/test/java/org/mitre/synthea/helpers/ConfigTest.java, src/test/resources/module/copd_test.json, src/test/resources/test2.properties
This set of commits aims to make Synthea more useable as a library. Together they provide:
- Support for running Synthea from a jar file via java -jar
- Support for building an uber jar with all dependencies bundled
- Support for overriding the bundled configuration file using a local config file to override a subset of settings
- Support for adding modules from a local directory
- Some generalization of the approach from pull request #582 for using a queue to exchange serialized records between threads, e.g. serving generated records from a servlet.
=> Synthea as a Library

src/main/resources/modules/colorectal_cancer.json, src/main/resources/modules/congestive_heart_failure.json, src/main/resources/modules/lung_cancer.json, src/main/resources/modules/metabolic_syndrome_care.json, src/main/resources/modules/veteran_prostate_cancer.json
Hello people,
This pull request eliminates all occurrences of the unicode zero width space across JSON files.
=> Eliminates the unicode zero width space across JSON files (fixes #590)

src/main/resources/modules/lung_cancer.json
This PR fixes an invalid code within the lung cancer module.
=> Fix invalid code.

src/main/java/org/mitre/synthea/datastore/DataStore.java, src/main/java/org/mitre/synthea/engine/Module.java, src/main/java/org/mitre/synthea/engine/PhysiologySimulator.java, src/main/java/org/mitre/synthea/export/CPCDSExporter.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/PrevalenceReport.java, src/main/java/org/mitre/synthea/export/ReportExporter.java, src/main/java/org/mitre/synthea/helpers/RandomCollection.java, src/main/java/org/mitre/synthea/modules/BloodPressureValueGenerator.java, src/main/java/org/mitre/synthea/modules/DeathModule.java, src/main/java/org/mitre/synthea/modules/Immunizations.java, src/main/java/org/mitre/synthea/world/agents/Clinician.java, src/test/java/org/mitre/synthea/engine/GeneratorTest.java, src/test/java/org/mitre/synthea/world/geography/DemographicsTest.java
This PR fixes dozens of checkstyle warnings and complaints: mostly lines that are longer than 100 characters, missing JavaDoc comments, and other miscellaneous checkstyle fixes.
This PR contains no functional changes.
There are still checkstyle issues remaining, all of which are missing JavaDoc comments.
=> Fix checkstyle warnings and add javadoc comments. No functional changes.

src/main/java/org/mitre/synthea/export/CDWExporter.java, src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/export/ReportExporter.java, src/main/java/org/mitre/synthea/modules/DeathModule.java
This pull request fixes a few checkstyle issues, but make adjustments to the FHIR R4 exporter to account for US Core "Must Support" elements that were previously overlooked.
=> US Core Must Support

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/test/java/org/mitre/synthea/modules/WeightLossModuleTest.java, src/test/java/org/mitre/synthea/world/concepts/NHANESSampleTest.java, src/test/java/org/mitre/synthea/world/concepts/PediatricGrowthTrajectoryTest.java
Fix some accumulated checkstyle warnings...
No functional changes.
=> Checkstyle fixes.

src/main/resources/modules/covid19/admission.json, src/main/resources/modules/covid19/outcomes.json
Ditching my mihin branch in favor of this smaller change
=> Ventilator attribute

src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/world/agents/Person.java, src/main/java/org/mitre/synthea/world/agents/Provider.java, src/main/java/org/mitre/synthea/world/agents/behaviors/ProviderFinderNearest.java
Update provider finder code so that veterans are more likely to use VA facilities.
=> Update provider finder code for veterans

src/main/java/org/mitre/synthea/engine/State.java, src/main/java/org/mitre/synthea/helpers/ExpressionProcessor.java, src/main/java/org/mitre/synthea/helpers/physiology/IoMapper.java, src/main/resources/physiology/generators/circulation_hemodynamics.yml, src/test/java/org/mitre/synthea/helpers/ExpressionProcessorTest.java, src/test/java/org/mitre/synthea/helpers/physiology/IoMapperTest.java
Adds a bit more functionality to expression processing. In particular it allows use of more types of variables in addition to Decimal types: List<Decimal>, Boolean, and String.
=> Expression processor

src/main/java/org/mitre/synthea/export/FhirR4.java
This is to fix https://github.com/synthetichealth/synthea/issues/726
=> fix SNOMED CT Code for "Patient" in FHIR R4 Export

src/main/java/App.java, src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/engine/Module.java
Fixes the issue on MacOS, need to confirm fix on Windows.
Update 6/26 - confirmed to work on Windows.
=> Fix for issue #734 - exception when using a local module directory

src/main/java/org/mitre/synthea/engine/Generator.java
Commented out init() in Generator.java to remove second "Running with options:" statement. 
All options minimally tested except for _run_synthea -m metabolic*_
=> remove repeated print lines

src/main/java/org/mitre/synthea/helpers/ExpressionProcessor.java
=> Fixes thread safety issue with physiology generators

src/main/java/org/mitre/synthea/engine/State.java, src/main/java/org/mitre/synthea/modules/BloodPressureValueGenerator.java, src/main/resources/biometrics.yml, src/main/resources/modules/hypertension.json, src/main/resources/modules/medications/hypertension_medication.json
This pull request updates the hypertension module to exclude certain comorbidities (they should be handled differently), account for different medication pathways and escalation from mono, to dual, to tritherapy.
This Hypertension model reflects the treatment of Primary Hypertension (HTN) in Adults. 
Hypertension diagnosis definitions, pharmacologic treatment thresholds, and control target recommendations diverge across clinical guidelines. However, the model was informed by the following hypertension guidelines and subsequent updates:
- 2018 ESC/ESH Guidelines for the management of arterial hypertension: The Task Force for the management of arterial hypertension of the European Society of Cardiology (ESC) and the European Society of Hypertension (ESH)
- 2017 …
=> Hypertension update

gradle/wrapper/gradle-wrapper.properties
Fix #751 thanks to https://github.com/gradle/gradle/issues/10248#issuecomment-647923554
=> Upgrade gradle version

src/main/java/org/mitre/synthea/helpers/SimpleCSV.java
Method proposed as first step to address [Issue #786](https://github.com/synthetichealth/synthea/issues/786#issue-699245953)
=> Added new method using standard library to validate csv output

src/main/resources/modules/cerebral_palsy.json
New revised clinical module for cerebral palsy with clinical feedback addressed. Opened new pull request to put module in correct location. Attaching clinical feedback previously received (closed pull request #805). Thank you for your patience! Module Companion Guide with additional module information also attached (no updates since previous pull request). 
[20200923_Module_Companion_Guide_Cerebral Palsy_clean.docx](https://github.com/synthetichealth/synthea/files/5662594/20200923_Module_Companion_Guide_Cerebral.Palsy_clean.docx)
[CPReview_2020-10-22 (002).docx](https://github.com/synthetichealth/synthea/files/5662597/CPReview_2020-10-22.002.docx)
=> New revised clinical module for cerebral palsy

src/main/resources/modules/spina_bifida.json
This pull request is to add a new clinical module Spina Bifida. Please see the attached detailed documentation about this new module. 
[20201201_Module_Companion_Guide_Spina_Bifida.docx](https://github.com/synthetichealth/synthea/files/5652043/20201201_Module_Companion_Guide_Spina_Bifida.docx)
=> New clinical module Spina Bifida.

src/main/java/org/mitre/synthea/export/CSVExporter.java
Fix for #765 
- Added iteration through all instances of all series in an imaging study when creating the `imaging_studies.csv` export file.
- Added `SERIES_UID` and `INSTANCE_UID` fields.
=> Fix for #765: Made all imaging study instances get exported in CSV

src/main/resources/modules/sepsis.json, src/main/resources/modules/sepsis_v2.json
New sepsis clinical module. See module companion guide for additional module information. Thanks! 
[20201201_Module_Companion_Guide_Sepsis.docx](https://github.com/synthetichealth/synthea/files/5662569/20201201_Module_Companion_Guide_Sepsis.docx)
=> New clinical sepsis module

build.gradle, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/resources/templates/ccda/results.ftl, src/main/resources/templates/ccda/vital_signs.ftl, src/test/java/org/mitre/synthea/export/CCDAExporterTest.java
Main purpose:
- Fix references from Explanation of Benefit and Coverage resources
- Switch references from PractitionerRole to be logical instead of literal
Bonus features:
- Increase to heap space to address intermittent CI failures
- Attempt to fix intermittent CCDA exporter unit test failure related to empty unit on values
=> Transaction Bundle Fixes

src/main/java/org/mitre/synthea/engine/Components.java, src/main/java/org/mitre/synthea/export/FhirDstu2.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/export/FhirStu3.java, src/main/java/org/mitre/synthea/helpers/ChartRenderer.java, src/main/resources/modules/total_joint_replacement/functional_status_assessments.json, src/test/java/org/mitre/synthea/editors/GrowthDataErrorsEditorTest.java, src/test/java/org/mitre/synthea/engine/FixedRecordTest.java, src/test/java/org/mitre/synthea/export/FHIRDSTU2ExporterTest.java, src/test/java/org/mitre/synthea/helpers/ChartRendererTest.java, src/test/java/org/mitre/synthea/helpers/UtilitiesTest.java
1. Fix an array out of bounds error in the tests.
2. Fix attachment size in R4 exporter
3. Fix encounter period bounds in DSTU exporter
4. Fix units in functional assessment sub module
=> Assorted Unit Test Fixes

src/main/resources/modules/encounter/vitals.json, src/main/resources/modules/mend_program.json, src/main/resources/modules/weight_loss/mend_week.json
This Pull Request adds a module to simulate the MEND (Mind, Exercise, Nutrition, Do It!) program, described here - http://www.mendfoundation.org. MEND is one of the world's largest evidence-based healthy lifestyle programs that empowers children, with the support of their families, to reach and maintain a healthy weight. While the program is targeted at 7 - 13 year olds, it is applied more widely in practice. This module allows children between 5 - 17 to participate in the program. This module depends on attributes set by Synthea's  java `WeightLossModule`. It adds and uses the `mend_program.json` module as well as the `weight_loss/mend_week.json` and `encounter/vitals.json` submodules.
=> MEND Program Module

src/main/java/org/mitre/synthea/engine/Logic.java, src/main/java/org/mitre/synthea/engine/State.java, src/main/java/org/mitre/synthea/helpers/Utilities.java, src/test/java/org/mitre/synthea/helpers/UtilitiesTest.java
Support fractional durations in case they are used in a GMF module
=> Fractional Durations

.gitignore, build.gradle, src/main/java/org/mitre/synthea/export/BB2RIFExporter.java, src/test/java/org/mitre/synthea/export/BB2RIFExporterTest.java
- Add code translation for medications
- Refactor condition code translation to extract a common utility class for code translations.
Note: copy the two JSON files from [here](https://communityshare.mitre.org/sites/healthsim/SharedDocuments/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fhealthsim%2FSharedDocuments%2FCMS%20Engagement%2FJSON%20Map%20Files&FolderCTID=0x012000DEF68DBBC4AD3B46B8E5835D9F25782D&View=%7BA73A4173%2D3405%2D49CB%2D9692%2DE83803BD2009%7D) to `$SYNTHEA_HOME/src/main/resources`
=> Prescription Export Updates

src/main/java/org/mitre/synthea/world/geography/Location.java
=> Fix default value for SDOH file.

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java, src/main/java/org/mitre/synthea/helpers/Config.java
Changed BeneficiaryID, ClaimId, and PDEId from a Int to Long.
=> Changed data types for ClaimId and Beneificiary Id to Long from Int

src/main/java/Graphviz.java, src/main/java/org/mitre/synthea/engine/Module.java, src/main/java/org/mitre/synthea/helpers/Attributes.java, src/main/java/org/mitre/synthea/helpers/Concepts.java, src/main/java/org/mitre/synthea/helpers/ModuleOverrides.java, src/main/java/org/mitre/synthea/helpers/Utilities.java
=> Fix utility tasks so they work when run from a jar file

src/main/resources/modules/cerebral_palsy.json, src/main/resources/modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json, src/main/resources/modules/sepsis.json, src/main/resources/modules/spina_bifida.json
Revised "Last Updated" field in Module Remarks to be "Date Created" since this field may not be updated as module updates are made. 
Thanks, 
Casey
=> Update Module Remarks in Cerebral Palsy, Prescribing Opioids for Chronic Pain, Sepsis, and Spina Bifida Modules

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
=> Remove bad character Windows-1252.

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/MetadataExporter.java, src/main/resources/synthea.properties
- Make generator thread pool size configurable
- Default pool size to number of processor cores available to JVM
=> Generator Thread Pool Sizing

src/main/java/org/mitre/synthea/export/FhirR4.java
My theory is that somehow the Reference for the provider is being passed null to its constructor. This change DRYs out the code, which was needed anyway, but ensures that Reference should always be OK.
My guess is that somehow when the code is trying to look up the full URL for either the Organization or PractitionerRole resource, it isn't finding it and returning null.
=> Trying to fix the CI test failures with ExplanationOfBenefit

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
- Skip claims for services rendered by VA facilities.
- Move urgent care claims to carrier file.
- Move IHS center claims to carrier file.
=> RIF PRVDR_NUM fixes

src/main/java/App.java
Fixes two generator options that are loaded only from the default config file at options initialization time.
=> Fix generator options loading from non-default config file.

src/main/resources/modules/acute_myeloid_leukemia.json, src/main/resources/modules/lookup_tables/AML.csv
New AML Module (with lookup table) is ready to be posted for public use on 3/11/22. This module was previously reviewed  by the MITRE team in July 2021 and clinical feedback has been incorporated. Final Module Companion Guide also ready for posting and attached. 
Thanks, 
Casey
[20220301_Module_Companion_Guide_Leukemia_FINAL_508.pdf](https://github.com/synthetichealth/synthea/files/8209377/20220301_Module_Companion_Guide_Leukemia_FINAL_508.pdf)
=> New AML Module- Ready to Post in Synthea

build.gradle
This PR is meant to address deprecated gradle features reported in #1023
=> Fix deprecated gradle features.

src/main/resources/costs/devices.csv, src/main/resources/costs/supplies.csv, src/main/resources/modules/sleep_apnea.json
This is a basic Sleep Apnea module derived from Harrison's Principles of Internal Medicine. 15th edition. 2001.
> Sleep apnea ... is one of the leading causes of excessive daytime sleepiness.
> ...
> Epidemiologic studies have established a prevalence of clinically important sleep apnea of at least 2% in middle-aged women and 4% in middle-aged men.
> ...
> ...  inevitably results in snoring. In most patients, snoring antedates the development of obstructive events by many years.
> ...
> Over 50% of patients with Obstructive Sleep Apnea (OSA) have systemic hypertension.
> ...
> the typical patient is a male aged 30 to 60 years who presents with a history of snoring, excessive daytime sleepiness ... and often mild to moderate hypertension.
> ...
> The definitive investigation for suspected …
=> Basic Sleep Apnea module.

src/main/java/org/mitre/synthea/modules/LifecycleModule.java
One of a few PRs I'll be issuing with features broken out from the `cabg_cardio_gmf_htn_trial` branch, this updates the cholesterol model for individuals without diabetes.  The goal is a more realistic distribution of cholesterol numbers, based primarily on this report: https://www.cdc.gov/nchs/data/databriefs/db363-h.pdf
=> Cholesterol model for individuals without diabetes

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java, src/main/java/org/mitre/synthea/export/CPCDSExporter.java, src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/world/agents/Payer.java, src/main/java/org/mitre/synthea/world/agents/Person.java, src/main/java/org/mitre/synthea/world/agents/behaviors/IPayerAdjustment.java, src/main/java/org/mitre/synthea/world/agents/behaviors/PayerAdjustmentFixed.java, src/main/java/org/mitre/synthea/world/agents/behaviors/PayerAdjustmentNone.java, src/main/java/org/mitre/synthea/world/agents/behaviors/PayerAdjustmentRandom.java, src/main/java/org/mitre/synthea/world/agents/behaviors/PayerFinderBestRates.java, src/main/java/org/mitre/synthea/world/concepts/Claim.java, src/main/java/org/mitre/synthea/world/concepts/CoverageRecord.java, src/test/java/org/mitre/synthea/world/agents/PayerTest.java, src/test/java/org/mitre/synthea/world/concepts/LossOfCareHealthRecordTest.java
Switch financial fields and calculations to use BigDecimal instead of double to improve accuracy.
=> Claims Financial Calculations

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/test/java/org/mitre/synthea/export/BB2RIFExporterTest.java
This PR adds unit tests to validate the content of the carrier RIF file and fixes issues highlighted by those tests.
=> RIF Export Validation

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/helpers/DefaultRandomNumberGenerator.java, src/main/java/org/mitre/synthea/helpers/RandomCollection.java, src/main/java/org/mitre/synthea/helpers/RandomNumberGenerator.java, src/main/java/org/mitre/synthea/world/agents/Clinician.java, src/main/java/org/mitre/synthea/world/agents/Person.java, src/main/java/org/mitre/synthea/world/agents/Provider.java, src/main/java/org/mitre/synthea/world/geography/Demographics.java, src/main/java/org/mitre/synthea/world/geography/Location.java, src/test/java/org/mitre/synthea/engine/GeneratorTest.java, src/test/java/org/mitre/synthea/export/CodeResolveAndExportTest.java, src/test/java/org/mitre/synthea/export/ExporterTest.java, src/test/java/org/mitre/synthea/export/HospitalExporterTestDstu2.java, src/test/java/org/mitre/synthea/export/HospitalExporterTestR4.java, src/test/java/org/mitre/synthea/export/HospitalExporterTestStu3.java, src/test/java/org/mitre/synthea/export/ValueSetCodeResolverTest.java, src/test/java/org/mitre/synthea/helpers/RandomCollectionTest.java, src/test/java/org/mitre/synthea/modules/EncounterModuleTest.java, src/test/java/org/mitre/synthea/modules/covid/C19ImmunizationModuleTest.java, src/test/java/org/mitre/synthea/world/agents/PayerTest.java, src/test/java/org/mitre/synthea/world/agents/PersonTest.java, src/test/java/org/mitre/synthea/world/agents/ProviderTest.java, src/test/java/org/mitre/synthea/world/agents/behaviors/PayerFinderTest.java, src/test/java/org/mitre/synthea/world/geography/DemographicsTest.java
This probably won't merge cleanly into master when the time comes, but it works.
```
./run_synthea -s 0 -cs 0 -r 20220523 -f ../hrsa-hab-population/test-move-states.json -e 20101231 "North Carolina"
```
Make sure you use `-s`, `-cs`, and `-r`.
=> Fixes for regeneration of data.

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
=> Carrier Line Item Diagnosis Codes 

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java
This tiny PR adds a new `syntheticData` attribute to the RIF manifest as requested by the BFD team.
See https://github.com/CMSgov/beneficiary-fhir-data/blob/master/apps/bfd-pipeline/bfd-pipeline-ccw-rif/src/main/resources/bfd-manifest.xsd
=> Add new attribute to RIF manifest.

src/main/java/org/mitre/synthea/world/geography/CMSStateCodeMapper.java
Fix incorrect state code found during data analysis.
=> Fix incorrect state code.

build.gradle, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/FhirGroupExporterR4.java, src/main/java/org/mitre/synthea/export/FhirPractitionerExporterDstu2.java, src/main/java/org/mitre/synthea/export/FhirPractitionerExporterR4.java, src/main/java/org/mitre/synthea/export/FhirPractitionerExporterStu3.java, src/main/java/org/mitre/synthea/export/FhirR4.java, src/main/java/org/mitre/synthea/export/HospitalExporterDstu2.java, src/main/java/org/mitre/synthea/export/HospitalExporterR4.java, src/main/java/org/mitre/synthea/export/HospitalExporterStu3.java, src/test/java/org/mitre/synthea/export/HospitalExporterTestDstu2.java, src/test/java/org/mitre/synthea/export/HospitalExporterTestR4.java, src/test/java/org/mitre/synthea/export/PractitionerExportTestDstu2.java, src/test/java/org/mitre/synthea/export/PractitionerExportTestR4.java, src/test/java/org/mitre/synthea/export/PractitionerExportTestStu3.java
Modifies FHIR bulk export to write NDJSON files for:
-  `Organization`
- `Location` (R4 only)
- `Practitioner`
- `PractitionerRole` (R4 only)
Addresses #1069
=> New NDJSON files

src/main/java/org/mitre/synthea/world/agents/PayerManager.java
- Fix loading of plans when payer does not exist because it is out of state.
=> Payer Tweak

src/main/java/org/mitre/synthea/export/BB2RIFExporter.java, src/main/java/org/mitre/synthea/export/CPCDSExporter.java, src/main/java/org/mitre/synthea/export/CSVExporter.java, src/main/java/org/mitre/synthea/helpers/ConsolidatedServicePeriods.java, src/main/java/org/mitre/synthea/world/concepts/Claim.java, src/test/java/org/mitre/synthea/export/BB2RIFExporterTest.java, src/test/java/org/mitre/synthea/helpers/ConsolidatedServicePeriodsTest.java, src/test/java/org/mitre/synthea/world/agents/PayerTest.java
Fixes #1173 
- Update BFD HHA exporter to add total charge revenue center line to all claims
- Update BFD SNF exporter to add total charge revenue center line to all claims
- Consolidate HHA claim periods by provider
- Separate consolidated claim lines by clinician
- Fix bug in claim cost aggregation for medications
- Rename some claim methods for clarity
- Fix bug in SNF.REV_CNTR_RATE_AMT calculation
=> BFD RIF total charge claim line

src/main/java/org/mitre/synthea/engine/Logic.java, src/main/java/org/mitre/synthea/engine/State.java, src/main/java/org/mitre/synthea/engine/Transition.java, src/main/java/org/mitre/synthea/world/concepts/TelemedicineConfig.java, src/main/resources/synthea.properties, src/main/resources/telemedicine_config.json, src/test/java/org/mitre/synthea/engine/TransitionTest.java, src/test/java/org/mitre/synthea/export/ExportBreakerTest.java, src/test/java/org/mitre/synthea/world/concepts/TelemedicineConfigTest.java, src/test/resources/generic/virtual_medicine_transition.json
This PR introduces a TypeOfCare transition. 
Functionality is described in the wiki on the [Transition section of the GMF page](https://github.com/synthetichealth/synthea/wiki/Generic-Module-Framework%3A-Transitions#typeofcare).
=> TypeOfCare Transition

src/main/resources/modules/gallstones.json, src/main/resources/modules/sepsis.json
=> Address Module Issues

src/main/java/org/mitre/synthea/export/rif/CodeMapper.java, src/main/java/org/mitre/synthea/export/rif/HospiceExporter.java, src/test/java/org/mitre/synthea/export/rif/BB2RIFExporterTest.java, src/test/java/org/mitre/synthea/export/rif/CodeMapperTest.java, src/test/resources/export/unweighted_code_map.json, src/test/resources/export/weighted_code_map.json
Also
- Break out CodeMapper tests into new separate test file
- Fix a checkstyle warning in HospiceExporter
=> Update CodeMapper to support map files with weights.

src/main/resources/modules/acute_myeloid_leukemia.json, src/main/resources/modules/breast_cancer.json, src/main/resources/modules/breast_cancer/chemotherapy_breast.json, src/main/resources/modules/breast_cancer/surgery_therapy_breast.json, src/main/resources/modules/cerebral_palsy.json, src/main/resources/modules/colorectal_cancer.json, src/main/resources/modules/congestive_heart_failure.json, src/main/resources/modules/contraceptives/female_sterilization.json, src/main/resources/modules/copd.json, src/main/resources/modules/dementia.json, src/main/resources/modules/gallstones.json, src/main/resources/modules/injuries.json, src/main/resources/modules/lung_cancer.json, src/main/resources/modules/metabolic_syndrome/amputations.json, src/main/resources/modules/opioid_addiction.json, src/main/resources/modules/pregnancy.json, src/main/resources/modules/veteran_lung_cancer.json
Adjusts modules to tune inpatient length of stay. See #1169
Some `outpatient` encounters were incorrectly classified as `inpatient`.
Many inpatient encounters were modified so that length of stay follows an exponential distribution.
=> Inpatient Length of Stay

src/main/java/org/mitre/synthea/engine/Generator.java, src/main/java/org/mitre/synthea/export/CDWExporter.java, src/main/java/org/mitre/synthea/export/Exporter.java, src/main/java/org/mitre/synthea/export/rif/BB2RIFExporter.java, src/main/java/org/mitre/synthea/export/rif/BeneficiaryExporter.java, src/main/java/org/mitre/synthea/export/rif/CarrierExporter.java, src/main/java/org/mitre/synthea/export/rif/RIFExporter.java, src/main/java/org/mitre/synthea/export/rif/SNFExporter.java, src/main/java/org/mitre/synthea/modules/LifecycleModule.java, src/main/java/org/mitre/synthea/world/agents/Person.java, src/main/java/org/mitre/synthea/world/agents/behaviors/planeligibility/QualifyingConditionCodesEligibility.java, src/main/resources/export/bfd_field_values.tsv, src/main/resources/modules/atrial_fibrillation.json, src/main/resources/modules/chronic_kidney_disease.json, src/main/resources/modules/dialysis.json, src/main/resources/modules/heart/avrr/antithrombotic.json, src/main/resources/modules/heart/cabg/operation.json, src/main/resources/modules/heart/chf_meds_hfmef.json, src/main/resources/modules/heart/chf_meds_hfref_nyha2.json, src/main/resources/modules/heart/chf_meds_hfref_nyha3.json, src/main/resources/modules/heart/chf_meds_hfref_nyha4.json, src/main/resources/modules/kidney_transplant.json, src/main/resources/modules/lung_cancer.json, src/main/resources/modules/metabolic_syndrome/kidney_conditions.json, src/main/resources/modules/veteran_lung_cancer.json, src/main/resources/payers/eligibility_input_files/ssd_eligibility.csv, src/test/java/org/mitre/synthea/export/rif/BB2RIFExporterTest.java
See #1232.
This PR is a work-in-progress.
=> Medicare eligibility and entitlements

src/main/resources/modules/contraceptives/female_sterilization.json, src/main/resources/modules/cystic_fibrosis.json, src/main/resources/modules/heart/avrr/referral.json, src/main/resources/modules/heart/avrr/savrr_operation.json, src/main/resources/modules/heart/tavr/operation.json, src/main/resources/modules/lung_cancer.json, src/main/resources/modules/metabolic_syndrome/amputations.json, src/main/resources/modules/metabolic_syndrome_care.json, src/main/resources/modules/opioid_addiction.json, src/main/resources/modules/pregnancy.json, src/main/resources/modules/total_joint_replacement.json, src/test/java/org/mitre/synthea/world/concepts/CostsTest.java
Repairing these inpatient encounter reasons also corrects weird primary diagnosis codes and admission codes in RIF exports.
=> Repair inpatient encounter reason codes.

README.md
Adds a link to our User Survey https://forms.office.com/g/3Mz9Ha8MLz in the readme, with a couple emoji just to highlight it a little bit
=> Add survey link to readme

src/main/java/org/mitre/synthea/export/CSVExporter.java
This PR sorts patient expenses and payer transitions by start time.
This helps comprehension of the CSV output when browsing, and also aids in the interpretation of `diff` when comparing multiple runs (e.g., see #1236).
The sortation is per patient, so a `diff` may continue to show discrepancies if `generate.thread_pool_size` is not restricted to `1`.
=> CSV sort patient expenses and payer transitions by time.

src/main/java/org/mitre/synthea/engine/PhysiologySimulator.java
Fix how physiology SBMLs are being loaded to ensure they work when running from JAR. Also cleans up a few things which are now unused. Fixes #1296 
Tested on MacOS native and JAR, and Windows native and JAR.
=> Fix physiology simulations when running from JAR

src/main/java/org/mitre/synthea/export/rif/BB2RIFExporter.java, src/main/java/org/mitre/synthea/export/rif/BB2RIFStructure.java, src/main/java/org/mitre/synthea/export/rif/BeneficiaryExporter.java, src/test/java/org/mitre/synthea/export/rif/BB2RIFExporterTest.java
Fixes #1294 by removing the export of the BFD beneficiary history file.
=> Remove BFD beneficiary history file

src/main/resources/modules/kidney_transplant.json, src/main/resources/modules/metabolic_syndrome/kidney_conditions.json
=> Resolve weirdness of ESRD diagnosis and transplant interaction

config/aws/CloudFormation.yaml
This will automate Synthea deployment on AWS.
=> Synthea deployment on AWS using cloudformation template

src/main/java/org/mitre/synthea/modules/covid/C19Vaccine.java
Fixes #1436, COVID-19 vaccine descriptions.
References: https://www2a.cdc.gov/vaccines/iis/iisstandards/vaccines.asp?rpt=cvx
Tested with HL7 FHIR Validator website.
=> COVID-19 Vaccine Descriptions

src/main/resources/costs/procedures.csv, src/main/resources/modules/lung_cancer.json, src/main/resources/modules/veteran_lung_cancer.json
=> Fix #1414: Update SNOMED code for “Fiberoptic bronchoscopy”

src/main/java/org/mitre/synthea/world/agents/Provider.java, src/main/java/org/mitre/synthea/world/agents/behaviors/payeradjustment/PayerAdjustmentFixed.java, src/main/java/org/mitre/synthea/world/agents/behaviors/payeradjustment/PayerAdjustmentRandom.java, src/test/java/org/mitre/synthea/world/agents/ProviderTest.java, src/test/java/org/mitre/synthea/world/agents/behaviors/PlanFinderTest.java, src/test/java/org/mitre/synthea/world/agents/behaviors/payeradjustment/PayerAdjustmentTest.java, src/test/java/org/mitre/synthea/world/concepts/ClinicianSpecialtyTest.java
Increase some unit test coverage.
=> Additional unit tests.

src/main/resources/modules/allergies.json, src/main/resources/modules/breast_cancer.json, src/main/resources/modules/breast_cancer/surgery_therapy_breast.json, src/main/resources/modules/breast_cancer/tnm_diagnosis.json, src/main/resources/modules/cerebral_palsy.json, src/main/resources/modules/colorectal_cancer.json, src/main/resources/modules/congestive_heart_failure.json, src/main/resources/modules/dementia.json, src/main/resources/modules/dental_and_oral_examination.json, src/main/resources/modules/dentures.json, src/main/resources/modules/heart/tavr/alt_access.json, src/main/resources/modules/hiv/hiv_baseline.json, src/main/resources/modules/injuries.json, src/main/resources/modules/injuries/broken_jaw.json, src/main/resources/modules/opioid_addiction.json, src/main/resources/modules/osteoarthritis.json, src/main/resources/modules/pregnancy.json, src/main/resources/modules/prescribing_opioids_for_chronic_pain_and_treatment_of_oud.json, src/main/resources/modules/spina_bifida.json
This pull request aims to update the SNOMED codes across various Synthea modules which came from the meeting we had with Dylan and Carlos, ensuring they are current and active
=> Updated the remaining Snomed codes from the discussion with Dylan and Carlos
